### PR TITLE
Added textureCache in GradientFilter

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/235)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/235#-:-KjI1pJqMiZVTKLtiPlZ:bnfp4nl)*

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/235#-:-KjI3vs8g8yg4yaxrCUr:bnfp4nl)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[openfl/filters/GradientFilter.hx, line 54 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/235#-Kjb5gi2wTXU58GviaUe:-Kjb5gi2wTXU58GviaUf:bhs8r2b) ([raw file](https://github.com/fishingcactus/openfl/blob/a8a2b4f86ea37de0af55273040e225bd18565b2b/openfl/filters/GradientFilter.hx#L54)):*
> if(__textureCacheMap.exists(hash)) {
> 			__lookupTexture = __textureCacheMap.get(hash);

could get() and test if not null to avoid searching the map twice

---

*[openfl/filters/GradientFilter.hx, line 158 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/235#-Kjb5FsNLZMwZBI_HP_P:-Kjb5FsNLZMwZBI_HP_Q:b7n2xsn) ([raw file](https://github.com/fishingcactus/openfl/blob/a8a2b4f86ea37de0af55273040e225bd18565b2b/openfl/filters/GradientFilter.hx#L158)):*
> buffer[0] = angle;
> 		buffer[1] = blurX;
> 		buffer[2] = blurY;
> 		buffer[3] = distance;
> 		buffer[4] = cast type;
> 		buffer[5] = knockout ? 1 : 0;
> 		buffer[6] = quality;
> 		buffer[7] = strength;
>  

those parameters shouldn't be necessary... the gradient texture doesn't depend on them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/235)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/235#-:-KjbFWDe8nXhPO93f3tz:bnfp4nl)*

**Pull request merged**
