### PR TITLE
Feature/reduce allocations

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/155)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 237 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtgPJUibLqkCFZsgfP:-KbtgPJUibLqkCFZsgfQ:bbti1re) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/display/DisplayObject.hx#L237)):*
> ```Haxe
> 	}
> 
> 	public inline function convertToLocal (pos:Point) {
> ```

is this supposed to be a different behavior than globalToLocal()?

---

*[openfl/events/MouseEvent.hx, line 50 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtgafZdDGdTOXKE7Jw:-KbtgafZdDGdTOXKE7Jx:bbmqqkb) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/events/MouseEvent.hx#L50)):*
> ```Haxe
> 
> 
> 	public function new (type:String = "unset", bubbles:Bool = true, cancelable:Bool = false, localX:Float = 0, localY:Float = 0, relatedObject:InteractiveObject = null, ctrlKey:Bool = false, altKey:Bool = false, shiftKey:Bool = false, buttonDown:Bool = false, delta:Int = 0, commandKey:Bool = false, clickCount:Int = 0) {
> ```

would be safer if ctor was made private as it doesn't initialize all fields properly anymore

---

*[openfl/utils/UnshrinkableArray.hx, line 56 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-Kbtiy3UemkiPscrywyq:-Kbtiy3V6gZVdlOYFQiI:bbi5fym) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/utils/UnshrinkableArray.hx#L56)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>
>      for(i in 0...this._length)
>         {
>             if(this._items[i] == item)
>             {
>                 found = i;
>                 break;
>             }
>         }
</details>

indexOf ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/utils/UnshrinkableArray.hx, line 75 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtoVio2Mu4FULmJUIT:-KbtoVio2Mu4FULmJUIU:bc6mz9f) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/utils/UnshrinkableArray.hx#L75)):*
> ```Haxe
>         for(i in from...this._length - count)
>         {
>             this._items[i] = this._items[i + count];
> ```

this will crash if from is >= length or if count < 0 (on Array, this would result into an empty array)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by crazyjul** [comment]
Reviewed 5 of 7 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by gogoprog** [comment]
Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 237 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtgPJUibLqkCFZsgfP:-KbxwFLdxcNFAaFBXIYc:bn0dw8l) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/display/DisplayObject.hx#L237)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

is this supposed to be a different behavior than globalToLocal()?
</blockquote></details>

Yes : never clone the input point (I updated the code to match Pieter's changes)

---

*[openfl/utils/UnshrinkableArray.hx, line 56 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-Kbtiy3UemkiPscrywyq:-KbxyOM5YjS-_8bu3FTT:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/utils/UnshrinkableArray.hx#L56)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

>      for(i in 0...this._length)
>         {
>             if(this._items[i] == item)
>             {
>                 found = i;
>                 break;
>             }
>         }

indexOf ?
</blockquote></details>

Done.

---

*[openfl/utils/UnshrinkableArray.hx, line 75 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtoVio2Mu4FULmJUIT:-Kby1jPcHhQBaju_qkqj:b2ufyoe) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/utils/UnshrinkableArray.hx#L75)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

this will crash if from is >= length or if count < 0 (on Array, this would result into an empty array)
</blockquote></details>

Done by matching the JS array behavior

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by gogoprog** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/events/MouseEvent.hx, line 50 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-KbtgafZdDGdTOXKE7Jw:-Kby2TgHubqLtPDIsLNQ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/4812945cf031d58c023f6b87c36661c45159085e/openfl/events/MouseEvent.hx#L50)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

would be safer if ctor was made private as it doesn't initialize all fields properly anymore
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155#-:-Kc2XQ2CjA1No2Nm9hFT:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/155)*

**Pull request merged**
