### PR TITLE
Avoid null children in addChildAt

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/191)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 99 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/191#-Kdj_S9ADpSoy1i_wXKt:-Kdj_S9ADpSoy1i_wXKu:b-d4cast) ([raw file](https://github.com/fishingcactus/openfl/blob/e93d8708ffad066a6c8a21396935f829c489e91d/openfl/display/DisplayObjectContainer.hx#L99)):*
> if(childIndexToRemove > -1) {
> 			removeChildAt(childIndexToRemove < index ? childIndexToRemove : childIndexToRemove + 1);
> 		}
>  
Won't work if you insert a child at the same position. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/191)*

**Comment by gogoprog** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 99 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/191#-Kdj_S9ADpSoy1i_wXKt:-Kdjc99LVUL9MV7A1X_D:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/e93d8708ffad066a6c8a21396935f829c489e91d/openfl/display/DisplayObjectContainer.hx#L99)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> if(childIndexToRemove > -1) {
> 			removeChildAt(childIndexToRemove < index ? childIndexToRemove : childIndexToRemove + 1);
> 		}
>  
Won't work if you insert a child at the same position. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/191)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/191#-:-KdjcDt2-wDmAFqkLqiy:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/191)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/191)*

**Pull request merged**
