### PR TITLE
DiscretizedTransform : Compare fractional part of translations

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/351)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/351#-:-KvkoXTWiCc52hu3adt2:bnfp4nl)*

**Comment by crazyjul** [comment]
I already said it, but my advice seems to have less impact :-)

You should compute a hash and test it instead of testing each value

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/351#-:-KvkvyWs-kGSaHtVDPIk:bf870cb)*

**Comment by gogoprog** [comment]
Hey I did it in the MorphShape cache ;)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/351#-:-Kvl0FxnNfhppij-mwC7:b-cpv537)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 343 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/351#-KvlC91PKpI7LGZ_5KUw:-KvlC91PKpI7LGZ_5KUx:b-mkd4lj) ([raw file](https://github.com/fishingcactus/openfl/blob/9cba56e5d10d16565a5ad0d7770defeb6961737a/format/swf/lite/symbols/ShapeSymbol.hx#L343)):*
> ```Haxe
> 			&& c == other.c
> 			&& tx == other.tx
> 			&& ty == other.ty;
> ```

I think we translate more often than rotate so better check tx/ty before c/d
OR
go for the hash suggestion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/351)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/351)*

**Pull request merged**
