### PR TITLE
Small optim on Float32Array creation in VertexBuffer3D

### PR DESCRIPTION
**Pull request by gogoprog**
This will let the browser do the array-typedarray conversion

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/271)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/271#-:-KmzfulSv8jYgw8_8jXP:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display3D/VertexBuffer3D.hx, line 88 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/271#-Kn8URfA_0ourGUVzLpY:-Kn8URfA_0ourGUVzLpZ:boked8n) ([raw file](https://github.com/fishingcactus/openfl/blob/080d1a6bca0de4c5b1c42fa3818423ea1ee15eba/openfl/display3D/VertexBuffer3D.hx#L88)):*
> if(startVertex == 0 && length == data.length) {
> 			float32Array = untyped __js__("new Float32Array(data.data)");
> 		} else {
Indentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/271)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/271)*

**Comment by gogoprog** [comment]
*[openfl/display3D/VertexBuffer3D.hx, line 88 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/271#-Kn8URfA_0ourGUVzLpY:-KnE-ffol01lfFL5oClE:b-old9op) ([raw file](https://github.com/fishingcactus/openfl/blob/080d1a6bca0de4c5b1c42fa3818423ea1ee15eba/openfl/display3D/VertexBuffer3D.hx#L88)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> if(startVertex == 0 && length == data.length) {
> 			float32Array = untyped __js__("new Float32Array(data.data)");
> 		} else {
Indentation
</blockquote></details>

Looks fine to me?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/271)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display3D/VertexBuffer3D.hx, line 88 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/271#-Kn8URfA_0ourGUVzLpY:-KnE25eSW1TPahhxhKrL:b-7cliw8) ([raw file](https://github.com/fishingcactus/openfl/blob/080d1a6bca0de4c5b1c42fa3818423ea1ee15eba/openfl/display3D/VertexBuffer3D.hx#L88)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Looks fine to me?
</blockquote></details>

strange.. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/271)*

**Pull request merged**
