### PR TITLE
Fix/stage3D resize

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/283)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DirectRenderer.hx, line 47 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/283#-KoM7jrk0WIfhTxcaT0B:-KoM7jrlySyJmQPAeRGY:b-jd3nvp) ([raw file](https://github.com/fishingcactus/openfl/blob/60888f330a297e8b4d9219b165776ed62dba95d9/openfl/display/DirectRenderer.hx#L47)):*
> ```Haxe
> 	
> 	public override function set_width(value:Float) {
> 		return __width = Std.int(value);
> ```

Shouldn't this call super.width = value?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/283)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DirectRenderer.hx, line 47 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/283#-KoM7jrk0WIfhTxcaT0B:-KoM8oDJ8Img1DMrzadu:bn1ndk6) ([raw file](https://github.com/fishingcactus/openfl/blob/60888f330a297e8b4d9219b165776ed62dba95d9/openfl/display/DirectRenderer.hx#L47)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Shouldn't this call super.width = value?
</blockquote></details>

No. The reason we have this override is because this object is only a DisplayObject so that it will call the __renderGL function. 
It has no bounds.
If you call `super.width = value`, the value will be stored in terms of scale. To compute it we divide by the bounds. This results in `Infinity` scale and `Nan` width. That's the reason for this override

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/283)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/283#-:-KoMAY4CMgT_z9tUppWi:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/283)*

**Pull request merged**
