### PR TITLE
Optimized hittest and flattened children stack update using branch depth info

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/292)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/292)*

**Comment by gogoprog** [comment]
Reviewed 3 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[openfl/display/DisplayObject.hx, line 129 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/292#-KpJy-DeYylnrv9zhRVN:-KpJy-DeYylnrv9zhRVO:b-n3sw9p) ([raw file](https://github.com/fishingcactus/openfl/blob/b3e2caeaea1c6c5837ec43c40c6aa8083118559b/openfl/display/DisplayObject.hx#L129)):*
> ```Haxe
> 	private var __mouseListenerCount:Int = 0;
> 	private var __recursiveMouseListenerCount:Int = 0;
> 	static private var __mouseListenerBranchDepthStack:haxe.ds.GenericStack<Int> = new haxe.ds.GenericStack<Int>();
> ```

could be an UnshrinkableArray

---

*[openfl/display/Stage.hx, line 688 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/292#-KpJxpP1utZ3vfLpeGLe:-KpJxpP1utZ3vfLpeGLf:b-av8hdb) ([raw file](https://github.com/fishingcactus/openfl/blob/b3e2caeaea1c6c5837ec43c40c6aa8083118559b/openfl/display/Stage.hx#L688)):*
> ```Haxe
> 
> 	private function __concatDepthFirstChildren(array:UnshrinkableArray<DisplayObject>, head:DisplayObject) {
> 		var stack:haxe.ds.GenericStack<Int> = new haxe.ds.GenericStack<Int>();
> ```

could be a static UnshrinkableArray to avoid allocs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/292)*

**Comment by rams3s** [comment]
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 129 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/292#-KpJy-DeYylnrv9zhRVN:-KpK4cIDQBgQ9xCURZ-8:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/b3e2caeaea1c6c5837ec43c40c6aa8083118559b/openfl/display/DisplayObject.hx#L129)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

could be an UnshrinkableArray
</blockquote></details>

Done.

---

*[openfl/display/Stage.hx, line 688 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/292#-KpJxpP1utZ3vfLpeGLe:-KpK4dFhc-EjYs_6Z-RI:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/b3e2caeaea1c6c5837ec43c40c6aa8083118559b/openfl/display/Stage.hx#L688)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

could be a static UnshrinkableArray to avoid allocs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/292)*

**Comment by gogoprog** [comment]
Reviewed 4 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/292)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/292#-:-KpK7Sv_nUdSU1twCUcw:bnfp4nl)*

**Pull request merged**
