### PR TITLE
Feature/hxbit serialization

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/280)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 39 of 48 files at r1, 13 of 14 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-:-KoCXl_oITmacIsbv-KD:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 34 of 48 files at r1, 10 of 14 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[format/swf/data/etc/Edge.hx, line 18 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoD1G8CoHDJAXZSNl3t:-KoD1G8CoHDJAXZSNl3u:blzwwp) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/format/swf/data/etc/Edge.hx#L18)):*
>    public function reverseWithNewFillStyle(newFillStyleIdx:Int):Edge {
> 		return new Edge();
> 	}

as this class replaces an interface and should be abstract (in a C++ sense), maybe could we add a safety throw in here?

---

*[openfl/_internal/renderer/DrawCommandReader.hx, line 58 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoD3FSB747CCxF3IUlo:-KoD3FSB747CCxF3IUlp:b-hk6krz) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/openfl/_internal/renderer/DrawCommandReader.hx#L58)):*
> //js.Browser.console.assert(viPos == buffer.vi.length);
> //js.Browser.console.assert(vfPos == buffer.vf.length);

commented code?

---

*[openfl/utils/Float32ArrayContainer.hx, line 30 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoDTJLRqbd9pk0_hNQA:-KoDTJLRqbd9pk0_hNQB:b-kjbrrc) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/openfl/utils/Float32ArrayContainer.hx#L30)):*
>         var length = ctx.getInt();
>         var tempArray = new Array<Float>();
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         for(i in 0...length)
>         {
>             tempArray.push(ctx.getFloat());
>         }
</details>
>  
>         value = new Float32Array(tempArray);

any idea how we could make this more efficient? even if for JS only?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280)*

**Comment by rams3s** [comment]
Reviewed 5 of 48 files at r1, 3 of 14 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/data/etc/Edge.hx, line 18 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoD1G8CoHDJAXZSNl3t:-KoGZJmJ3mj-2GQ1WdqI:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/format/swf/data/etc/Edge.hx#L18)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

>    public function reverseWithNewFillStyle(newFillStyleIdx:Int):Edge {
> 		return new Edge();
> 	}

as this class replaces an interface and should be abstract (in a C++ sense), maybe could we add a safety throw in here?
</blockquote></details>

Done.

---

*[openfl/_internal/renderer/DrawCommandReader.hx, line 58 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoD3FSB747CCxF3IUlo:-KoGZeiaCKGQjUOhDuqL:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/openfl/_internal/renderer/DrawCommandReader.hx#L58)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> //js.Browser.console.assert(viPos == buffer.vi.length);
> //js.Browser.console.assert(vfPos == buffer.vf.length);

commented code?
</blockquote></details>

Done.

---

*[openfl/utils/Float32ArrayContainer.hx, line 30 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/280#-KoDTJLRqbd9pk0_hNQA:-KoGkbJmsMHF9PrJXHkL:b-vwj2tg) ([raw file](https://github.com/fishingcactus/openfl/blob/3616791e5f47ba13bb76270e12eef950ed2127f7/openfl/utils/Float32ArrayContainer.hx#L30)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

>         var length = ctx.getInt();
>         var tempArray = new Array<Float>();
>  
>         for(i in 0...length)
>         {
>             tempArray.push(ctx.getFloat());
>         }
>  
>         value = new Float32Array(tempArray);

any idea how we could make this more efficient? even if for JS only?
</blockquote></details>

Done. Using bytes serialization now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280)*

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/280)*

**Pull request merged**
