### PR TITLE
Preprocess simplesprites

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/347)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 155 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/347#-KvanHadfY-iZgjqmGnW:-KvanHadfY-iZgjqmGnX:b-pk0yoq) ([raw file](https://github.com/fishingcactus/openfl/blob/8722e48ad68af83ea99901543e701eb5e32b40ba/openfl/utils/MovieClipPreprocessor.hx#L155)):*
> ```Haxe
>             var bitmapData = Assets.getBitmapData(cast(swf.symbols.get(entry.symbol.bitmapID),format.swf.lite.symbols.BitmapSymbol).path);
> 
>             if(@:privateAccess bitmapData != null) {
> ```

no need for private access ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/347)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 155 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/347#-KvanHadfY-iZgjqmGnW:-KvapKIgGbkFrr5zxP2t:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/8722e48ad68af83ea99901543e701eb5e32b40ba/openfl/utils/MovieClipPreprocessor.hx#L155)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

no need for private access ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/347)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/347)*

**Comment by gogoprog** [comment]
*[openfl/utils/MovieClipPreprocessor.hx, line 206 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/347#-Kvg-BXh9GnVb1czUMiF:-Kvg-BXh9GnVb1czUMiG:b-1quj4q) ([raw file](https://github.com/fishingcactus/openfl/blob/fe6a33417248bfb69d9f3b48c067e0270d7e3a66/openfl/utils/MovieClipPreprocessor.hx#L206)):*
> ```Haxe
>                         }
>                     } else if (Std.is(symbol, SimpleSpriteSymbol)) {
>                         if (frameObject.symbol != depthSymbolMap[frameObject.depth] || !renderTransform.equals (depthRenderTransformMap[frameObject.depth])) {
> ```

The check on the renderTransform is useless as we just create gl textures using simple sprite sources

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/347)*

**Pull request merged**
