### PR TITLE
swflite spritesheet generation

### PR DESCRIPTION
**Pull request by onMouseUp**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[openfl/display/BitmapData.hx, line 1336 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCS_PnD0ShVtDWx577C:-LCS_PnD0ShVtDWx577D:b-l1cfze) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/openfl/display/BitmapData.hx#L1336)):*
> ```Haxe
> 	}
> 
> 	public static function isSpritesheetImage(id:Int):Bool {
> ```

duplicate function from SimpleSprite. factorize please

---

*[openfl/display/BitmapData.hx, line 1340 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCS_Usa8DIlnGSl5Kl0:-LCS_Usa8DIlnGSl5Kl1:b-ugoswz) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/openfl/display/BitmapData.hx#L1340)):*
> ```Haxe
> 	}
> 
> 	public static function getFromSritesheet(id:Int, path:String):BitmapData {
> ```

Typo `getFromSpritesheet`

---

*[tools/Tools.hx, line 631 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCSbnOJ6DIVzvBZQLIP:-LCSbnOJ6DIVzvBZQLIQ:benova0) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/tools/Tools.hx#L631)):*
> ```Haxe
> 	}
> 
> 	private static function markForSpritesheet(asset:Asset, excludeList:Array<Int>):Void {
> ```

tryMarkForSpritesheet would be a clearer and more correct name

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by rams3s** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/lite/SimpleSprite.hx, line 29 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCTDjYQBZfODJjZDUh4:-LCTDjYQBZfODJjZDUh5:b-k101ub) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/format/swf/lite/SimpleSprite.hx#L29)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (isSpritesheetImage(symbol.bitmapID)) {
>             // for reducing draw calls usePerFrameBitmapData should be set to false
>             var frameName:String = Std.string(symbol.bitmapID);
>             var displayObject:DisplayObject = spritesheet.getDisplayObjectByFrameName(frameName);
>             addDisplayObject(displayObject, symbol);
>         } else {
> ```
</details>


is this first if necessary? Looks like Assets.getBitmapDataFromSymbol() will already provide us with the bitmap data from the spritesheet.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by onMouseUp** [comment]
*[format/swf/lite/SimpleSprite.hx, line 29 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCTDjYQBZfODJjZDUh4:-LCXjpIV0aYTtuqpa8yP:b81f6lm) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/format/swf/lite/SimpleSprite.hx#L29)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> ```
>         if (isSpritesheetImage(symbol.bitmapID)) {
>             // for reducing draw calls usePerFrameBitmapData should be set to false
>             var frameName:String = Std.string(symbol.bitmapID);
>             var displayObject:DisplayObject = spritesheet.getDisplayObjectByFrameName(frameName);
>             addDisplayObject(displayObject, symbol);
>         } else {
> ```

is this first if necessary? Looks like Assets.getBitmapDataFromSymbol() will already provide us with the bitmap data from the spritesheet.
</blockquote></details>

SimpleSprite is using a different spritesheet-instance than BitmapData. It's the same texture but uses "usePerFrameBitmapData = false". So with SimpleSprite you can reduce some draw calls. For BitmapData we need "usePerFrameBitmapData = true".  

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by onMouseUp** [comment]
*[openfl/display/BitmapData.hx, line 1336 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCS_PnD0ShVtDWx577C:-LCXovf97UqaqKSuU-2j:b-eucnlq) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/openfl/display/BitmapData.hx#L1336)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

duplicate function from SimpleSprite. factorize please
</blockquote></details>

SimpleSprite has a different spritesheet injection than BitmapData! 

SimpleSprite --> "usePerFrameBitmapData = false"  
BitmapData --> "usePerFrameBitmapData = true"

The idea is to reduce some draw calls in SimpleSprite by using the entire texture instead of using BitmapData of each frame 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/BitmapData.hx, line 1336 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCS_PnD0ShVtDWx577C:-LCY5GUi6jauHcw5Ge2J:b32w0x) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/openfl/display/BitmapData.hx#L1336)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

SimpleSprite has a different spritesheet injection than BitmapData! 

SimpleSprite --> "usePerFrameBitmapData = false"  
BitmapData --> "usePerFrameBitmapData = true"

The idea is to reduce some draw calls in SimpleSprite by using the entire texture instead of using BitmapData of each frame 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/SimpleSprite.hx, line 29 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCTDjYQBZfODJjZDUh4:-LCYF0MG3BqcU6cpCHyz:bb74pu7) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/format/swf/lite/SimpleSprite.hx#L29)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

SimpleSprite is using a different spritesheet-instance than BitmapData. It's the same texture but uses "usePerFrameBitmapData = false". So with SimpleSprite you can reduce some draw calls. For BitmapData we need "usePerFrameBitmapData = true".  
</blockquote></details>

Thx.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by onMouseUp** [comment]
Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/BitmapData.hx, line 1340 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCS_Usa8DIlnGSl5Kl0:-LCdiHTA8kDl7ukmZ_fg:b-7ql1td) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/openfl/display/BitmapData.hx#L1340)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Typo `getFromSpritesheet`
</blockquote></details>

fixed

---

*[tools/Tools.hx, line 631 at r1](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCSbnOJ6DIVzvBZQLIP:-LCdiJlkDQSzgykpva3A:b-7ql1td) ([raw file](https://github.com/fishingcactus/openfl/blob/86f0fea57dc2a79d5ada836778fb7143fea9e2ee/tools/Tools.hx#L631)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

tryMarkForSpritesheet would be a clearer and more correct name
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by NuclearCookie** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[templates/haxe/ApplicationMain.hx, line 3 at r3](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCh3i7m7a5YeKdvqXnx:-LCh3i7m7a5YeKdvqXny:bpfagmj) ([raw file](https://github.com/fishingcactus/openfl/blob/16ff71a6a1a187f477a7ec274fb28848e84ac505/templates/haxe/ApplicationMain.hx#L3)):*
> ```Haxe
> #if !macro
> 
> import spritesheet.wrapper.SpritesheetConfig;
> ```

openfl should be able to compile without spritesheet package. 
Does it work to include this code in a `::if (swfSpritesheet.enabled):: section?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by onMouseUp** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[templates/haxe/ApplicationMain.hx, line 3 at r3](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCh3i7m7a5YeKdvqXnx:-LChMXXuEZMjdevcqDEE:bwakoef) ([raw file](https://github.com/fishingcactus/openfl/blob/16ff71a6a1a187f477a7ec274fb28848e84ac505/templates/haxe/ApplicationMain.hx#L3)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

openfl should be able to compile without spritesheet package. 
Does it work to include this code in a `::if (swfSpritesheet.enabled):: section?
</blockquote></details>

now if swfspritesheet is disabled all code fragments related to spritesheet generation will be ignored in template. Tested successfully in ApplicationMain of classic-framework 

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by rams3s** [comment]
Reviewed 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Comment by onMouseUp** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[templates/haxe/ApplicationMain.hx, line 3 at r3](https://reviewable.io/reviews/fishingcactus/openfl/418#-LCh3i7m7a5YeKdvqXnx:-LChRRgCAyM8ZShBmL5g:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/16ff71a6a1a187f477a7ec274fb28848e84ac505/templates/haxe/ApplicationMain.hx#L3)):*
<details><summary><i>Previously, onMouseUp (onMouseUp) wrote…</i></summary><blockquote>

now if swfspritesheet is disabled all code fragments related to spritesheet generation will be ignored in template. Tested successfully in ApplicationMain of classic-framework 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/418)*

**Pull request merged**
