### PR TITLE
Cleaned up added_to- and removed_from stage code. Better resources cl…

### PR DESCRIPTION
**Pull request by NuclearCookie**
…eanup.

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/269)

### CODE REVIEW

**Comment by gogoprog** [comment]
*[openfl/display/DisplayObject.hx, line 790 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmetnN6UOLqf5TRJjKt:-KmetnN6UOLqf5TRJjKu:b-v9ypub) ([raw file](https://github.com/fishingcactus/openfl/blob/ce08c582a8c0a8439daa958ca934a7619f607563/openfl/display/DisplayObject.hx#L790)):*
> if (this.stage.focus == this) {
>  
> 					this.stage.focus = null;

Is is intended to remove these lines?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by gogoprog** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by rams3s** [comment]
I find it confusing to know which of  __setStageReference  and set_stage should be called.
Can we try to provide a clear single entry point?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 790 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmetnN6UOLqf5TRJjKt:-Kmf2VstMcTWz4zHObWh:b32v57) ([raw file](https://github.com/fishingcactus/openfl/blob/ce08c582a8c0a8439daa958ca934a7619f607563/openfl/display/DisplayObject.hx#L790)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

> if (this.stage.focus == this) {
>  
> 					this.stage.focus = null;

Is is intended to remove these lines?
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-:-Kmf497YDEK8mzyFHSBr:b-dylpba)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 790 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmetnN6UOLqf5TRJjKt:-KmfGhcrmhARGpmnQtAp:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/ce08c582a8c0a8439daa958ca934a7619f607563/openfl/display/DisplayObject.hx#L790)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 774 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmkHfzWnVLWjXv-73Tb:-KmkHfzXZ8uDKAQ46Wwy:b-4j7f60) ([raw file](https://github.com/fishingcactus/openfl/blob/8804178688ce1df63ae5d4ab808896c466f196b9/openfl/display/DisplayObject.hx#L774)):*
> ```Haxe
> 	private function __fireRemovedFromStageEvent() {
> 		#if compliant_stage_events
> 			var stack = __getDisplayStack( this );
> ```

This is now computed twice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by gogoprog** [comment]
*[openfl/display/DisplayObject.hx, line 774 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmkHfzWnVLWjXv-73Tb:-KmkPYnut1BRNUrn-rAj:b2ngthb) ([raw file](https://github.com/fishingcactus/openfl/blob/8804178688ce1df63ae5d4ab808896c466f196b9/openfl/display/DisplayObject.hx#L774)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

This is now computed twice
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by NuclearCookie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 774 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/269#-KmkHfzWnVLWjXv-73Tb:-Kn8hWJVS_dDSIO2fvYJ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/8804178688ce1df63ae5d4ab808896c466f196b9/openfl/display/DisplayObject.hx#L774)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/269)*

**Pull request merged**
