### PR TITLE
Feature/simplify shape commands

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/220)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by gogoprog** [comment]
Reviewed 9 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by crazyjul** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 9 files at r1, 8 of 9 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 517 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4_FnJH7u3blGGvpgb:-Ki4_FnJH7u3blGGvpgc:b6armk4) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L517)):*
> ```Haxe
> 			var command = commands[i];
> 
> 			function simplifyEmptyLineStyle ():Bool {
> ```

Re-creating those functions on each iteration is not cool. You can move them out quite easily

---

*[format/swf/exporters/SWFLiteExporter.hx, line 552 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4a41d8mWGE6vBkF06:-Ki4a41e3jHTmRMztZBE:b-nq3nsb) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L552)):*
> ```Haxe
> 						}
> 
> 						if (matrix.b != 0 || matrix.c != 0) {
> ```

I thought you supported rotation now?

---

*[format/swf/exporters/SWFLiteExporter.hx, line 556 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4aUnuKPeV-V9_Ko-i:-Ki4aUnuKPeV-V9_Ko-j:bgjdhvf) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L556)):*
> ```Haxe
> 						}
> 
> 						if (i+6 >= commands.length) {
> ```

You may miss some cases because of this. If there is no MoveTo command, there will only be 5 commands used. 

---

*[format/swf/exporters/SWFLiteExporter.hx, line 561 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4aqa3dyNXf39XIZKk:-Ki4aqa3dyNXf39XIZKl:b-g1erew) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L561)):*
> ```Haxe
> 
> 						var rectStartIndex:Int;
> 						var startPoint = new Point ();
> ```

We have a pool for points. This is initialization phase so it's perfect to populate the pool at this moment.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 605 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4bs1doMgEG99jC1-D:-Ki4bs1doMgEG99jC1-E:b2ngwr1) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L605)):*
> ```Haxe
> 						}
> 
> 						centerPoint.x = centerPoint.x / 4;
> ```

/= 

---

*[openfl/_internal/renderer/DrawCommandReader.hx, line 47 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4dbrfDR5TMV2cLerA:-Ki4dbrfDR5TMV2cLerB:bhau3ea) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/openfl/_internal/renderer/DrawCommandReader.hx#L47)):*
> ```Haxe
> 	
> 	
> 	private function advance ():Void {
> ```

any reason for removing the inline?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 517 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4_FnJH7u3blGGvpgb:-Ki4fNL6qr32_wL5Cr7O:b-rc3mf3) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L517)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Re-creating those functions on each iteration is not cool. You can move them out quite easily
</blockquote></details>

this is in the exporter, compiled to neko
Timing is also not important here

---

*[format/swf/exporters/SWFLiteExporter.hx, line 561 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4aqa3dyNXf39XIZKk:-Ki4ff0QYb3_yQHEIwD5:b-jp0frh) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L561)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

We have a pool for points. This is initialization phase so it's perfect to populate the pool at this moment.
</blockquote></details>

again, in the exporter, it's not worth the effort

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 552 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4a41d8mWGE6vBkF06:-Ki4uZtaQXm1XIzRZlvP:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L552)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

I thought you supported rotation now?
</blockquote></details>

Done.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 556 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4aUnuKPeV-V9_Ko-i:-Ki4uh3_PCOCnA9y6f-N:b-wxlp63) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L556)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

You may miss some cases because of this. If there is no MoveTo command, there will only be 5 commands used. 
</blockquote></details>

yep, that's just early rejection for sub shapes with more commands than needed for a simple quad

---

*[format/swf/exporters/SWFLiteExporter.hx, line 605 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4bs1doMgEG99jC1-D:-Ki4tcurFokUTKVzLOuy:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L605)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

/= 
</blockquote></details>

Done.

---

*[openfl/_internal/renderer/DrawCommandReader.hx, line 47 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4dbrfDR5TMV2cLerA:-Ki4pPGI05s04zpcmw-J:ba3yz0v) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/openfl/_internal/renderer/DrawCommandReader.hx#L47)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

any reason for removing the inline?
</blockquote></details>

pretty long function (+100 lines with spacing) inlined quite a few times (almost 20 times)...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 556 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki4aUnuKPeV-V9_Ko-i:-Ki5CqI4gvSkTAh0iitD:b-8hacrs) ([raw file](https://github.com/fishingcactus/openfl/blob/f65d3573c7b6e413835fa791f63ce75abd58516c/format/swf/exporters/SWFLiteExporter.hx#L556)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

yep, that's just early rejection for sub shapes with more commands than needed for a simple quad
</blockquote></details>

Will keep it like this for now as it seems we always have a MoveTo before LineTo. I will now throw an exception if it's not the case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-:-Ki5FE60H-TzOkAUFjgs:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by crazyjul** [comment]
I don't think that a RotatedRectangle is a parallelogram, this is means that the matrix is skewed.

Are you sure this is representable by a drawImage?

**Comment by gogoprog** [comment]
Reviewed 6 of 9 files at r2, 1 of 2 files at r3.
Review status: 9 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 1130 at r4](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki9OM6XrPbxOgw66ecT:-Ki9OM6XrPbxOgw66ecU:b5b1zaa) ([raw file](https://github.com/fishingcactus/openfl/blob/6c5467f5523431b5b412a2d594d3b95a45b452cb/format/swf/exporters/SWFLiteExporter.hx#L1130)):*
> ```Haxe
> }
> 
> class Parallellogram {
> ```

Typo : Parallelogram

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Comment by rams3s** [comment]
Yes, it works fine. Matrix with skewing was tested and added to graphic tests project.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-:-Ki9RRoRK1LHv8Bi3i8q:b-e19890)*

**Comment by NuclearCookie** [comment]
*[format/swf/exporters/SWFLiteExporter.hx, line 1130 at r4](https://reviewable.io:443/reviews/fishingcactus/openfl/220#-Ki9OM6XrPbxOgw66ecT:-Ki9TMkcQ3kwaQGTWy9s:b-c4gyln) ([raw file](https://github.com/fishingcactus/openfl/blob/6c5467f5523431b5b412a2d594d3b95a45b452cb/format/swf/exporters/SWFLiteExporter.hx#L1130)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Typo : Parallelogram
</blockquote></details>

Damn the dutch man who wrote it with double L >.<

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/220)*

**Pull request merged**
