### PR TITLE
Fixes for text rendering and Dynamic Text Fields

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/206)

### CODE REVIEW

**Comment by rams3s** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/canvas/CanvasTextField.hx, line 251 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqtcmMj7CPgVDAU5CW:-KfqtcmMj7CPgVDAU5CX:b2om6da) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/renderer/canvas/CanvasTextField.hx#L251)):*
> } else if (!((group.startIndex < textField.__caretIndex && group.startIndex < textField.__selectionIndex && group.endIndex < textField.__caretIndex && group.endIndex < textField.__selectionIndex)
> 									|| (group.startIndex > textField.__caretIndex && group.startIndex > textField.__selectionIndex && group.endIndex > textField.__caretIndex && group.endIndex > textField.__selectionIndex))) {
>

that's hard to read ;p

Considering that group.startIndex should always be < than group.endIndex and using min/max(caretIndex, selectionIndex), I think this could be substantially simplified

---

*[openfl/_internal/text/TextEngine.hx, line 670 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvPUse0ToHmxuNEeA:-KfqvPUse0ToHmxuNEeB:b-opdo8i) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L670)):*
> for(i in 0...64) {
> 						width += __context.measureText (char).width;
> 					}
> 					width /= 64;
> 					advances.push(width);

not sure this helps with accuracy... shouldn't this code measure the length of the concatenated string?

---

*[openfl/_internal/text/TextEngine.hx, line 764 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvbgxYZdKRRF6lG9S:-KfqvbgxYZdKRRF6lG9T:b-ha1gbj) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L764)):*
> ```Haxe
> 			layoutGroup.endIndex = endIndex;
> 			layoutGroup.width = widthValue;
> 			layoutGroup.advances = advances.splice(0, advances.length);
> ```

Not sure splice is necessary here. If not, better remove it because splicing the whole array could result in unnecessary allocations.

---

*[openfl/text/TextField.hx, line 169 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kfqymr4ARAnguHzD0wA:-Kfqymr4ARAnguHzD0wB:b-lbax8o) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L169)):*
> charIndex > group.endIndex

As group.endIndex is not inclusive, shouldn't it be charIndex >= group.endIndex?

---

*[openfl/text/TextField.hx, line 1773 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqtL88kBUsMm2f-GxT:-KfqtL88kBUsMm2f-GxU:blfkq9x) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L1773)):*
> ```Haxe
> 		__dirty = true;
> 
> 		// mouse moved to much. don't check for doubleclick
> ```

typo ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by crazyjul** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[format/swf/lite/DynamicTextField.hx, line 123 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfrERLQIbvNEi6H_0gT:-KfrERLQIbvNEi6H_0gU:b-71itpx) ([raw file](https://github.com/fishingcactus/openfl/blob/f24e1e2d209d6d6a8dc32fb165d939afc6004f28/format/swf/lite/DynamicTextField.hx#L123)):*
> ```Haxe
> 		if (symbol.text != null) {
> 
> 			#if !flash
> ```

The test was !flash, so always true, why keep the false?

---

*[openfl/_internal/text/TextEngine.hx, line 670 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvPUse0ToHmxuNEeA:-KfrEpueWmsMeYVGFRGd:b81flyf) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L670)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> for(i in 0...64) {
> 						width += __context.measureText (char).width;
> 					}
> 					width /= 64;
> 					advances.push(width);

not sure this helps with accuracy... shouldn't this code measure the length of the concatenated string?
</blockquote></details>

I agree, it doesn't change anything, measureText will always return the same value.

---

*[openfl/text/TextField.hx, line 1774 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfrFjzbqZCwRl9DZvSN:-KfrFjzbqZCwRl9DZvSO:bz5leaw) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L1774)):*
> ```Haxe
> 
> 		// mouse moved to much. don't check for doubleclick
> 		if( __firstDownPos != null && (Math.abs(__firstDownPos.x - mouseX) > 10 || Math.abs(__firstDownPos.y - mouseY) > 10)) {
> ```

Review to intern apply to you ;-), no constant in code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by NuclearCookie** [comment]
Review status: 2 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[format/swf/lite/DynamicTextField.hx, line 123 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfrERLQIbvNEi6H_0gT:-Kfu5YXPjzc2CX_ZXUXo:bexa0cp) ([raw file](https://github.com/fishingcactus/openfl/blob/f24e1e2d209d6d6a8dc32fb165d939afc6004f28/format/swf/lite/DynamicTextField.hx#L123)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

The test was !flash, so always true, why keep the false?
</blockquote></details>

I don't see what you mean

---

*[openfl/_internal/renderer/canvas/CanvasTextField.hx, line 251 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqtcmMj7CPgVDAU5CW:-Kfu6gSfw-gD9suQ0Pgf:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/renderer/canvas/CanvasTextField.hx#L251)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> } else if (!((group.startIndex < textField.__caretIndex && group.startIndex < textField.__selectionIndex && group.endIndex < textField.__caretIndex && group.endIndex < textField.__selectionIndex)
> 									|| (group.startIndex > textField.__caretIndex && group.startIndex > textField.__selectionIndex && group.endIndex > textField.__caretIndex && group.endIndex > textField.__selectionIndex))) {
>

that's hard to read ;p

Considering that group.startIndex should always be < than group.endIndex and using min/max(caretIndex, selectionIndex), I think this could be substantially simplified
</blockquote></details>

Done.

---

*[openfl/_internal/text/TextEngine.hx, line 670 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvPUse0ToHmxuNEeA:-Kfu7ARK-q8FOtTrulnF:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L670)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I agree, it doesn't change anything, measureText will always return the same value.
</blockquote></details>

Done.

---

*[openfl/_internal/text/TextEngine.hx, line 764 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvbgxYZdKRRF6lG9S:-Kfu7Ds4NNkpu-IYz26C:b-sgyvrq) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L764)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

Not sure splice is necessary here. If not, better remove it because splicing the whole array could result in unnecessary allocations.
</blockquote></details>

It's done to create a copy of the advances.  (and empty the table at the same time.) Each layout group should contain its own advance table

---

*[openfl/text/TextField.hx, line 169 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kfqymr4ARAnguHzD0wA:-Kfu7rZ9kRYciI26lzps:bxqi28h) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L169)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> charIndex > group.endIndex

As group.endIndex is not inclusive, shouldn't it be charIndex >= group.endIndex?
</blockquote></details>

No, not in this case. Because what we want here is the posibility to place the cursor AFTER the last element. 

---

*[openfl/text/TextField.hx, line 1773 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqtL88kBUsMm2f-GxT:-Kfu84eiyjlRkjw1vYIx:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L1773)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

typo ;)
</blockquote></details>

Done.

---

*[openfl/text/TextField.hx, line 1774 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfrFjzbqZCwRl9DZvSN:-Kfu8J67FlOITxEyKw2S:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/text/TextField.hx#L1774)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Review to intern apply to you ;-), no constant in code
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/_internal/text/TextEngine.hx, line 764 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvbgxYZdKRRF6lG9S:-KfvBVlbmWp03hzxMqD5:b-avgz1a) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L764)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

It's done to create a copy of the advances.  (and empty the table at the same time.) Each layout group should contain its own advance table
</blockquote></details>

As discussed, transferring ownership should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by NuclearCookie** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/_internal/text/TextEngine.hx, line 764 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-KfqvbgxYZdKRRF6lG9S:-KfzJARlnEqv4UyPpaFU:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/175c1ab1fa3602fbb14669dbb623101d90051d62/openfl/_internal/text/TextEngine.hx#L764)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

As discussed, transferring ownership should be enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by crazyjul** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[openfl/text/TextField.hx, line 129 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-vpTxV3IMidG18vNR:-Kg-vpTy9d6-Tly1OIj-:b-134qt7) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L129)):*
> if ( maxChars == 0 || __textEngine.text.length < maxChars ) {
> 			__textEngine.text += text;

this allows for text longer than maxChars... Is this intended? Or trimmed later on?

---

*[openfl/text/TextField.hx, line 497 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-z27v4MnjPe8JR5ue:-Kg-z27v4MnjPe8JR5uf:b-1l7lf2) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L497)):*
> if (lengthOfTextToReplace <= 0) {
> 				return "";
> 			} else {

can this ever happen? there is already a test for beginIndex < endIndex above and __textEngine.text.length should be <= maxChars, shouldn't it?

---

*[openfl/text/TextField.hx, line 499 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-yHmNPITbd9fQKDzV:-Kg-yHmNPITbd9fQKDzW:b-f5uq22) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L499)):*
> 	newText = newText.substring(0, lengthOfTextToReplace);

I think that String.substr would be semantically more correct (i.e. second argument is a length and not an index)

---

*[openfl/text/TextField.hx, line 1269 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-ynNebV_xJxyTeQLb:-Kg-ynNebV_xJxyTeQLc:b-skkrdc) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L1269)):*
> ```Haxe
> 
> 						}
> 						// :TODO: support alignment
> ```

can comment be removed now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/text/TextField.hx, line 129 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-vpTxV3IMidG18vNR:-KgDawX7737PnhfCuZzU:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L129)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> if ( maxChars == 0 || __textEngine.text.length < maxChars ) {
> 			__textEngine.text += text;

this allows for text longer than maxChars... Is this intended? Or trimmed later on?
</blockquote></details>

Done.

---

*[openfl/text/TextField.hx, line 497 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-z27v4MnjPe8JR5ue:-KgD_7dPPl32_q6l-eZi:b-epn6x) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L497)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> if (lengthOfTextToReplace <= 0) {
> 				return "";
> 			} else {

can this ever happen? there is already a test for beginIndex < endIndex above and __textEngine.text.length should be <= maxChars, shouldn't it?
</blockquote></details>

Ideally this could indeed not happen. But I'm not so sure that we covered all cases. I'd prefer to keep this here.

---

*[openfl/text/TextField.hx, line 499 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-yHmNPITbd9fQKDzV:-KgDayFKfdfQOD2IX5CN:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L499)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> 	newText = newText.substring(0, lengthOfTextToReplace);

I think that String.substr would be semantically more correct (i.e. second argument is a length and not an index)
</blockquote></details>

Done.

---

*[openfl/text/TextField.hx, line 1269 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/206#-Kg-ynNebV_xJxyTeQLb:-KgDaywp5Lkec3c48krS:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/93cf274c73d497fa4446d507c5dd097b3a2f42c6/openfl/text/TextField.hx#L1269)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

can comment be removed now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r4.
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/206)*

**Pull request merged**
