### PR TITLE
Fixed compilation with compliant stage events

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/276)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/DisplayObjectContainer.hx, line 678 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnDtc_Mvp6CG83z_ts8:-KnDtc_NL-5dbM7Qf_Lc:b7kl41v) ([raw file](https://github.com/fishingcactus/openfl/blob/77deb76cb56eb64118ea0d083b1ca7f640729f33/openfl/display/DisplayObjectContainer.hx#L678)):*
> #if compliant_stage_events
> 					if ( stack[stack.length] == this ) {
> 						stack.push(child);
> 					} else {
> 						stack[stack.length] = child;
> 					}
> 				#end

the test + push could be done out of the loop

---

*[openfl/display/DisplayObjectContainer.hx, line 707 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnDtyyJaZqtyYzQ1F_D:-KnDtyyJaZqtyYzQ1F_E:b-c253yd) ([raw file](https://github.com/fishingcactus/openfl/blob/77deb76cb56eb64118ea0d083b1ca7f640729f33/openfl/display/DisplayObjectContainer.hx#L707)):*
> #if compliant_stage_events
> 					if ( stack[stack.length] == this ) {
> 						stack.push(child);
> 					} else {
> 						stack[stack.length] = child;
> 					}
> 				#end
same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/DisplayObjectContainer.hx, line 678 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnDtc_Mvp6CG83z_ts8:-KnE1Hhh5lFuwcUyEXDB:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/77deb76cb56eb64118ea0d083b1ca7f640729f33/openfl/display/DisplayObjectContainer.hx#L678)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> #if compliant_stage_events
> 					if ( stack[stack.length] == this ) {
> 						stack.push(child);
> 					} else {
> 						stack[stack.length] = child;
> 					}
> 				#end

the test + push could be done out of the loop
</blockquote></details>

Done.

---

*[openfl/display/DisplayObjectContainer.hx, line 707 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnDtyyJaZqtyYzQ1F_D:-KnE1IfBh25S3dybC1Nr:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/77deb76cb56eb64118ea0d083b1ca7f640729f33/openfl/display/DisplayObjectContainer.hx#L707)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> #if compliant_stage_events
> 					if ( stack[stack.length] == this ) {
> 						stack.push(child);
> 					} else {
> 						stack[stack.length] = child;
> 					}
> 				#end
same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 677 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnE7n1pWDk7HnqxxGOb:-KnE7n1pWDk7HnqxxGOc:bak91ua) ([raw file](https://github.com/fishingcactus/openfl/blob/fb5a64b0717ddef5fc362d4133e1aecafd924288/openfl/display/DisplayObjectContainer.hx#L677)):*
> if ( stack[stack.length-1] != this ) {
> 					throw "Unexpected stack. Fix behavior..";
>  
>  
> 				}

#if dev ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Comment by gogoprog** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 677 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/276#-KnE7n1pWDk7HnqxxGOb:-KnEooCDvI5194-GgC9O:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/fb5a64b0717ddef5fc362d4133e1aecafd924288/openfl/display/DisplayObjectContainer.hx#L677)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> if ( stack[stack.length-1] != this ) {
> 					throw "Unexpected stack. Fix behavior..";
>  
>  
> 				}

#if dev ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/276)*

**Pull request merged**
