### PR TITLE
Optimized hit testing

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/281)

### CODE REVIEW

**Comment by gogoprog** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/281)*

**Comment by crazyjul** [comment]
Reviewed 9 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/281)*

**Comment by NuclearCookie** [comment]
Reviewed 9 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[openfl/display/Stage.hx, line 711 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/281#-KoD744naG2lh1MHpgfd:-KoD744naG2lh1MHpgfe:bht9fq2) ([raw file](https://github.com/fishingcactus/openfl/blob/702e4e2ee9ad49b4745c35f2178b0c31a9e460cf/openfl/display/Stage.hx#L711)):*
> ```Haxe
> 					} else {
> 						child.__mustEvaluateHitTest = false;
> 						__ancestorHasMouseListenerStack.set (__allChildrenLength, false);
> ```

could be simplified by moving `__ancestorHasMouseListenerStack.set (__allChildrenLength, child.__mustEvalbuateHitTest );` out of the condition

---

*[openfl/events/EventDispatcher.hx, line 18 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/281#-KoD7La6gPW5J5veVnVw:-KoD7La6gPW5J5veVnVx:bohf8cu) ([raw file](https://github.com/fishingcactus/openfl/blob/702e4e2ee9ad49b4745c35f2178b0c31a9e460cf/openfl/events/EventDispatcher.hx#L18)):*
> ```Haxe
> 	private var __newEventMap:Map<String, Array<Listener>>;
> 	private var __mouseListenerCount:Int = 0;
> 	private var __mustEvaluateHitTest:Bool = false;
> ```

doesn't this belong in DisplayObject ? Eventdispatcher by itself could never be hittested.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/281)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/Stage.hx, line 711 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/281#-KoD744naG2lh1MHpgfd:-KoDW83F4oXleYGqQWBo:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/702e4e2ee9ad49b4745c35f2178b0c31a9e460cf/openfl/display/Stage.hx#L711)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

could be simplified by moving `__ancestorHasMouseListenerStack.set (__allChildrenLength, child.__mustEvalbuateHitTest );` out of the condition
</blockquote></details>

Done.

---

*[openfl/events/EventDispatcher.hx, line 18 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/281#-KoD7La6gPW5J5veVnVw:-KoDV24wGXMZ3nyq-oXv:bi3lves) ([raw file](https://github.com/fishingcactus/openfl/blob/702e4e2ee9ad49b4745c35f2178b0c31a9e460cf/openfl/events/EventDispatcher.hx#L18)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

doesn't this belong in DisplayObject ? Eventdispatcher by itself could never be hittested.. 
</blockquote></details>

Done. Was afraid to be too low (or high, depends how you see things) in the class hierarchy and miss some custom classes (out of openfl). After a quick search, it seems indeed it can safely be moved to DO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/281)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/281#-:-KoGXpHDcCEVhblG-XPV:bnfp4nl)*

**Pull request merged**
