### PR TITLE
Fix extra line added by close path

### PR DESCRIPTION
**Pull request by crazyjul**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/215)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 237 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/215#-KgZJNukq5iFDjB49ZVM:-KgZJNukq5iFDjB49ZVN:bpkrvyn) ([raw file](https://github.com/fishingcactus/openfl/blob/937bc6f4b56362d39b3ae2e9ed7b3b29495e4238/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L237)):*
> ```Haxe
> 			if (canvasGraphics.hasFill && closeGap) {
> 
> 				context.lineTo (startX, startY);
> ```

Don't you miss a context.closePath() after this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/215)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/215)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 237 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/215#-KgZJNukq5iFDjB49ZVM:-KgmcRwEkYY6w4gsgDkc:b-7nd4hn) ([raw file](https://github.com/fishingcactus/openfl/blob/937bc6f4b56362d39b3ae2e9ed7b3b29495e4238/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L237)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Don't you miss a context.closePath() after this?
</blockquote></details>

It seems the shapes from swf are always closed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/215#-:-Kgmc_iFZgx42qMoeS4c:bnfp4nl)*

**Comment by gogoprog** [comment]
After more investigation this doesn't fix the issue.
The bug is in IE11/Edge code, so closing this.

**Pull request closed without merging**
