### PR TITLE
Feature parse font properties

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/30)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r4.
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[openfl/text/TextField.hx, line 1201 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwlqeluKi_LsQYzYR6:-KPwlqeluKi_LsQYzYR7:b-lbgimt) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1201)):_

> ``` Haxe
>                       if(tag.indexOf("<font") == 0 ) {
> 
>                           var faceIndex = tag.indexOf ("face=");
> ```

attributes are not in node name

---

_[openfl/text/TextField.hx, line 1223 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwlyAf6H9thXESxNxn:-KPwlyAf6H9thXESxNxo:b-3ta5d1) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1223)):_

> ``` Haxe
>                           }
>           } else {
>                           throw "trying to parse unsupported tag from localization";
> ```

Localization has nothing to do here

---

_[openfl/text/TextField.hx, line 1224 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwm0b2TYyiU7ku59jC:-KPwm0b2TYyiU7ku59jD:b-7i5fxt) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1224)):_

> ``` Haxe
>           } else {
>                           throw "trying to parse unsupported tag from localization";
>                       }
> ```

indentation is broken

---

_[openfl/text/TextField.hx, line 1251 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwkJQoVN_zUfiXcwZ-:-KPwkJQoVN_zUfiXcwZ0:byw9ad6) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1251)):_

> ``` Haxe
>           value = new EReg ("<br/>", "g").replace (value, "\n");
> 
>           var data = Xml.parse(value);
> ```

Are we sure the html always start by a tag?

---

_[openfl/text/TextField.hx, line 1255 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwmBhdxSHC0cz_ju2U:-KPwmBhdxSHC0cz_ju2V:boduyrn) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1255)):_

> ``` Haxe
>           __textEngine.textFormatRanges.splice (0, __textEngine.textFormatRanges.length);
>           value = parseTags(data, __textFormat.clone(), 0).text;
> 
> ```

This is a bit ugly, value is returned but __textEngine.textFormatRanges is modified on the fly.
Return both

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/30)_

**Comment by NuclearCookie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[openfl/text/TextField.hx, line 1251 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwkJQoVN_zUfiXcwZ-:-KPwpGu54wOU35IGmE9t:boxkygi) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1251)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> Are we sure the html always start by a tag?
> </details>
> It does not. But it does not seem to be a problem for the parser. It automatically adds a root node.

---

_[openfl/text/TextField.hx, line 1255 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwmBhdxSHC0cz_ju2U:-KPwpq6n1ziT4sj-RhbY:b-7x88fx) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1255)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> This is a bit ugly, value is returned but __textEngine.textFormatRanges is modified on the fly.
> Return both
> </details>
> You mean returning the new format ranges in parseTags and adding all of them after parsing?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/30)_

**Comment by crazyjul** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

_[openfl/text/TextField.hx, line 1251 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwkJQoVN_zUfiXcwZ-:-KPwro_Nlk1fKk-QD0Ki:b-ry69bk) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1251)):_
<details><summary>

<i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary>



> It does not. But it does not seem to be a problem for the parser. It automatically adds a root node.
> </details>
> Ok, I'll check it

---

_[openfl/text/TextField.hx, line 1255 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwmBhdxSHC0cz_ju2U:-KPwrgLfWdFabC90hJi5:bajh3lw) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1255)):_
<details><summary>

<i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary>



> You mean returning the new format ranges in parseTags and adding all of them after parsing?
> </details>
> yes, that would make the function clearer on what it changes

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/30)_

**Comment by NuclearCookie** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[openfl/text/TextField.hx, line 1201 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwlqeluKi_LsQYzYR6:-KPww6e-vYWn7UFp22qc:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1201)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> attributes are not in node name
> </details>
> Done.

---

_[openfl/text/TextField.hx, line 1223 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwlyAf6H9thXESxNxn:-KPww7bvQVdqDgLLPScw:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1223)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> Localization has nothing to do here
> </details>
> Done.

---

_[openfl/text/TextField.hx, line 1224 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwm0b2TYyiU7ku59jC:-KPww82Grb3nBx_nGYts:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1224)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> indentation is broken
> </details>
> Done.

---

_[openfl/text/TextField.hx, line 1255 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/30#-KPwmBhdxSHC0cz_ju2U:-KPwwA60hgiOao5h4Uey:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3eeb0c88f0144c4a50816abccc206fb0c8b328ba/openfl/text/TextField.hx#L1255)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> yes, that would make the function clearer on what it changes
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/30)_

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/30)_

**Pull request merged**
