### PR TITLE
Fixed leak with cache as bitmap

### PR DESCRIPTION
**Pull request by NuclearCookie**
When using GLBitmap.drawBitmapDrawable, we had a potential leak.
We explicitly disabled cacheAsBitmap for the source, but not for the children of the source.
This caused leaked bitmaps.

Solution was to add global flag to the renderer to enable or disable cached as bitmap.

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/270)

### CODE REVIEW

**Comment by crazyjul** [comment]
I'm afraid that this change might break the caching of a movie clip with children having filters.

cacheGL is applying the filters

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-:-KmcCvKUbE7d9XZIsbUa:b-vqpgbw)*

**Comment by NuclearCookie** [comment]
Good point... Thanks!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-:-KmeUZfV2FZjHLXy3Bnj:bcnnaj8)*

**Comment by NuclearCookie** [comment]
@crazyjul New approach :)

**Comment by gogoprog** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 169 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-KmenD_y_TelBl9ufqeG:-KmenD_zR9J3SjeLxdsx:bmr9i8u) ([raw file](https://github.com/fishingcactus/openfl/blob/c915ce47694c56567fbe29431f6050ba29d526c4/openfl/_internal/renderer/opengl/GLBitmap.hx#L169)):*
> ```Haxe
> 		if ( Std.is(source, DisplayObject) ) {
> 			if ( cast(source, DisplayObject).stage == null ) {
> 				throw "Leaking textures. Add source to the stage, and pop it afterwards";
> ```

Can't we call directly releaseResources from here?

I don't like the fact you force to add to stage something that shouldn't be added (for manual draw calls)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270)*

**Comment by gogoprog** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270)*

**Comment by rams3s** [comment]
Reviewed 1 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 169 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-KmenD_y_TelBl9ufqeG:-Kmf7mVUO8hRfR2rUEDS:brhm2c3) ([raw file](https://github.com/fishingcactus/openfl/blob/c915ce47694c56567fbe29431f6050ba29d526c4/openfl/_internal/renderer/opengl/GLBitmap.hx#L169)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Can't we call directly releaseResources from here?

I don't like the fact you force to add to stage something that shouldn't be added (for manual draw calls)
</blockquote></details>

I would rather call it, potential texture leak ;)

@gogoprog Unfortunately, we cannot release resources here because we need them for later (this is used for creating a cached texture manually).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270)*

**Comment by gogoprog** [comment]
*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 169 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-KmenD_y_TelBl9ufqeG:-Kmf8SUqgTkv8pfdglhc:b-jy9dfy) ([raw file](https://github.com/fishingcactus/openfl/blob/c915ce47694c56567fbe29431f6050ba29d526c4/openfl/_internal/renderer/opengl/GLBitmap.hx#L169)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

I would rather call it, potential texture leak ;)

@gogoprog Unfortunately, we cannot release resources here because we need them for later (this is used for creating a cached texture manually).
</blockquote></details>

Indeed but I'm still not convinced by the force-to-add-to-stage..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 169 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-KmenD_y_TelBl9ufqeG:-KmfLQUu76Koemy7n5db:b-kwjw3g) ([raw file](https://github.com/fishingcactus/openfl/blob/c915ce47694c56567fbe29431f6050ba29d526c4/openfl/_internal/renderer/opengl/GLBitmap.hx#L169)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Indeed but I'm still not convinced by the force-to-add-to-stage..
</blockquote></details>

Check my new code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270)*

**Comment by crazyjul** [comment]
I think you can squash your commit to remove internediate version from history

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-:-KmkIWC8vyJQQNtB4lHD:bfbtlxv)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-:-Kn3XICCQX4F6C2yvNw9:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Squashed

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/270#-:-Kn8idrwORHlwWf3ACk3:bo7s01v)*

**Pull request merged**
