### PR TITLE
Take children's filter bounds into account when generating cached bit…

### LINKED ISSUE #194: Missing filter growBounds
It seems we miss a growBounds here :

```cpp
    private function __getBounds (rect:Rectangle):Void {

		if (__graphics != null) {

			__graphics.__getBounds (rect);

		} else {

			rect.setEmpty ();

		}

               //  this one :
		if (__filters != null) {
			@:privateAccess BitmapFilter.__expandBounds (__filters, rect, Matrix.__identity);
		}
	}
```

This needs to be discussed

### PR DESCRIPTION
**Pull request by NuclearCookie**
Fixes #194

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/275)

### CODE REVIEW

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275#-:-KnDuWheUDKYfnXGXD9-:bnfp4nl)*

**Comment by gogoprog** [comment]
*[openfl/display/DisplayObjectContainer.hx, line 393 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/275#-KnE39-JNoQj1Q5Avkgl:-KnE39-JNoQj1Q5Avkgm:bsnenil) ([raw file](https://github.com/fishingcactus/openfl/blob/015d01a7320ccc0b29ac899d6bfe3b654726f738/openfl/display/DisplayObjectContainer.hx#L393)):*
> ```Haxe
> 		for (child in __children) {
> 
> 			if (child == null ) continue;
> ```

I'm surprised you need that, we should not have gaps in the children

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275)*

**Comment by gogoprog** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 393 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/275#-KnE39-JNoQj1Q5Avkgl:-KnE5b1Ddu2UJmRD0bLJ:bf8ofew) ([raw file](https://github.com/fishingcactus/openfl/blob/015d01a7320ccc0b29ac899d6bfe3b654726f738/openfl/display/DisplayObjectContainer.hx#L393)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

I'm surprised you need that, we should not have gaps in the children
</blockquote></details>

if it's copied from other code, I use to require this in an attempt to support flash timeline. Since I changed solution, this test should be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275)*

**Comment by NuclearCookie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObjectContainer.hx, line 393 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/275#-KnE39-JNoQj1Q5Avkgl:-KnEAR_iBmUhkusmxZv1:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/015d01a7320ccc0b29ac899d6bfe3b654726f738/openfl/display/DisplayObjectContainer.hx#L393)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

if it's copied from other code, I use to require this in an attempt to support flash timeline. Since I changed solution, this test should be removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275#-:-KnEAjWh2YWCpjiV9yCP:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/275)*

**Pull request merged**
