### PR TITLE
Feature/graphics refactor

### PR DESCRIPTION
**Pull request by gogoprog**
DrawCommandBuffer constructed in swf export

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/213)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 430 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgKgGn3pwr1WP6AIdsp:-KgKgGn3pwr1WP6AIdsq:br1t293) ([raw file](https://github.com/fishingcactus/openfl/blob/937bc6f4b56362d39b3ae2e9ed7b3b29495e4238/format/swf/lite/MovieClip.hx#L430)):*
> No more (shallow) copy required here?

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 84 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgKf6NDA-huWpd6CCWs:-KgKf6NDA-huWpd6CCWt:bw1tmj8) ([raw file](https://github.com/fishingcactus/openfl/blob/25f9297013930653efdc7c92123b0f01e8ed9ec7/format/swf/lite/symbols/ShapeSymbol.hx#L84)):*
> ```Haxe
> 	public function fillDrawCommandBuffer(shapeCommands:Array<ShapeCommand>)
> 	{
> 		graphics = @:privateAccess new Graphics();
> ```

graphics.__owner ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by crazyjul** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 84 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgKf6NDA-huWpd6CCWs:-KgON0VJ2MTr37oe0ufz:b3e7me9) ([raw file](https://github.com/fishingcactus/openfl/blob/25f9297013930653efdc7c92123b0f01e8ed9ec7/format/swf/lite/symbols/ShapeSymbol.hx#L84)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

graphics.__owner ?
</blockquote></details>

Not needed if you can't change the graphics. It's only used for dirtyness update

---

*[openfl/display/Shape.hx, line 43 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgOOk4k1PLAlEqB2jRW:-KgOOk4lqyZ74n-AdvAQ:b-ftz0nf) ([raw file](https://github.com/fishingcactus/openfl/blob/25f9297013930653efdc7c92123b0f01e8ed9ec7/openfl/display/Shape.hx#L43)):*
> ```Haxe
> 	}
> 
> 	private function set_graphics (graphics:Graphics):Graphics {
> ```

I don't like this setter, it should not be allowed to do this. I rather use a private access to set this field

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 430 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgKgGn3pwr1WP6AIdsp:-KgT5RLtT7CcmUgraiZv:b6il1l1) ([raw file](https://github.com/fishingcactus/openfl/blob/937bc6f4b56362d39b3ae2e9ed7b3b29495e4238/format/swf/lite/MovieClip.hx#L430)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> No more (shallow) copy required here?
</blockquote></details>

Indeed it is always a ref now.
I think I miss the case when it needs to be copied (g.e same symbol different scales?)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by gogoprog** [comment]
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/Shape.hx, line 43 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgOOk4k1PLAlEqB2jRW:-KgT8a2fzMRF0Gkr8sDS:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/25f9297013930653efdc7c92123b0f01e8ed9ec7/openfl/display/Shape.hx#L43)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I don't like this setter, it should not be allowed to do this. I rather use a private access to set this field
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by gogoprog** [comment]
Review status: 13 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 430 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-KgKgGn3pwr1WP6AIdsp:-KgTE_kgMTTwED2JxsOC:bw9g2r5) ([raw file](https://github.com/fishingcactus/openfl/blob/937bc6f4b56362d39b3ae2e9ed7b3b29495e4238/format/swf/lite/MovieClip.hx#L430)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Indeed it is always a ref now.
I think I miss the case when it needs to be copied (g.e same symbol different scales?)
</blockquote></details>

After discussion I'm gonna put back the shallow copy

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213#-:-KgTk-_brsAtUmcZ_uFL:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/213)*

**Pull request merged**
