### PR TITLE
WIP: Feature/animation preprocessor

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/340)

### CODE REVIEW

**Comment by gogoprog** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 312 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy8vGBPSmPvU787vng:-Kuy8vGBPSmPvU787vnh:b-yi9ppf) ([raw file](https://github.com/fishingcactus/openfl/blob/7ff944dfc362290eaeca5ed3a6d33c0611d26da5/format/swf/lite/symbols/ShapeSymbol.hx#L312)):*
> private static function __clearCachedTables(e:openfl.events.Event) {
> 		var width = Reflect.getProperty (e.currentTarget, "width");
> 		var height = Reflect.getProperty (e.currentTarget, "height");
>  
> 		if(lastStageWidth != width || lastStageHeight != height) {
> 			#if profile
> 				for(s in shapeSymbolsUsingBitmapCacheMap) {
> 					s.__clearCachedTable();
> 				}
> 			#end
> 			lastStageWidth = width;
> 			lastStageHeight = height;
> 		}
> 	}

This function isn't doing anything when profile=0

---

*[openfl/utils/AnimationPreprocessor.hx, line 10 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy9ZPQGhqONcdgEQtV:-Kuy9ZPQGhqONcdgEQtW:b8xiemq) ([raw file](https://github.com/fishingcactus/openfl/blob/7ff944dfc362290eaeca5ed3a6d33c0611d26da5/openfl/utils/AnimationPreprocessor.hx#L10)):*
> ```Haxe
> import openfl.geom.Matrix;
> 
> class AnimationPreprocessor {
> ```

MovieClipPreprocessor is a better name ;)

---

*[openfl/utils/AnimationPreprocessor.hx, line 55 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuyAAM-IbpxYXFAPf0f:-KuyAAM-IbpxYXFAPf0g:bypd4qy) ([raw file](https://github.com/fishingcactus/openfl/blob/7ff944dfc362290eaeca5ed3a6d33c0611d26da5/openfl/utils/AnimationPreprocessor.hx#L55)):*
> ```Haxe
> 
>         for (entry in graphicsToProcessTable) {
>             var symbol = @:privateAccess cast(entry.graphics.__symbol, ShapeSymbol);
> ```

should test the type, TextFields could also be here

---

*[openfl/utils/AnimationPreprocessor.hx, line 59 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuyATqGEgMz_xrGpQK_:-KuyATqGEgMz_xrGpQKa:b-o7vbrn) ([raw file](https://github.com/fishingcactus/openfl/blob/7ff944dfc362290eaeca5ed3a6d33c0611d26da5/openfl/utils/AnimationPreprocessor.hx#L59)):*
> ```Haxe
>         }
> 
>         haxe.Timer.delay (cacheGraphics, 16);
> ```

Why not zero?

---

*[openfl/utils/AnimationPreprocessor.hx, line 84 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuyAZXqlSw84lvxGECT:-KuyAZXqlSw84lvxGECU:bb7od0r) ([raw file](https://github.com/fishingcactus/openfl/blob/7ff944dfc362290eaeca5ed3a6d33c0611d26da5/openfl/utils/AnimationPreprocessor.hx#L84)):*
> ```Haxe
>             graphicsToProcessIndex = 0;
>         } else {
>             haxe.Timer.delay (cacheGraphics, 16);
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 312 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy8vGBPSmPvU787vng:-KuybhFlgC17BbQaZTcb:b1t32ke) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/format/swf/lite/symbols/ShapeSymbol.hx#L312)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

> private static function __clearCachedTables(e:openfl.events.Event) {
> 		var width = Reflect.getProperty (e.currentTarget, "width");
> 		var height = Reflect.getProperty (e.currentTarget, "height");
>  
> 		if(lastStageWidth != width || lastStageHeight != height) {
> 			#if profile
> 				for(s in shapeSymbolsUsingBitmapCacheMap) {
> 					s.__clearCachedTable();
> 				}
> 			#end
> 			lastStageWidth = width;
> 			lastStageHeight = height;
> 		}
> 	}

This function isn't doing anything when profile=0
</blockquote></details>

@rams3s Are you sure about this? This used to clear the cache when resizing.. Why only doing this #if profile ?

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 319 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuyc3RvzmMWZj_YQ7Un:-Kuyc3RvzmMWZj_YQ7Uo:bwgurp4) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/format/swf/lite/symbols/ShapeSymbol.hx#L319)):*
> ```Haxe
> 
> private abstract FixedPointNumber(Int) {
> 	public function new (value:Int) {
> ```

private constructor

---

*[openfl/utils/AnimationPreprocessor.hx, line 10 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy9ZPQGhqONcdgEQtV:-KuycNWki5RPFMU3b-LL:b-m8rxjm) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/openfl/utils/AnimationPreprocessor.hx#L10)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

MovieClipPreprocessor is a better name ;)
</blockquote></details>

I prefer GraphicsPreprocessor

---

*[openfl/utils/AnimationPreprocessor.hx, line 16 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuycY-NrQh_AhcqEbk6:-KuycY-NrQh_AhcqEbk7:bvnrpc5) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L16)):*
> ```Haxe
> 
>     static public function renderCompleteAnimation(movieclip : MovieClip, useDelay:Bool) {
>         // :NOTE: update all parent transforms
> ```

updateS

---

*[openfl/utils/AnimationPreprocessor.hx, line 32 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuyd9qgOI1GmqazGy2N:-Kuyd9qgOI1GmqazGy2O:b9fsmdm) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L32)):*
> ```Haxe
>             movieclip.__update(true, true);
> 
>             containerToProcessTable.clear ();
> ```

no need to clear due to next while loop condition

---

*[openfl/utils/AnimationPreprocessor.hx, line 42 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuydVINgzNPN5hYj4yU:-KuydVINgzNPN5hYj4yV:b-45bcvd) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L42)):*
> ```Haxe
>                     if ( graphics != null ) {
>                         // :TODO: get transform from pool (or store coefficients manually)
>                         graphicsToProcessTable.push({ graphics: graphics, transform: child.__renderTransform.clone() });
> ```

Push descretized transforms?

---

*[openfl/utils/AnimationPreprocessor.hx, line 75 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuye72mBoAuIDt4HlVY:-Kuye72mBoAuIDt4HlVZ:b-anodw4) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L75)):*
> ```Haxe
>         var renderSession = @:privateAccess Lib.current.stage.__renderer.renderSession;
>         var gl:lime.graphics.GLRenderContext = renderSession.gl;
>         var count = Std.int (Math.min (graphicsToProcessTable.length - graphicsToProcessIndex, 20));
> ```

Don't count. 
Use a timer in the loop and break after a certain delay ( 10ms ? 25ms? )
If you count, you could have 20 super huge graphics --> slow frame.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[openfl/utils/AnimationPreprocessor.hx, line 32 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuyd9qgOI1GmqazGy2N:-Kv1Nm1irSJmhAiEarN_:bb6ywmx) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L32)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no need to clear due to next while loop condition
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by rams3s** [comment]
Review status: 2 of 3 files reviewed at latest revision, 11 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 312 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy8vGBPSmPvU787vng:-Kv1aS5G1_RVDB_rcIbA:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/format/swf/lite/symbols/ShapeSymbol.hx#L312)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

@rams3s Are you sure about this? This used to clear the cache when resizing.. Why only doing this #if profile ?
</blockquote></details>

Done.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 319 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuyc3RvzmMWZj_YQ7Un:-Kuyj_ApKhAaYZxKlJYE:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/format/swf/lite/symbols/ShapeSymbol.hx#L319)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

private constructor
</blockquote></details>

Done.

---

*[openfl/utils/AnimationPreprocessor.hx, line 10 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuy9ZPQGhqONcdgEQtV:-Kv1ahiPJYM2ODRZyWxt:baw5ux) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/openfl/utils/AnimationPreprocessor.hx#L10)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

I prefer GraphicsPreprocessor
</blockquote></details>

I vote for MovieClipPreprocessor so that it can be used for more than Graphics caching

---

*[openfl/utils/AnimationPreprocessor.hx, line 55 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuyAAM-IbpxYXFAPf0f:-Kv1cdal6BOlLJf5AUDs:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/openfl/utils/AnimationPreprocessor.hx#L55)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

should test the type, TextFields could also be here
</blockquote></details>

Done.

---

*[openfl/utils/AnimationPreprocessor.hx, line 59 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuyATqGEgMz_xrGpQK_:-Kv1ciBMu5g7KrmUptiF:b-jnrnre) ([raw file](https://github.com/fishingcactus/openfl/blob/349d183b3b5240bd0cad8a1b6fc841251e130129/openfl/utils/AnimationPreprocessor.hx#L59)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Why not zero?
</blockquote></details>

I wanted to ensure we can insert a render frame between 2 invocations and not delay the render more than it should

---

*[openfl/utils/AnimationPreprocessor.hx, line 16 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuycY-NrQh_AhcqEbk6:-KuyjpIR969bSH4GfyPW:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L16)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

updateS
</blockquote></details>

Done.

---

*[openfl/utils/AnimationPreprocessor.hx, line 32 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuyd9qgOI1GmqazGy2N:-Kuyjx7ZBudTEbfEQmiZ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L32)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no need to clear due to next while loop condition
</blockquote></details>

Done.

---

*[openfl/utils/AnimationPreprocessor.hx, line 42 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-KuydVINgzNPN5hYj4yU:-Kuyk3-s-XJ3UEc48e8r:b-2s0g7v) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L42)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Push descretized transforms?
</blockquote></details>

discretrized transform is implementation detail of symbol cache

---

*[openfl/utils/AnimationPreprocessor.hx, line 75 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kuye72mBoAuIDt4HlVY:-Kv1mNY4TH51jvlCqsBe:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L75)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Don't count. 
Use a timer in the loop and break after a certain delay ( 10ms ? 25ms? )
If you count, you could have 20 super huge graphics --> slow frame.
</blockquote></details>

Done.

---

*[openfl/utils/AnimationPreprocessor.hx, line 99 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kv1fIau1NEaMpDmRXug:-Kv1fIau1NEaMpDmRXuh:b89plks) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L99)):*
> ```Haxe
>         }
>     }
>     static public function renderCompleteInstant(clipId:String)
> ```

Movie clip cache will be generated at the scale of the stage... if it is added to a container with a different, this warmup will be lost. Isn't it possible to use the above call directly ? or to provide the final container as argument?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by gogoprog** [comment]
Review status: 1 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 82 at r8](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kv6jsdl716pVOXwLhAV:-Kv6jsdl716pVOXwLhAW:bsv3o5v) ([raw file](https://github.com/fishingcactus/openfl/blob/b29f5baef436734d31a28f04aaa91156fb49bb30/openfl/utils/MovieClipPreprocessor.hx#L82)):*
> ```Haxe
>         validate ();
> 
>         var startTime = haxe.Timer.stamp () * 1000;
> ```

better use openfl.Lib.getTimer()

---

*[openfl/utils/MovieClipPreprocessor.hx, line 132 at r8](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kv6kEWti7jjDzMOONMm:-Kv6kEWti7jjDzMOONMn:bb7od0r) ([raw file](https://github.com/fishingcactus/openfl/blob/b29f5baef436734d31a28f04aaa91156fb49bb30/openfl/utils/MovieClipPreprocessor.hx#L132)):*
> ```Haxe
>         var renderSession = @:privateAccess Lib.current.stage.__renderer.renderSession;
>         var gl:lime.graphics.GLRenderContext = renderSession.gl;
>         var startTime = haxe.Timer.stamp () * 1000;
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r8.
Review status: 1 of 3 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by crazyjul** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r7, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 116 at r9](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kv71_q0DJ8lor1RYrD5:-Kv71_q0DJ8lor1RYrD6:b-lr5kpo) ([raw file](https://github.com/fishingcactus/openfl/blob/100d1e7d917a5963c11ac8550afb2d5512825ed5/format/swf/lite/symbols/ShapeSymbol.hx#L116)):*
> ```Haxe
> 
> 			// :TODO: pool
> 			var fixedRenderTransform = new DiscretizedTransform (renderTransform, cachePrecision);
> ```

Might be faster to generate a unique key and use a simple lookup

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r10.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by gogoprog** [comment]
Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[openfl/utils/AnimationPreprocessor.hx, line 99 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/340#-Kv1fIau1NEaMpDmRXug:-KvBVvgAaLeUzSOViVrp:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d3d1082650c74d6bcc9145c075b539d514b36dd/openfl/utils/AnimationPreprocessor.hx#L99)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

Movie clip cache will be generated at the scale of the stage... if it is added to a container with a different, this warmup will be lost. Isn't it possible to use the above call directly ? or to provide the final container as argument?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/340)*

**Pull request merged**
