### PR TITLE
Support for a blur of 0

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/68)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[openfl/filters/commands/CommandType.hx, line 8 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/68#-KUM2JLQKVAUTGaoMOa1:-KUM2JLQKVAUTGaoMOa2:bg5a7g1) ([raw file](https://github.com/fishingcactus/openfl/blob/2a24a7ed79ea951385e6fdb2fbab6af61bf67393/openfl/filters/commands/CommandType.hx#L8)):_

> ``` Haxe
> 
>   Blur1D (target:BitmapData, source:BitmapData, blur:Float, horizontal:Bool, distance:Float, angle:Float, strength:Float);
>   Offset (target:BitmapData, source:BitmapData, distance:Float, angle:Float, strength:Float);
> ```

Parameter order is not the same as when used in switch case (strength, distance, angle).
Same for the above Blur1D enum for which I'm responsible ;)

---

_[openfl/filters/commands/OffsetCommand.hx, line 10 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/68#-KUM39kCYc-c7L0RfaGZ:-KUM39kDzzt4nsU8Kvkh:bwik65e) ([raw file](https://github.com/fishingcactus/openfl/blob/2a24a7ed79ea951385e6fdb2fbab6af61bf67393/openfl/filters/commands/OffsetCommand.hx#L10)):_

> ``` Haxe
> class OffsetCommand {
> 
>   public static inline var MAXIMUM_FETCH_COUNT = 20;
> ```

no need for fetch count

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/68)_

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[openfl/filters/commands/CommandType.hx, line 8 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/68#-KUM2JLQKVAUTGaoMOa1:-KUM5GUMoCD97GsewJ3u:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/2a24a7ed79ea951385e6fdb2fbab6af61bf67393/openfl/filters/commands/CommandType.hx#L8)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> Parameter order is not the same as when used in switch case (strength, distance, angle).
> Same for the above Blur1D enum for which I'm responsible ;)
> </details>
> Done.

---

_[openfl/filters/commands/OffsetCommand.hx, line 10 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/68#-KUM39kCYc-c7L0RfaGZ:-KUM5FND2U9OjMftZdrD:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/2a24a7ed79ea951385e6fdb2fbab6af61bf67393/openfl/filters/commands/OffsetCommand.hx#L10)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> no need for fetch count
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/68)_

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/68#-:-KUM5gWSCSOF-glvU9yO:bnfp4nl)_

**Comment by NuclearCookie** [comment]
Why close this?

**Comment by NuclearCookie** [comment]
Updated base branch.

**Pull request merged**
