### PR TITLE
Fix cached in cached

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/105)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 287 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/105#-KXqMuAOmCrAv_tyXtrt:-KXqMuAOmCrAv_tyXtru:b-9nhij5) ([raw file](https://github.com/fishingcactus/openfl/blob/5e60650041c364ff544faddb361783bb9657da1f/openfl/_internal/renderer/opengl/GLBitmap.hx#L287)):*
> ```Haxe
> 	private static inline function mustFlipMatrix ():Bool {
> 
> 		return fbData.length == 2;
> ```

I'm not sure about this, I would expect to be >= 2. What's the reason?

---

*[openfl/filters/BitmapFilter.hx, line 56 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/105#-KXqNg-WiE5UElPnylsr:-KXqNg-XW7PQWcB4ySFc:b-7jcmbd) ([raw file](https://github.com/fishingcactus/openfl/blob/579068482630d7e71c768847c8a1794674e2c340/openfl/filters/BitmapFilter.hx#L56)):*
> ```Haxe
> 		var inverseTransform = Matrix.pool.get ();
> 		inverseTransform.copyFrom (transform);
> 		inverseTransform.invert ();
> ```

This was crappy, good catch

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105)*

**Comment by rams3s** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 287 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/105#-KXqMuAOmCrAv_tyXtrt:-KYUDvKOlWlLPNTZgWX2:b-6k7soh) ([raw file](https://github.com/fishingcactus/openfl/blob/5e60650041c364ff544faddb361783bb9657da1f/openfl/_internal/renderer/opengl/GLBitmap.hx#L287)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I'm not sure about this, I would expect to be >= 2. What's the reason?
</blockquote></details>

Not used anymore. We only wanted to flip once for first render to texture. Otherwise subsequent cacheAsBitmap in the hierarchy would ping pong the flipping behavior.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105)*

**Comment by crazyjul** [comment]
Reviewed 4 of 6 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105)*

**Comment by crazyjul** [comment]
:lgtm:

---

Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105#-:-KYmOlzwTEtKIUFULtmF:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 2 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/105#-:-KYmQ0fOK4_LjZWpUZpk:bg7igk9)*

**Pull request merged**
