### PR TITLE
updateSwfMaskData was called too often. cache and update 1 time per f…

### PR DESCRIPTION
**Pull request by NuclearCookie**
…rame

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/190)

### CODE REVIEW

**Comment by crazyjul** [comment]
I believe the other solution was a better one. This looks a more expensive solution

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 737 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-KddvhN-XbbXc_HQpv9f:-KddvhN0r_FJ7_b0hol8:b-nssmkh) ([raw file](https://github.com/fishingcactus/openfl/blob/959747fdf4ecc3b369f592130f23e1dc36a8db99/format/swf/lite/MovieClip.hx#L737)):*
> ```Haxe
> 	}
> 
> 	public override function __update (transformOnly:Bool, updateChildren:Bool):Void {
> ```

This choice double the size of the callstack when updating movie clip

---

*[format/swf/lite/MovieClip.hx, line 893 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-KddvrphouueA0PDRmg3:-KddvrphouueA0PDRmg4:b-y5rb57) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L893)):*
> ```Haxe
> 
> 							removeChild(displayObject);
> 							__maskDataKeys.remove(displayObject);
> ```

This is not done anywhere else. Removing those calls will keep the table filled

---

*[format/swf/lite/MovieClip.hx, line 948 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-Kddw1Qb5qXMUWrnirC9:-Kddw1Qb5qXMUWrnirCA:buo9nmt) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L948)):*
> ```Haxe
> 
> 						var clipDepth = __maskData.get(displayObject);
> 						__maskDataKeys.remove(displayObject);
> ```

Same here

---

*[format/swf/lite/MovieClip.hx, line 997 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-Kddw2egSsXLISx2SF7N:-Kddw2egSsXLISx2SF7O:b-7tdrph) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L997)):*
> ```Haxe
> 
> 						removeChild (displayObject);
> 						__SWFDepthData.remove(displayObject);
> ```

again

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-:-Kddw57q1cumdhja5Phn:b993v56)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 893 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-KddvrphouueA0PDRmg3:-Kde45ba0JOWDHtN6lEB:b84vxiv) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L893)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

This is not done anywhere else. Removing those calls will keep the table filled
</blockquote></details>

It's done inside the removeChild.. was done double

---

*[format/swf/lite/MovieClip.hx, line 948 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-Kddw1Qb5qXMUWrnirC9:-Kde48cIzm8zsl8UqjaY:b84vxiv) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L948)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

It's done inside the removeChild.. was done double

---

*[format/swf/lite/MovieClip.hx, line 997 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-Kddw2egSsXLISx2SF7N:-Kde49HIJPvtjqiGTyr6:b84vxiv) ([raw file](https://github.com/fishingcactus/openfl/blob/4b05ebced20784d967eb0aff049ee9008aaab75f/format/swf/lite/MovieClip.hx#L997)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

again
</blockquote></details>

It's done inside the removeChild.. was done double

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/190)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 737 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/190#-KddvhN-XbbXc_HQpv9f:-Kde71WS7V7Agxck43uW:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/959747fdf4ecc3b369f592130f23e1dc36a8db99/format/swf/lite/MovieClip.hx#L737)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

This choice double the size of the callstack when updating movie clip
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/190)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/190)*

**Pull request merged**
