### PR TITLE
Feature/shape bitmap cache

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/156)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-:-Kbxyloe1ZElBsSx8iIu:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/Graphics.hx, line 196 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-Kbz5kfds06Km8Q0AHei:-Kbz5kfds06Km8Q0AHej:b-2mypch) ([raw file](https://github.com/fishingcactus/openfl/blob/239e3fea775aafd01d2c272eda9b44764ebebf8c/openfl/display/Graphics.hx#L196)):*
> ```Haxe
> 
> 	public inline function shallowCopyFrom (sourceGraphics:Graphics):Void {
> ```

Get rid of this function. It's only used in 1 place and it can use the updated signature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-:-KbzTGqPGJ_bsF_FzaDP:bnfp4nl)*

**Comment by rams3s** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Graphics.hx, line 196 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-Kbz5kfds06Km8Q0AHei:-Kc2TMAKHrpjVyQL1T6_:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/239e3fea775aafd01d2c272eda9b44764ebebf8c/openfl/display/Graphics.hx#L196)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Get rid of this function. It's only used in 1 place and it can use the updated signature.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156)*

**Comment by NuclearCookie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 368 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-Kc2To0OY8PZxALX73dU:-Kc2To0OY8PZxALX73dV:b-ucilyc) ([raw file](https://github.com/fishingcactus/openfl/blob/a1034bfd4581c2c215d0ceafb2e084db6ed3d2b9/format/swf/lite/MovieClip.hx#L368)):*
> ```Haxe
> 
> 		if ( symbol.graphics != null && symbol.graphics.readOnly == true ) {
> 			graphics.shallowCopyFrom( symbol.graphics, true );
> ```

It's wrong. It's copyFrom not shallowCopyFrom. This does not compile

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-:-Kc2UjxbR4Z5T7tajUQu:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 368 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/156#-Kc2To0OY8PZxALX73dU:-Kc2UrbYlbB_3-pv2R1q:b32w0x) ([raw file](https://github.com/fishingcactus/openfl/blob/a1034bfd4581c2c215d0ceafb2e084db6ed3d2b9/format/swf/lite/MovieClip.hx#L368)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

It's wrong. It's copyFrom not shallowCopyFrom. This does not compile
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/156)*

**Pull request merged**
