### PR TITLE
Feature/skip same filters

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/339)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339)*

**Comment by gogoprog** [comment]
Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/filters/BitmapFilter.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-KuxZiwCQyKdjfd9V71X:-KuxZiwCQyKdjfd9V71Y:b-doerkw) ([raw file](https://github.com/fishingcactus/openfl/blob/6d43631992a34e8527d94b1e0cefb5e0c2bc8189/openfl/filters/BitmapFilter.hx#L50)):*
> ```Haxe
> 
> 	public function equals(filter:BitmapFilter) {
> 		return true;
> ```

return false by default

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/filters/BitmapFilter.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-KuxZiwCQyKdjfd9V71X:-Kuxg6EcnHKpa56daQE1:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6d43631992a34e8527d94b1e0cefb5e0c2bc8189/openfl/filters/BitmapFilter.hx#L50)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

return false by default
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-:-KuxhOPXoLRy_CVmTzbF:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[openfl/display/DisplayObject.hx, line 1356 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-KuxyHUGU0bV6G7NvwVa:-KuxyHUGU0bV6G7NvwVb:bbo7vwt) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/display/DisplayObject.hx#L1356)):*
> ```Haxe
> 				if ( !__filters[index].equals(value[index]) ) {
> 					same = false;
> 					break;
> ```

`return value;` ;)

---

*[openfl/filters/ColorMatrixFilter.hx, line 47 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-g_UmlSQPoPC2r_X:-Kuy-g_UmlSQPoPC2r_Y:bsbllzj) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/ColorMatrixFilter.hx#L47)):*
> ```Haxe
> 		if ( Std.is(filter, ColorMatrixFilter) ) {
> 			var otherFilter:ColorMatrixFilter = cast filter;
> 			for ( index in 0...multipliers.length ) {
> ```

should also check length

---

*[openfl/filters/ConvolutionFilter.hx, line 45 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-oo1MOfqP63nvRkk:-Kuy-oo1MOfqP63nvRkl:bb7od0r) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/ConvolutionFilter.hx#L45)):*
> ```Haxe
> 		if ( Std.is(filter, ConvolutionShader) ) {
> 			var otherFilter:ConvolutionShader = cast filter;
> 			for ( index in 0...matrix.length ) {
> ```

same

---

*[openfl/filters/GradientFilter.hx, line 52 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-HzYR7lCJWGZfTCP:-Kuy-HzYR7lCJWGZfTCQ:bb7od0r) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/GradientFilter.hx#L52)):*
> ```Haxe
> 		if ( Std.is(filter, GradientFilter) ) {
> 			var otherFilter:GradientFilter = cast filter;
> 			for ( index in 0...colors.length ) {
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339)*

**Comment by NuclearCookie** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/filters/ColorMatrixFilter.hx, line 47 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-g_UmlSQPoPC2r_X:-Kuy26OPJjFIR0LAu67J:b-y7q3wp) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/ColorMatrixFilter.hx#L47)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

should also check length
</blockquote></details>

Fixed length

---

*[openfl/filters/ConvolutionFilter.hx, line 45 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-oo1MOfqP63nvRkk:-Kuy2MqSe8RhFck0_h8b:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/ConvolutionFilter.hx#L45)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[openfl/filters/GradientFilter.hx, line 52 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-Kuy-HzYR7lCJWGZfTCP:-Kuy5Ne6awyZ1HqSEeb9:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/d8276f8770ec97c920a010b6af7a7d4aa4ac4942/openfl/filters/GradientFilter.hx#L52)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/339#-:-Kuy5vtRaejv2UVRQw28:bnfp4nl)*

**Pull request merged**
