### PR TITLE
Strip _parent. for variablename lookup for DynamicTextFields.

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/410)

### CODE REVIEW

**Comment by crazyjul** [comment]
I made this fix a while ago. I don't know why this is needed again, but LGTM

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/410)*

**Comment by NuclearCookie** [comment]
*[format/swf/lite/DynamicTextField.hx, line 132 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/410#-L8W6kwQtaSSbQ8OKkLd:-L8W6kwQtaSSbQ8OKkLe:b-xuz4o3) ([raw file](https://github.com/fishingcactus/openfl/blob/11d02292c66107a23616569fadb4bd681f78c4ef/format/swf/lite/DynamicTextField.hx#L132)):*
> ```Haxe
> 		if ( hasVariableName ) {
> 
> 			var variableName = StringTools.replace( _variableName, "_parent.", "" );
> ```

Merged too soon. You're not using your new variable.. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/410)*

**Comment by rams3s** [comment]
Good catch. Wrong conflict resolution after rebase.

**Pull request merged**
