### PR TITLE
Transform dirty shouldn't have to recompute filters.

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/254)

### CODE REVIEW

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/254#-:-KkoinPWuKF67n_q0FiS:bnfp4nl)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/254)*

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/254#-:-KkojLEX0sCdSKl_XtiG:bnfp4nl)*

**Comment by NuclearCookie** [comment]
@rams3s didn't really agree with this change because it's not 100% correct. However, the behavior was wrong before introducing this change and we never noticed anything.

**Pull request merged**
