### PR TITLE
Fixed when only translation is involved

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/331)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 1167 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/331#-KuQAScGH_uT5QW5zRaT:-KuQAScGH_uT5QW5zRaU:bx42er1) ([raw file](https://github.com/fishingcactus/openfl/blob/f447ec95f8718883bf67245fed02ea6f60fcd2a3/openfl/display/DisplayObject.hx#L1167)):*
> ```Haxe
>                 old_world_transform.c != wt.c)
>             {
>                 _onWorldTransformChanged();
> ```

Restore the original name!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/331)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/331)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/331)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/331)*

**Pull request merged**
