### PR TITLE
Optimize update code

### PR DESCRIPTION
**Pull request by crazyjul**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/181)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[openfl/display/DisplayObject.hx, line 922 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/181#-KdV-2qzsgM9XiR4_ET9:-KdV-2qzsgM9XiR4_ETA:b-atdyx7) ([raw file](https://github.com/fishingcactus/openfl/blob/076fe7e2fc000b0d9f280b17fefb8c0ab93b577f/openfl/display/DisplayObject.hx#L922)):*
> ```Haxe
> 			}
> 
> 			__renderDirty = __renderDirty && updateChildren;
> ```

needs a negation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/181)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/181#-:-KdV-80Xi8YEr_SfCgLo:bnfp4nl)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/181#-:-KdVMAcvAbVxgJFTwDTe:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/181)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 922 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/181#-KdV-2qzsgM9XiR4_ET9:-KdVMU7FdpGbx5JINLRV:bb6ywmx) ([raw file](https://github.com/fishingcactus/openfl/blob/076fe7e2fc000b0d9f280b17fefb8c0ab93b577f/openfl/display/DisplayObject.hx#L922)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

needs a negation!
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/181)*

**Pull request merged**
