### PR TITLE
Wait for textfield to stand still before generating texture to avoid …

### PR DESCRIPTION
**Pull request by rams3s**
…jumps related to canvas internal snapping (Chrome and IE)

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/348)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/348)*

**Comment by NuclearCookie** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/text/TextField.hx, line 786 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/348#-KvfPBHm326wYACu-Of3:-KvfPBHm326wYACu-Of4:bcve6lv) ([raw file](https://github.com/fishingcactus/openfl/blob/19bad602ab974591cc3440febdf7b396c55fe6a2/openfl/text/TextField.hx#L786)):*
> ```Haxe
> 
> 		CanvasTextField.render (this, renderSession);
> 		GLRenderer.renderBitmap (this, renderSession, __textEngine.antiAliasType != ADVANCED || __textEngine.gridFitType != PIXEL);
> ```

We no longer use these flags then?
I seem to remember we forced one of those flags to make the text render crisp. Maybe we can remove the forcing, but still take these variables into account if they are set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/348)*

**Comment by gogoprog** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/348)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/348#-:-KvguB_ncNxeCorZTEHE:bnfp4nl)*

**Pull request merged**
