### PR TITLE
Feature/timeslice mc preprocessor

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/353)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-:-KvlQ54qh40BWSTkKDvR:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 330 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-KvlUs0Pi9WCMvtTSCNy:-KvlUs0Pi9WCMvtTSCNz:b9s9jde) ([raw file](https://github.com/fishingcactus/openfl/blob/7d0089880ec6c6f2f9b3adb6d4562bfbe5661f11/format/swf/lite/symbols/ShapeSymbol.hx#L330)):*
> ```Haxe
> 
> 	public function set_cachePrecision (value:Int):Int {
> 		if (__cachePrecision != null && __cachePrecision != value) {
> ```

Only do this in dev mode?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 25 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-KvlX12IAErEOhgzOKgS:-KvlX12IAErEOhgzOKgT:brrge1v) ([raw file](https://github.com/fishingcactus/openfl/blob/7d0089880ec6c6f2f9b3adb6d4562bfbe5661f11/format/swf/lite/symbols/ShapeSymbol.hx#L25)):*
> ```Haxe
> 	public var snapCoordinates:Bool = false;
> 
> 	static private var DefaultCachePrecision:Int = 100;
> ```

camelCase like the others?

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 330 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-KvlUs0Pi9WCMvtTSCNy:-KvlX79Pa6GOxV28_3ER:b2ngthb) ([raw file](https://github.com/fishingcactus/openfl/blob/7d0089880ec6c6f2f9b3adb6d4562bfbe5661f11/format/swf/lite/symbols/ShapeSymbol.hx#L330)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Only do this in dev mode?
</blockquote></details>

+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353)*

**Comment by rams3s** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 25 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-KvlX12IAErEOhgzOKgS:-KvldFC_OIqTEMTvdaQb:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/7d0089880ec6c6f2f9b3adb6d4562bfbe5661f11/format/swf/lite/symbols/ShapeSymbol.hx#L25)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

camelCase like the others?
</blockquote></details>

Done.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 330 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-KvlUs0Pi9WCMvtTSCNy:-KvldY7LXABl3NbHQ1SZ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/7d0089880ec6c6f2f9b3adb6d4562bfbe5661f11/format/swf/lite/symbols/ShapeSymbol.hx#L330)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/353#-:-KvlyYurO4uhlJPF5EAB:bnfp4nl)*

**Pull request merged**
