### PR TITLE
Fix/flow change

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/278)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/MovieClip.hx, line 986 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/278#-Kn_QZX_WA64YjAd3a6M:-Kn_QZXaE8uhcexKil4X:b-2k05vw) ([raw file](https://github.com/fishingcactus/openfl/blob/97d2e5499e0421a879129b463aafa1220c25e63b/format/swf/lite/MovieClip.hx#L986)):*
> ```Haxe
> 				__frameScripts.get (index) ();
> 
> 				if( ( index  + 1 ) % ( __totalFrames + 1 ) != __currentFrame){
> ```

This seems like a strange condition. I would like to see which case you fix with this.

index is zero based, while __currentFrame is one based. Putting a modulo of __totalFrames + 1 make no sense, as now the range has __totalFrames + 1

On top of it, index is warped correctly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/MovieClip.hx, line 986 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/278#-Kn_QZX_WA64YjAd3a6M:-KncOp6-6NQqCMg_7WR-:b-wu9pml) ([raw file](https://github.com/fishingcactus/openfl/blob/97d2e5499e0421a879129b463aafa1220c25e63b/format/swf/lite/MovieClip.hx#L986)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

This seems like a strange condition. I would like to see which case you fix with this.

index is zero based, while __currentFrame is one based. Putting a modulo of __totalFrames + 1 make no sense, as now the range has __totalFrames + 1

On top of it, index is warped correctly
</blockquote></details>

There's 1 flaw in this system: 

Imagine you're on the last frame of a movieclip with 30 frames:
`__renderFrame(29);`

And there's a framescript:

```
function frame30() {
    gotoAndStop(1);
}
```

The __currentFrame is expected to be 30 ( `index + 1` ) but it is now 1 because it has been explicitly set.
In this case, the function will return that a script has changed the flow, but it has not. 

Following that logic, my current implementation is also incorrect, because I'd have to warp `__currentFrame` as well. 

I think a more correct implementation would be this:

```
__currentFrame = ( index + 1 ) % __totalFrames;

if ( ( index + 1) % __totalFrames != __currentFrame ) {
```

It's very hard to tell exactly what kind of issues the old implementation can be causing but there's definitively something wrong with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/MovieClip.hx, line 986 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/278#-Kn_QZX_WA64YjAd3a6M:-KncYFjslkcsIBEK5os-:b-grtcle) ([raw file](https://github.com/fishingcactus/openfl/blob/97d2e5499e0421a879129b463aafa1220c25e63b/format/swf/lite/MovieClip.hx#L986)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

There's 1 flaw in this system: 

Imagine you're on the last frame of a movieclip with 30 frames:
`__renderFrame(29);`

And there's a framescript:

```
function frame30() {
    gotoAndStop(1);
}
```

The __currentFrame is expected to be 30 ( `index + 1` ) but it is now 1 because it has been explicitly set.
In this case, the function will return that a script has changed the flow, but it has not. 

Following that logic, my current implementation is also incorrect, because I'd have to warp `__currentFrame` as well. 

I think a more correct implementation would be this:

```
__currentFrame = ( index + 1 ) % __totalFrames;

if ( ( index + 1) % __totalFrames != __currentFrame ) {
```

It's very hard to tell exactly what kind of issues the old implementation can be causing but there's definitively something wrong with it.


</blockquote></details>

That's not true, gotoAndStop is setting target frame, and it is ignore if iwe already are in a gotoAnd

This code is never __currentFrame, it is done outside

If you don't have a specific case to fix, don't change it. I spent days ( and some with Robert ) to figure those things. If you have a case, create a test case and run them both in flash and in html. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/MovieClip.hx, line 986 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/278#-Kn_QZX_WA64YjAd3a6M:-KncZviluLT3-UKyWqxz:bbux8bj) ([raw file](https://github.com/fishingcactus/openfl/blob/97d2e5499e0421a879129b463aafa1220c25e63b/format/swf/lite/MovieClip.hx#L986)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

That's not true, gotoAndStop is setting target frame, and it is ignore if iwe already are in a gotoAnd

This code is never __currentFrame, it is done outside

If you don't have a specific case to fix, don't change it. I spent days ( and some with Robert ) to figure those things. If you have a case, create a test case and run them both in flash and in html. 

</blockquote></details>

Yes, I just realized that the check is ment for the current frame and not the next frame!
I've reverted this commit and now I only kept the `scriptHasChangedFlow` part

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Comment by crazyjul** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278#-:-Kncaaf1EEfA5Q5Tf2d5:bnfp4nl)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/278)*

**Pull request merged**
