### PR TITLE
Fix/cached bitmap smooth

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/301)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 354 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAAEgmAGdauPMcuy6N:-KrAAEgmAGdauPMcuy6O:bh1f43o) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/_internal/renderer/opengl/GLRenderer.hx#L354)):*
> ```Haxe
> 			}
> 			// simple blit. use nearest neighbor anyway
> 			if ( smooth ) {
> ```

Are we sure that source image and destination have the same size? Even if the matrix is 1/1, the bitmap cached why not be 1/1 with destination

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/301)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 228 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAH514kCpKUqKLNbOQ:-KrAH514kCpKUqKLNbOR:boeuany) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L228)):*
> ```Haxe
> 		if ( forceSmoothingValue != null ) {
> 			smoothingResult = forceSmoothingValue;
> 		}
> ```

if  `forceSmoothingValue != null`, no need to evaluate `itIsSimpleBlit` and `smoothingResult = smoothing && !itIsSimpleBlit`

---

*[openfl/display/DisplayObject.hx, line 793 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAGNHKq8n64LfoGjX-:-KrAGNHKq8n64LfoGjX0:b-8fbeyx) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/display/DisplayObject.hx#L793)):*
> ```Haxe
> 		__cacheGLMatrix.translate (__offset.x, __offset.y);
> 
> 		renderSession.spriteBatch.renderBitmapData(__cachedBitmap, __cacheAsBitmapSmooth == null ? true : __cacheAsBitmapSmooth, __cacheGLMatrix, __worldColorTransform, __worldAlpha, blendMode, __shader, NEVER, true );
> ```

if I'm not wrong this will force smoothing all the time...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/301)*

**Comment by rams3s** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/301)*

**Comment by NuclearCookie** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 354 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAAEgmAGdauPMcuy6N:-KrAKKJeS_A8EkUb2eDH:bv9hp25) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/_internal/renderer/opengl/GLRenderer.hx#L354)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Are we sure that source image and destination have the same size? Even if the matrix is 1/1, the bitmap cached why not be 1/1 with destination
</blockquote></details>

I'm not following you here. What source and destination? And how could that be? 

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 228 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAH514kCpKUqKLNbOQ:-KrAKbZBQD2MJkwWNBO9:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L228)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

if  `forceSmoothingValue != null`, no need to evaluate `itIsSimpleBlit` and `smoothingResult = smoothing && !itIsSimpleBlit`
</blockquote></details>

Done.

---

*[openfl/display/DisplayObject.hx, line 793 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAGNHKq8n64LfoGjX-:-KrAKcJZuzR6akjGFkA_:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/display/DisplayObject.hx#L793)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

if I'm not wrong this will force smoothing all the time...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/301)*

**Comment by crazyjul** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 354 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/301#-KrAAEgmAGdauPMcuy6N:-KrALOzFZYL6c3zFPRe8:boivjna) ([raw file](https://github.com/fishingcactus/openfl/blob/fe2000318cad3ce8755e9a406ba53f4fc9c9452a/openfl/_internal/renderer/opengl/GLRenderer.hx#L354)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

I'm not following you here. What source and destination? And how could that be? 
</blockquote></details>

The bitmap from the graphics does not have to be of the same size as the shape. In some case, the cached bitmap is forced to some specific size

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/301)*

**Comment by crazyjul** [comment]
Any issue with this MR?

**Comment by NuclearCookie** [comment]
No loger needed. This was not the correct solution for the bug we had. correct solution now lives in fix/renderbounds, MR will come shortly

**Pull request closed without merging**
