### PR TITLE
Feature/movieclip preprocessor job priority

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/344)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/344#-:-KvWlZgGOvWwo3i_ZGLn:bnfp4nl)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/344)*

**Comment by gogoprog** [comment]
conflicts atm

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/344#-:-KvWu0NJpS5VuO8Qn81Y:b-70q1vu)*

**Comment by rams3s** [comment]
rebased onto origin/develop

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/344#-:-KvX94xaDsmqFrvCO9GV:bhhvh79)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/344)*

**Pull request merged**
