### PR TITLE
Optimize/events

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/169)

### CODE REVIEW

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/169#-:-Kcb0Z3L4GHT8b6dB7Fi:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/geom/Transform.hx, line 92 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/169#-KcqiaG9nK0CrnltxQQP:-KcqiaG9nK0CrnltxQQQ:b-gpwu9) ([raw file](https://github.com/fishingcactus/openfl/blob/b886ecb3a16f9a30f9f4e90502529d4ee2a954dc/openfl/geom/Transform.hx#L92)):*
> ```Haxe
> 	}
> 
> 	public function get_matrix_no_clone():Matrix {
> ```

Follow naming convention

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/169)*

**Comment by crazyjul** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/169)*

**Comment by NuclearCookie** [comment]
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/geom/Transform.hx, line 92 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/169#-KcqiaG9nK0CrnltxQQP:-KcqqFK_wRyu8JVOm6EH:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/b886ecb3a16f9a30f9f4e90502529d4ee2a954dc/openfl/geom/Transform.hx#L92)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Follow naming convention
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/169)*

**Pull request merged**
