### PR TITLE
Added a poolable flag: object put in pool after removed from parent

### PR DESCRIPTION
**Pull request by gogoprog**
Useful on movie clips that intensively use create/remove child objects as particles

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/224)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Comment by NuclearCookie** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[format/swf/lite/MovieClip.hx, line 329 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-KiU2sFxU2Spy6er9TGP:-KiU2sFxU2Spy6er9TGQ:b-rw5f6r) ([raw file](https://github.com/fishingcactus/openfl/blob/6ce059cd486b448de33c6040d1c844aab6d331e4/format/swf/lite/MovieClip.hx#L329)):*
> #if profile
> 				__childrenCreateCount.set(this.__symbol.id, (__childrenCreateCount.exists(this.__symbol.id) ? __childrenCreateCount.get(this.__symbol.id) + 1 : 1));
> 				#end

This check is not correct. It should be moved out of the if;else and checked if `displayObject == null`

---

*[openfl/display/Shape.hx, line 25 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-KiU3Dw41VKVc6MWM7hz:-KiU3Dw41VKVc6MWM7i-:b-fx1dac) ([raw file](https://github.com/fishingcactus/openfl/blob/6ce059cd486b448de33c6040d1c844aab6d331e4/openfl/display/Shape.hx#L25)):*
> override public function getSymbol():format.swf.lite.symbols.SWFSymbol{
> 		return graphics.__symbol;
> 	}
Add this for morphshapes too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/MovieClip.hx, line 329 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-KiU2sFxU2Spy6er9TGP:-KiUEyZFYInbUNvbrJ0_:bi7xo01) ([raw file](https://github.com/fishingcactus/openfl/blob/6ce059cd486b448de33c6040d1c844aab6d331e4/format/swf/lite/MovieClip.hx#L329)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> #if profile
> 				__childrenCreateCount.set(this.__symbol.id, (__childrenCreateCount.exists(this.__symbol.id) ? __childrenCreateCount.get(this.__symbol.id) + 1 : 1));
> 				#end

This check is not correct. It should be moved out of the if;else and checked if `displayObject == null`
</blockquote></details>

How is it not correct? I don't get what your request will change

---

*[openfl/display/Shape.hx, line 25 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-KiU3Dw41VKVc6MWM7hz:-KiUGFap_wBNgvZQ8z8_:b-mgmhft) ([raw file](https://github.com/fishingcactus/openfl/blob/6ce059cd486b448de33c6040d1c844aab6d331e4/openfl/display/Shape.hx#L25)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> override public function getSymbol():format.swf.lite.symbols.SWFSymbol{
> 		return graphics.__symbol;
> 	}
Add this for morphshapes too
</blockquote></details>

MorphShape derives from Shape so it already has this definition

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Comment by gogoprog** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/Shape.hx, line 25 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-KiU3Dw41VKVc6MWM7hz:-KiV5JrBXb-HtnFkmygU:b-c1f1zn) ([raw file](https://github.com/fishingcactus/openfl/blob/6ce059cd486b448de33c6040d1c844aab6d331e4/openfl/display/Shape.hx#L25)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

MorphShape derives from Shape so it already has this definition
</blockquote></details>

Code updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224#-:-KiZP6vqXLswcEU9RmPQ:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/224)*

**Pull request merged**
