### PR TITLE
Added SpriteSymbol.createNeededTextures

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/310)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-:-KsI_5TebsJgbhBRryPf:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 24 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-KsJRj4FrhfuTSLxOpu3:-KsJRj4FrhfuTSLxOpu4:b-j2bbai) ([raw file](https://github.com/fishingcactus/openfl/blob/95cb4de6e0d6846ced7ea9de082f152a2671d203/format/swf/lite/symbols/SpriteSymbol.hx#L24)):*
> ```Haxe
> 
> 	public function findNeededShapesSymbolId(result:Map<Int, ShapeSymbol>, swflite:SWFLite):Void {
> 		__findNeededShapesAndCreateSimpleSpriteTextures(result, null, swflite);
> ```

Doesn't always create textures. Name implies otherwise

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 37 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-KsJRlpmDu0BDydleeFQ:-KsJRlpmDu0BDydleeFR:bch6jfc) ([raw file](https://github.com/fishingcactus/openfl/blob/95cb4de6e0d6846ced7ea9de082f152a2671d203/format/swf/lite/symbols/SpriteSymbol.hx#L37)):*
> ```Haxe
> 	}
> 
> 	private function __findNeededShapesAndCreateSimpleSpriteTextures(result:Map<Int, ShapeSymbol>, gl:GLRenderContext, swflite:SWFLite):Void {
> ```

default arguments should go in the back

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310)*

**Comment by gogoprog** [comment]
*[format/swf/lite/symbols/SpriteSymbol.hx, line 24 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-KsJRj4FrhfuTSLxOpu3:-KsJTi3MMMLlLuYgKK2v:b484l4l) ([raw file](https://github.com/fishingcactus/openfl/blob/95cb4de6e0d6846ced7ea9de082f152a2671d203/format/swf/lite/symbols/SpriteSymbol.hx#L24)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Doesn't always create textures. Name implies otherwise
</blockquote></details>

I copied the code as I could not find a good name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310)*

**Comment by gogoprog** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 24 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-KsJRj4FrhfuTSLxOpu3:-KsJTrqDe_ZMn0Y99qyu:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/95cb4de6e0d6846ced7ea9de082f152a2671d203/format/swf/lite/symbols/SpriteSymbol.hx#L24)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

I copied the code as I could not find a good name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310)*

**Comment by gogoprog** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 37 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/310#-KsJRlpmDu0BDydleeFQ:-KsJTvvSgMnf3Qp1hEsQ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/95cb4de6e0d6846ced7ea9de082f152a2671d203/format/swf/lite/symbols/SpriteSymbol.hx#L37)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

default arguments should go in the back
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/310)*

**Pull request merged**
