### PR TITLE
Feature/preprocess morphshapes

### PR DESCRIPTION
**Pull request by gogoprog**
This also fixes missing cache!

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/357)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 166 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/357#-Kw531z6bzVJA1Ac3P9I:-Kw531z6bzVJA1Ac3P9J:bvhd4sy) ([raw file](https://github.com/fishingcactus/openfl/blob/b5875510da7d9ff4823089e3096c672908fb8478/openfl/utils/MovieClipPreprocessor.hx#L166)):*
> !childRenderTransform.equals (idTransformMap[frameObject.id])

With this code, will we not have issues?
I think we might generate duplicates with it.
What if an object has the same transform on frame 1 and 3, but not on frame 2.
When evaulating frame 3, you will compare against the transform of frame 2. 
Shouldn't we keep a map of transforms for this ID ?  ( as done for the ratios )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by gogoprog** [comment]
*[openfl/utils/MovieClipPreprocessor.hx, line 166 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/357#-Kw531z6bzVJA1Ac3P9I:-Kw54q9mMFHVXpmeH2OM:b9wf7hk) ([raw file](https://github.com/fishingcactus/openfl/blob/b5875510da7d9ff4823089e3096c672908fb8478/openfl/utils/MovieClipPreprocessor.hx#L166)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> !childRenderTransform.equals (idTransformMap[frameObject.id])

With this code, will we not have issues?
I think we might generate duplicates with it.
What if an object has the same transform on frame 1 and 3, but not on frame 2.
When evaulating frame 3, you will compare against the transform of frame 2. 
Shouldn't we keep a map of transforms for this ID ?  ( as done for the ratios )
</blockquote></details>

Indeed this is wrong, I'm reworking this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by rams3s** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 194 at r6](https://reviewable.io:443/reviews/fishingcactus/openfl/357#-KwAV7bROre1kK_eqb91:-KwAV7bROre1kK_eqb92:b2tkc55) ([raw file](https://github.com/fishingcactus/openfl/blob/8e8b23ec2c67b03edb384323f3b195c3f2753fe6/openfl/utils/MovieClipPreprocessor.hx#L194)):*
>                idTransformMap[frameObject.id].copyFrom(localTransform.clone ());
>                 idRenderTransformMap[frameObject.id].copyFrom(childRenderTransform.clone ());
>    
no need to clone for copyFrom

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/357)*

**Pull request merged**
