### PR TITLE
Snap canvas coordinates after transform

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/225)

### CODE REVIEW

**Comment by gogoprog** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/geom/Matrix.hx, line 58 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/225#-KiTz5jboCTH3Ih9jNMv:-KiTz5jboCTH3Ih9jNMw:b-8oen3u) ([raw file](https://github.com/fishingcactus/openfl/blob/ea3d7af430159d683ae219d6f6c78ba625b0c73a/openfl/geom/Matrix.hx#L58)):*
> ```Haxe
> 
> 
> 		//__cleanValues ();
> ```

commented?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by NuclearCookie** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 271 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/225#-KiU42eFckD1XXO0-QGA:-KiU42eFckD1XXO0-QGB:b-bjsaw) ([raw file](https://github.com/fishingcactus/openfl/blob/ea3d7af430159d683ae219d6f6c78ba625b0c73a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L271)):*
> The CanvasRenderingContext2D.setTransform() method of the Canvas 2D API resets (overrides) the current transformation to the identity matrix and then invokes a transformation described by the arguments of this method.

There is `ctx.resetTransform();` which might be a bit more efficient than`setTransform(identity)`. 

---

*[openfl/geom/Matrix.hx, line 58 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/225#-KiTz5jboCTH3Ih9jNMv:-KiU5OOn0bZicQ1_OD0v:bdacid4) ([raw file](https://github.com/fishingcactus/openfl/blob/ea3d7af430159d683ae219d6f6c78ba625b0c73a/openfl/geom/Matrix.hx#L58)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

commented?
</blockquote></details>

commented in all other transform functions too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 271 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/225#-KiU42eFckD1XXO0-QGA:-KiUADYLHrUkoA0FReB9:bq1trfn) ([raw file](https://github.com/fishingcactus/openfl/blob/ea3d7af430159d683ae219d6f6c78ba625b0c73a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L271)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> The CanvasRenderingContext2D.setTransform() method of the Canvas 2D API resets (overrides) the current transformation to the identity matrix and then invokes a transformation described by the arguments of this method.

There is `ctx.resetTransform();` which might be a bit more efficient than`setTransform(identity)`. 
</blockquote></details>

Unfortunately still experimental

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225#-:-KiUCLt_7rFCM2uZgOw4:bnfp4nl)*

**Comment by gogoprog** [comment]
Reviewed 2 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by crazyjul** [comment]
Reviewed 4 of 5 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by NuclearCookie** [comment]
Reviewed 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by gogoprog** [comment]
Reviewed 5 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/225)*

**Pull request merged**
