### PR TITLE
Hack alpha handling for timeline

### PR DESCRIPTION
**Pull request by crazyjul**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/402)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Why is it called hack? :)

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/fishingcactus/openfl/402#-:-L4LX6JZCBSChaLJ8AOC:bcka1yw)*

**Comment by crazyjul** [comment]
Cause it's not the right way to do it.

The right way was discussed and rejected previously

**Comment by rams3s** [comment]
Can you explain what's wrong with this implementation?

Compared to the PR#400, I prefer this one because the other one had the following (solvable) issues:
- cached bitmaps would not be rendered at full opacity anymore (__renderAlpha attribute)
  - need to rerender the bitmap when changing alpha (more costly and hard to maintain with our caches at symbol level)
  -  if not handled properly this might result in squared alpha as was the case before the introduction of __renderAlpha vs __worldAlpha
- potentially worse batching because changing alpha would result in different render states (especially for particles)

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/402#-:-L4LdvOzVbXReUBQ7PJL:b-ct7zdo)*

**Comment by rams3s** [comment]
After further discussion with Gauthier, it looks like the first issue (cached bitmaps would not be rendered at full opacity anymore) was properly handled in PR#400.

If the batching issue of PR#400 can be fixed, for me boths PRs are ok to be merged.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/402#-:-L4MTUePhB8Qhs4cxRuJ:b-w5b605)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/402#-:-L4_geUwcqHItZFvdrkQ:bnfp4nl)*

**Pull request merged**
