### PR TITLE
Save morphshape symbol in graphics. This simplifies some logic and al…

### PR DESCRIPTION
**Pull request by NuclearCookie**
…lows for easier profiling

This makes it consistent to shapes

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/311)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/311)*

**Comment by rams3s** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/Graphics.hx, line 96 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/311#-KsNC8tWzU0Thf6CstkM:-KsNC8tWzU0Thf6CstkN:bjn1y2z) ([raw file](https://github.com/fishingcactus/openfl/blob/db59e270d41db1f2b51ba77dc639574c222a288c/openfl/display/Graphics.hx#L96)):*
> ```Haxe
> 	}
> 
> 	public function processCommands(shapeCommands:Array<ShapeCommand>) {
> ```

As we are filling the graphics with `ShapeCommand`s, I would prefer to keep it outside `Graphics` class. Maybe keep the one in `ShapeSymbol` and make it static?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/311)*

**Comment by NuclearCookie** [comment]
Review status: 1 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Graphics.hx, line 96 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/311#-KsNC8tWzU0Thf6CstkM:-KsNJRnZHvY22x2p01ib:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/db59e270d41db1f2b51ba77dc639574c222a288c/openfl/display/Graphics.hx#L96)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

As we are filling the graphics with `ShapeCommand`s, I would prefer to keep it outside `Graphics` class. Maybe keep the one in `ShapeSymbol` and make it static?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/311)*

**Comment by rams3s** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/311)*

**Pull request merged**
