### PR TITLE
Feature/screenshot utils

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/359)

### CODE REVIEW

**Comment by gogoprog** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 756 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/359#-KwFGD7PzwvnqmGEHdGy:-KwFGD7QqYVapACqOfWe:b40x8fd) ([raw file](https://github.com/fishingcactus/openfl/blob/a5f02650a43cc4d7ba34f3c34ed590fea17ce24a/openfl/display/DisplayObject.hx#L756)):*
> ```Haxe
> 		__getRenderBounds (cachedBitmapBounds);
> 
> 		if (cachedBitmapBounds.width <= 0 && cachedBitmapBounds.height <= 0) {
> ```

don't you want `||` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/359)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/359)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 756 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/359#-KwFGD7PzwvnqmGEHdGy:-KwFi6pzwPgu9OYbQKEX:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/a5f02650a43cc4d7ba34f3c34ed590fea17ce24a/openfl/display/DisplayObject.hx#L756)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

don't you want `||` here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/359)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/359#-:-KwJaJGI6tBCFAz8V3P1:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/359)*

**Pull request merged**
