### PR TITLE
Removed unused templates. Rely on the resolve method for accessing ch…

### PR DESCRIPTION
**Pull request by NuclearCookie**
The reason for this change is to support children that start with a $ sign for example. Invalid fields in haxe, but still resolvable through string

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/239)

### CODE REVIEW

**Comment by crazyjul** [comment]
Are you using the template for something. I remember having issue with them

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/239#-:-KjnHlj0PVkr3E_k4as7:b-1hnov0)*

**Comment by gogoprog** [comment]
Where is this template used?

---

Reviewed 2 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/239#-:-Kjrfe3_0XtFR4mn3Xqw:b-wf7xve)*

**Comment by NuclearCookie** [comment]
So, this is used if you specify `generate=true` on the library to process. It will generate a haxe class for each symbol defined in the .swf file. 

By default `generate` is false so we don't use this.

**Comment by crazyjul** [comment]
I tried to use it, but it only works if you  instantiate from code. On the other hand, don't remove it, it's used in the pigeon game 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/239#-:-KkATweGnOLzrVWAETY7:b-ks99v4)*

**Comment by NuclearCookie** [comment]
I think this code is still correct, even though we don't use it right now, this should still be merged

**Pull request merged**
