### PR TITLE
Fix/simple sprite snapping

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/335)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/335)*

**Comment by rams3s** [comment]
Reviewed 6 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 333 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/335#-KuZUnubhp8_a8OxIhOi:-KuZUnubhp8_a8OxIhOj:b-mfwthl) ([raw file](https://github.com/fishingcactus/openfl/blob/04abda2bf39dd2be2a90b610075442e97eebf84a/openfl/_internal/renderer/opengl/GLRenderer.hx#L333)):*
> ```Haxe
> 		} else if ( renderSession.roundPixels == false ) {
> 			round_pixels = PixelSnapping.NEVER;
> 		}
> ```

var round_pixels = renderSession.roundPixels != null ? renderSession.roundPixels : PixelSnapping.AUTO;

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/335)*

**Comment by gogoprog** [comment]
Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[format/swf/lite/symbols/SimpleSpriteSymbol.hx, line 14 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/335#-KuZf9ldesTRf5tujKg6:-KuZf9ldesTRf5tujKg7:bts2lms) ([raw file](https://github.com/fishingcactus/openfl/blob/04abda2bf39dd2be2a90b610075442e97eebf84a/format/swf/lite/symbols/SimpleSpriteSymbol.hx#L14)):*
> ```Haxe
> 	@:s public var matrix:Matrix;
> 	@:s public var bounds:Rectangle;
> 	@:s public var smooth:Bool;
> ```

Null<Bool> I guess

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/335)*

**Comment by rams3s** [comment]
Review status: 6 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/symbols/SimpleSpriteSymbol.hx, line 14 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/335#-KuZf9ldesTRf5tujKg6:-Ku_252AcDIRg4G5z3i-:b-m7xkun) ([raw file](https://github.com/fishingcactus/openfl/blob/04abda2bf39dd2be2a90b610075442e97eebf84a/format/swf/lite/symbols/SimpleSpriteSymbol.hx#L14)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Null<Bool> I guess
</blockquote></details>

Filled by exporter

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 333 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/335#-KuZUnubhp8_a8OxIhOi:-Ku_2SG6DDIhXRc8kXoL:b9w7fma) ([raw file](https://github.com/fishingcactus/openfl/blob/04abda2bf39dd2be2a90b610075442e97eebf84a/openfl/_internal/renderer/opengl/GLRenderer.hx#L333)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

var round_pixels = renderSession.roundPixels != null ? renderSession.roundPixels : PixelSnapping.AUTO;
</blockquote></details>

Code removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/335)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/335#-:-KudwNTeivuinf3JkveE:bnfp4nl)*

**Pull request merged**
