### PR TITLE
Feature/avoid update

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/179)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 880 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5v_LwveBOdRQ6mPpI:-Kd5v_LwveBOdRQ6mPpJ:bqoyva4) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/DisplayObject.hx#L880)):*
> ```Haxe
> 	}
> 
> 	public inline function __inlineUpdate(transformOnly:Bool, updateChildren:Bool):Void {
> ```

I'm not fan of this, is the function call so expensive? Bigger function are usually not optimized in vms

---

*[openfl/display/Stage.hx, line 1439 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5vwsMfCym8ozadUMr:-Kd5vwsNWNA02VZ7a1gm:b-8nnkkx) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/Stage.hx#L1439)):*
> ```Haxe
> 			__inlineUpdate(transformOnly, updateChildren);
> 			var i = 0;
> 			var cached_length = __updateStack.length;
> ```

Not used

---

*[openfl/display/Stage.hx, line 1443 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5w7icKx1Msdg1GskV:-Kd5w7icKx1Msdg1GskW:b-anojbw) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/Stage.hx#L1443)):*
> ```Haxe
> 			while (i < __updateStack.length ) {
> 				var child = __updateStack[i];
> 				if ( child.__updateDirty ) {
> ```

Child can be affected by a change in the parent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/179)*

**Comment by NuclearCookie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 880 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5v_LwveBOdRQ6mPpI:-Kd6--hS8jJJgLM3XZhC:b5be6oh) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/DisplayObject.hx#L880)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I'm not fan of this, is the function call so expensive? Bigger function are usually not optimized in vms
</blockquote></details>

No it' not. Having this just enables me to call the code that's inside the DisplayObject.__update, from the Stage.__update. ( And skipping DisplayObjectContainer.__update ).

---

*[openfl/display/Stage.hx, line 1443 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5w7icKx1Msdg1GskV:-Kd6-T-xVAGc1h1CXCVz:b-553kg7) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/Stage.hx#L1443)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Child can be affected by a change in the parent
</blockquote></details>

No problem. This is the start of a branch that needs to be updated. All children of this entry point will be updated. 
This check is here to avoid updating the same object twice. ( parent and child both in the tree )

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/179)*

**Comment by NuclearCookie** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/Stage.hx, line 1439 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/179#-Kd5vwsMfCym8ozadUMr:-Kd6-k5BuVUsSNk1l1SC:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/21b7f4195a8147846766165021b841e81fc45602/openfl/display/Stage.hx#L1439)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Not used
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/179)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/179)*

**Pull request merged**
