### PR TITLE
Cleanup intermediate textures for cached bitmaps

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/304)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Graphics.hx, line 733 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/304#-KrjX12C7JuLwXDvp5kv:-KrjX12DfTBqH368qxQB:bhiruly) ([raw file](https://github.com/fishingcactus/openfl/blob/d25eac0467ea8de201257c2eb597c50b00eac7f7/openfl/display/Graphics.hx#L733)):*
> ```Haxe
> 	private inline function __disposeBitmap():Void {
> 		__bitmap = null;
> 		__dirty = true;
> ```

done in calling function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/304)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Graphics.hx, line 733 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/304#-KrjX12C7JuLwXDvp5kv:-KrjYF2tsa28BOe1_vpm:b-76kf1x) ([raw file](https://github.com/fishingcactus/openfl/blob/d25eac0467ea8de201257c2eb597c50b00eac7f7/openfl/display/Graphics.hx#L733)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

done in calling function
</blockquote></details>

No, note the __dirty instead of dirty.
set_dirty will call set_renderDirty which will invalidate the cached bitmap and regenerate the graphics.
In this case we only want to flag the graphics as __dirty, not the owners.
I'm considering to make this the default behavior on graphic disposal but I wanted to keep the existing behavior for now.. feedback welcome

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/304)*

**Comment by rams3s** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/304)*

**Comment by gogoprog** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/304)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/304)*

**Pull request merged**
