### PR TITLE
Fix/remove gap graphics

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/388)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/data/SWFShape.hx, line 471 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XWZeo0gAQa_T7LE_V:-L1XWZeo0gAQa_T7LE_W:b-7ne4oc) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L471)):*
> ```Haxe
> 		var path:Array<Edge> = createPathFromEdgeMap(subLineEdgeMaps[groupIndex]);
> 		var pos:Point = new Point(SWFData.MAX_FLOAT_VALUE, SWFData.MAX_FLOAT_VALUE);
> 		//var lineStyleIdx:Int = uint.MAX_VALUE;
> ```

commented code

---

*[format/swf/data/SWFShape.hx, line 482 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XWm7_pQuR4Th15d5x:-L1XWm7_pQuR4Th15d5y:b-5wf3hf) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L482)):*
> ```Haxe
> 					pos = new Point(SWFData.MAX_FLOAT_VALUE, SWFData.MAX_FLOAT_VALUE);
> 					try {
> 						lineStyle = subLineStyles[subLineStyleIdx - 1];
> ```

why not using a if?

---

*[format/swf/data/SWFShape.hx, line 596 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XX8_42kIC0oVaW9vl:-L1XX8_42kIC0oVaW9vm:bk9d5fh) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L596)):*
> ```Haxe
> 				}
> 			}
> 			handler.lineStyle(
> ```

This will be executed all the time, erasing previous calls

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*

**Comment by crazyjul** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[format/swf/data/SWFShape.hx, line 482 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XWm7_pQuR4Th15d5x:-L1X_KcYAWkge20iCL0c:b597tkj) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L482)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

why not using a if?
</blockquote></details>

it's a plain copy paste. Didn't check that. Will change :)

---

*[format/swf/data/SWFShape.hx, line 596 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XX8_42kIC0oVaW9vl:-L1X_Ra7_xQatUWQEnW_:b-r2kt26) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L596)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

This will be executed all the time, erasing previous calls
</blockquote></details>

Good catch thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*

**Comment by gogoprog** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*

**Comment by rams3s** [comment]
Reviewed 12 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format/swf/data/SWFShape.hx, line 328 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rqwS81cehqGm1N65R:-L1rqwS81cehqGm1N65S:b-2ny414) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/format/swf/data/SWFShape.hx#L328)):*
> ```Haxe
> 		// :NOTE: Draw a stroke under the path when there
> 		// are 2 fill styles to avoid transparent gaps between 2 shapes.
> 		if (fillStyleIdx0 != 0 && fillStyleIdx1 != 0) {
> ```

no need to check that none of the 2 fill styles is transparent?

---

*[format/swf/data/SWFShape.hx, line 331 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rqD5WvZBSu4Mk4EG5:-L1rqD5WvZBSu4Mk4EG6:b-xh1w5v) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/format/swf/data/SWFShape.hx#L331)):*
> ```Haxe
> 			var sub_line_style_idx = subLineStyles.length + 1;
> 			currentSubLineEdgeMap.set (sub_line_style_idx, new Array<Edge>());
> 			path = currentSubLineEdgeMap.get (sub_line_style_idx);
> ```

I understand it's a copy from existing code but would be cleaner like this:
```path = new Array<Edge>();
currentSubLineEdgeMap.set (sub_line_style_idx, path);```
```


---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 261 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rt6fBusJNKYhbMuhd:-L1rt6fBusJNKYhbMuhe:b-u9egy3) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L261)):*
> ```Haxe
> 				// :NOTE: linewidth is scaled with the transform. Counteract this scaling.
> 				// This does not work if the scale is non uniform!
> 				if ( pending_matrix != null && pending_matrix.a == pending_matrix.d ) {
> ```

could help to throw if non uniform scale in dev mode

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[format/swf/data/SWFShape.hx, line 471 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XWZeo0gAQa_T7LE_V:-L1pxs0h3mVKzWKd1c5-:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L471)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

commented code
</blockquote></details>

Done.

---

*[format/swf/data/SWFShape.hx, line 482 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1XWm7_pQuR4Th15d5x:-L1pxsfAnwe6DVkl9Z9O:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/db24d74c7540963a5a0a08453e9a447ffe6073d7/format/swf/data/SWFShape.hx#L482)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

it's a plain copy paste. Didn't check that. Will change :)
</blockquote></details>

Done.

---

*[format/swf/data/SWFShape.hx, line 328 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rqwS81cehqGm1N65R:-L1vA3WgToXlYinDQbey:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/format/swf/data/SWFShape.hx#L328)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

no need to check that none of the 2 fill styles is transparent?
</blockquote></details>

Done.

---

*[format/swf/data/SWFShape.hx, line 331 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rqD5WvZBSu4Mk4EG5:-L1vAXXOJdBDjVa7R9XU:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/format/swf/data/SWFShape.hx#L331)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

I understand it's a copy from existing code but would be cleaner like this:
```path = new Array<Edge>();
currentSubLineEdgeMap.set (sub_line_style_idx, path);```

</blockquote></details>

Done.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 261 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-L1rt6fBusJNKYhbMuhd:-L1vDhMHYiK0sXieq4QP:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/ab185c634d2dbeab5036499ac582b0149881958a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L261)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

could help to throw if non uniform scale in dev mode
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388)*
<!-- Sent from Reviewable.io -->

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/388#-:-L1vbQQ9HCVcmMhL7h3g:bnfp4nl)*

**Pull request merged**
