### PR TITLE
Feature shader parameter float32array

### PR DESCRIPTION
**Pull request by gogoprog**
This PR reduces Float32Array instanciations when passing to the shader.

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/96)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 24 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[format/swf/data/filters/FilterColorMatrix.hx, line 37 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/96#-KXpd_3R6sCJeza2JRg1:-KXpd_3R6sCJeza2JRg2:b-ddxaso) ([raw file](https://github.com/fishingcactus/openfl/blob/126930f3a614d3a07a69261d832eea2a8899f07a/format/swf/data/filters/FilterColorMatrix.hx#L37)):*
> ```Haxe
> 		}
> 
> 		multipliers = new Float32ArrayContainer(new Float32Array([ colorMatrix[0], colorMatrix[1], colorMatrix[2], colorMatrix[3], colorMatrix[5], colorMatrix[6], colorMatrix[7], colorMatrix[8], colorMatrix[10], colorMatrix[11], colorMatrix[12], colorMatrix[13], colorMatrix[15], colorMatrix[16], colorMatrix[17], colorMatrix[18] ]));
> ```

Is there a reason to create another array for Float32Array contruction?

Normally, new Float32Array( colorMatrix ) should work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/96)*

**Comment by crazyjul** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/96)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[format/swf/data/filters/FilterColorMatrix.hx, line 37 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/96#-KXpd_3R6sCJeza2JRg1:-KXtNK588CmPyoQZ_Hjt:bdk1yd5) ([raw file](https://github.com/fishingcactus/openfl/blob/126930f3a614d3a07a69261d832eea2a8899f07a/format/swf/data/filters/FilterColorMatrix.hx#L37)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Is there a reason to create another array for Float32Array contruction?

Normally, new Float32Array( colorMatrix ) should work
</blockquote></details>

This is not the complete colorMatrix (take a look at indices 4, 9, 14 and 19 which are not part of this)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/96)*

**Comment by crazyjul** [comment]
Reviewed 1 of 24 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/96)*

**Pull request merged**
