### PR TITLE
Cache currently enabled vertex array

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/131)

### CODE REVIEW

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/shaders2/Shader.hx, line 43 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/131#-KaGl7MdqHvC500EBCG5:-KaGl7MdqHvC500EBCG6:b-z81zjh) ([raw file](https://github.com/fishingcactus/openfl/blob/b0a5c7df2753010e84569b8922109b5c991dbcd0/openfl/_internal/renderer/opengl/shaders2/Shader.hx#L43)):*
> ```Haxe
> 	private var vertexString:String;
> 	private var fragmentString:String;
> 	private var currentVertexArray:VertexArray;
> ```

Shouldn't this variable be static?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/131)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/131)*

**Comment by gogoprog** [comment]
lgtm

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/shaders2/Shader.hx, line 43 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/131#-KaGl7MdqHvC500EBCG5:-KaH7FA5IKCOcXOxzqeF:bmfj5al) ([raw file](https://github.com/fishingcactus/openfl/blob/b0a5c7df2753010e84569b8922109b5c991dbcd0/openfl/_internal/renderer/opengl/shaders2/Shader.hx#L43)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Shouldn't this variable be static?
</blockquote></details>

True... Thought it was per program...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/131)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/shaders2/Shader.hx, line 43 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/131#-KaGl7MdqHvC500EBCG5:-KaH8Vx-KiY9dICyX5tg:b3k4wpd) ([raw file](https://github.com/fishingcactus/openfl/blob/b0a5c7df2753010e84569b8922109b5c991dbcd0/openfl/_internal/renderer/opengl/shaders2/Shader.hx#L43)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

True... Thought it was per program...
</blockquote></details>

It's opengl, so everything is global, as usual

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/131)*

**Review by crazyjul — APPROVED** [review]

**Pull request merged**
