### PR TITLE
Outer knockout should hide inner shape regardless of its opacity

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/57)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[openfl/filters/commands/KnockoutCommand.hx, line 33 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/57#-KTTD0cxo-tsT0KTer5Y:-KTTD0cyayOy7vn05Utf:b8zewb3) ([raw file](https://github.com/fishingcactus/openfl/blob/532a009109443fd8ef15d1ac080ef39d0c328f4c/openfl/filters/commands/KnockoutCommand.hx#L33)):_

> ``` Haxe
>           'vec4 src2 = texture2D(${Shader.uSampler}, ${Shader.vTexCoord});',
>           'vec4 src1 = texture2D(uSource1Sampler, ${Shader.vTexCoord});', // target image
>           'src2 *= ( outer * 2.0 - 1.0 ) * ( outer - ( outer * step(0.0001, src1.a) + ( 1. - outer ) * src1.a ) );',
> ```

This becomes too complicated

Split this in 2 commands OuterKnockout and InnerKnockout

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/57)_

**Comment by NuclearCookie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[openfl/filters/commands/InnerKnockoutCommand.hx, line 33 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/57#-KTTD0cxo-tsT0KTer5Y:-KTTNT_Qy-JSsDkHjFYR:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/532a009109443fd8ef15d1ac080ef39d0c328f4c/openfl/filters/commands/InnerKnockoutCommand.hx#L33)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> This becomes too complicated
> 
> Split this in 2 commands OuterKnockout and InnerKnockout
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/57)_

**Comment by crazyjul** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/57)_

**Comment by crazyjul** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/57#-:-KTp2ToV0Z5lOjTH5EqE:bnfp4nl)_

**Pull request merged**
