### PR TITLE
Fix/renderbounds

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/305)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 736 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/305#-Ks2ahi5Pmv5ZDE00sIl:-Ks2ahi5Pmv5ZDE00sIm:b-ubcxml) ([raw file](https://github.com/fishingcactus/openfl/blob/c8dedc6c06203ab36166626fdc1b9118d848ed15/openfl/display/DisplayObject.hx#L736)):*
> ```Haxe
> 
> 		__getRenderBounds (__cachedBitmapBounds);
> 		var renderToLocal = Matrix.__temp;
> ```

I prefer a matrix from the pool. It's safer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/305#-:-Ks2b0IVR1HSWixEaUJZ:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 12 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/305)*

**Comment by NuclearCookie** [comment]
Won't merge. Has issues with padding > 1!
[ EDIT ] It's fine! But we manually have to take padding into account in tools like spritesheet exporter.

**Comment by gogoprog** [comment]
Reviewed 13 of 13 files at r1.
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/305)*

**Pull request merged**
