### PR TITLE
Feature/clean profile

### PR DESCRIPTION
**Pull request by gogoprog**
Clean Profile interface

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/370)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/370#-:-KxgNxae4G4QuND30yNY:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/370)*

**Comment by rams3s** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/370)*

**Comment by gogoprog** [comment]
Updated. Can you take a look?

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/370#-:-L5F-E3fBhmralXPmDGO:bnfp4nl)*

**Pull request merged**
