### PR TITLE
implemented knockout effect for shadow and glow filter

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/39)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

_[openfl/filters/commands/KnockoutCommand.hx, line 33 [r1]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQuo3f4D9FJ_K0eRfdm:-KQuo3f4D9FJ_K0eRfdn:bwqk9id) ([raw file](https://github.com/fishingcactus/openfl/blob/22e1cd1b619b63032d2a99e5a9542096872d4cdd/openfl/filters/commands/KnockoutCommand.hx#L33)):_

> ``` Haxe
>           'vec4 src1 = texture2D(uSource1Sampler, ${Shader.vTexCoord});',
>           'if (inner == 0) {',
>               'src1 *= src2.a;',
> ```

No test in shader, use step

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by crazyjul** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by crazyjul** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

_[openfl/filters/DropShadowFilter.hx, line 95 [r2]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQyNqQ_SMSaVBdsbOJ-:-KQyNqQac0fNBvBaqJMd:b7510vt) ([raw file](https://github.com/fishingcactus/openfl/blob/2df1fb507314075331c79fe9c5f9fff37466e0c8/openfl/filters/DropShadowFilter.hx#L95)):_

> if (hideObject || knockout) {
> 
> ```
>       commands.push (Knockout(bitmap,__shadowBitmapData, __shadowBitmapData, !inner));
> 
>   }
>   else if (inner) {
> ```
> 
>  
>           commands.push (CombineInner (bitmap, bitmap, __shadowBitmapData));
> 
>   }

Not sure about source1 and source2 here. I think source1 should be bitmap as the other Combine\* commands.

From what I see in AnimateCC, the behavior should be the following:
- inner + hideObject == inner + knockout
- outer + hideObject should show the whole shadow
- outer + knockout should show the shadow minus the original shape

---

_[openfl/filters/GlowFilter.hx, line 82 [r2]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQyPwmLT757a2kTPQrh:-KQyPwmLT757a2kTPQri:b49g3tx) ([raw file](https://github.com/fishingcactus/openfl/blob/2df1fb507314075331c79fe9c5f9fff37466e0c8/openfl/filters/GlowFilter.hx#L82)):_

> ``` Haxe
>       if (knockout) {
> 
>           commands.push (Knockout(bitmap, __glowBitmapData, __glowBitmapData, !inner));
> ```

Same as above. Not sure about source1 and source2 here. I think source1 should be bitmap as the other Combine\* commands.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by NuclearCookie** [comment]
glow
Aside from premultiplication on the right side, the effects look the same to me

**Comment by NuclearCookie** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 95 [r2]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQyNqQ_SMSaVBdsbOJ-:-KQypXa2c07dDMGkXZDO:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/2df1fb507314075331c79fe9c5f9fff37466e0c8/openfl/filters/DropShadowFilter.hx#L95)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> > if (hideObject || knockout) {
> > 
> > ```
> >         commands.push (Knockout(bitmap,__shadowBitmapData, __shadowBitmapData, !inner));
> > 
> >     }
> >     else if (inner) {
> > ```
> > 
> >  
> >             commands.push (CombineInner (bitmap, bitmap, __shadowBitmapData));
> > 
> > ```
> > }
> > ```
> 
> Not sure about source1 and source2 here. I think source1 should be bitmap as the other Combine\* commands.
> 
> From what I see in AnimateCC, the behavior should be the following:
> - inner + hideObject == inner + knockout
> - outer + hideObject should show the whole shadow
> - outer + knockout should show the shadow minus the original shape
>   </details>
>   Done.

---

_[openfl/filters/GlowFilter.hx, line 82 [r2]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQyPwmLT757a2kTPQrh:-KQypUbcZxl02n79ogYw:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/2df1fb507314075331c79fe9c5f9fff37466e0c8/openfl/filters/GlowFilter.hx#L82)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> Same as above. Not sure about source1 and source2 here. I think source1 should be bitmap as the other Combine\* commands.
> </details>
> Done.

---

_[openfl/filters/commands/KnockoutCommand.hx, line 33 [r1]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KQuo3f4D9FJ_K0eRfdm:-KQypW6HnoHpBygrGy8X:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/22e1cd1b619b63032d2a99e5a9542096872d4cdd/openfl/filters/commands/KnockoutCommand.hx#L33)):_
<details><summary>

<i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary>



> No test in shader, use step
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by crazyjul** [comment]
Reviewed 5 of 6 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by crazyjul** [comment]
@rams3s, you can merge if it's ok for you

---

Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-:-KR2YF45SFxLaMHfJpHQ:btmnbd3)_

**Comment by crazyjul** [comment]
Reviewed 1 of 6 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 94 [r3]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR3cmrDAeu9DV_LFtDK:-KR3cmrEETI1JvuuSPya:b3zh4e3) ([raw file](https://github.com/fishingcactus/openfl/blob/2373c2f433be6f382cca26746dd39aae73346e81/openfl/filters/DropShadowFilter.hx#L94)):_

> ``` Haxe
> 
>       if ( hideObject && !knockout && !inner ) {
>           commands.push (Overwrite(bitmap, __shadowBitmapData ));
> ```

IMHO Overwrite command is not necessary. You can achieve the same by changing the destination of the last command

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by NuclearCookie** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 94 [r3]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR3cmrDAeu9DV_LFtDK:-KR3g2Y3GWfq5-SFkcqp:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/2373c2f433be6f382cca26746dd39aae73346e81/openfl/filters/DropShadowFilter.hx#L94)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> IMHO Overwrite command is not necessary. You can achieve the same by changing the destination of the last command
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 95 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR3kvViQefW876V81CY:-KR3kvViQefW876V81CZ:btnzrtu) ([raw file](https://github.com/fishingcactus/openfl/blob/6461d6a7851a794dfa5cda55c2a100cbc0d01518/openfl/filters/DropShadowFilter.hx#L95)):_

> ``` Haxe
>       if ( hideObject && !knockout && !inner ) {
> 
>           commands.push (Combine (bitmap, __shadowBitmapData, __shadowBitmapData ));
> ```

You could set the target of the Colorize command to bitmap and save that last step

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Reviewed 3 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 93 [r5]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR7eO9EhAlDMX-ybvsq:-KR7eO9EhAlDMX-ybvsr:b-nhabpk) ([raw file](https://github.com/fishingcactus/openfl/blob/552999b28c255be5b3fe77bd1144c6de60df2c9e/openfl/filters/DropShadowFilter.hx#L93)):_

> ``` Haxe
>       if ( hideObject && !knockout && !inner ) {
> 
>           commands.push (Colorize (bitmap, __shadowBitmapData, color, alpha));
> ```

This should be the last command. Either set a flag to prevent adding the last Combine or return commands here.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by NuclearCookie** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

_[openfl/filters/DropShadowFilter.hx, line 95 [r4]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR3kvViQefW876V81CY:-KR7jIlF14SYCnjyKwZQ:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6461d6a7851a794dfa5cda55c2a100cbc0d01518/openfl/filters/DropShadowFilter.hx#L95)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> You could set the target of the Colorize command to bitmap and save that last step
> </details>
> Done.

---

_[openfl/filters/DropShadowFilter.hx, line 93 [r5]](https://reviewable.io:443/reviews/fishingcactus/openfl/39#-KR7eO9EhAlDMX-ybvsq:-KR7jITOBWtVsBMNmBzu:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/552999b28c255be5b3fe77bd1144c6de60df2c9e/openfl/filters/DropShadowFilter.hx#L93)):_
<details><summary>

<i>Previously, rams3s wrote…</i></summary>



> This should be the last command. Either set a flag to prevent adding the last Combine or return commands here.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/39)_

**Pull request merged**
