### PR TITLE
added pool in colortransform

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/121)

### CODE REVIEW

**Comment by gogoprog** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 207 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/121#-K_8zKkn4jy54kkWyddk:-K_8zKkn4jy54kkWyddl:bx0de41) ([raw file](https://github.com/fishingcactus/openfl/blob/041b3cd475f5c832ca84dddd340ba45326b38af1/openfl/_internal/renderer/opengl/GLBitmap.hx#L207)):*
> ```Haxe
> 		spritebatch.finish ();
> 
> 		ColorTransform.pool.put(new_color_transform);
> ```

This reference is passed to 'source.__worldColorTransform'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/121)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLBitmap.hx, line 207 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/121#-K_8zKkn4jy54kkWyddk:-K_9-6YQlgrUlnqh5rxl:bqnst3w) ([raw file](https://github.com/fishingcactus/openfl/blob/041b3cd475f5c832ca84dddd340ba45326b38af1/openfl/_internal/renderer/opengl/GLBitmap.hx#L207)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

This reference is passed to 'source.__worldColorTransform'
</blockquote></details>

The source.__worldColorTransform is ctCache at this point. It's passed temporarily to __worldColorTransform but overwritten afterwards

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/121)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/121#-:-K_9-l4WVIDObWD4W4X6:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/121)*

**Pull request merged**
