### PR TITLE
Added Tools.viewBitmapData(bitmapData)

### PR DESCRIPTION
**Pull request by gogoprog**
This depends on Jquery-ui, see https://github.com/FishingCactus/lime/pull/25

Just break in the generated js code and call 'Tools.viewBitmapData(yourBitmapData);'

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/248)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/248#-:-KkGHjVHWYgtoHd-BAgt:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/248)*

**Comment by crazyjul** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/248#-:-KkGJSOQr15P4zUzKXoA:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/248)*

**Pull request merged**
