### PR TITLE
Fix Morph shape offset when style changes was missing in the end list

### PR DESCRIPTION
**Pull request by crazyjul**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/393)

### CODE REVIEW

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/393#-:-L2ZEsCZ_1RjWKp0Vh35:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/393)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[format/swf/lite/symbols/MorphShapeSymbol.hx, line 100 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/393#-L2_1u-5dCeGr-49zMAq:-L2_1u-5dCeGr-49zMAr:bvrg8l3) ([raw file](https://github.com/fishingcactus/openfl/blob/912d6846bff89f649e6562469abe8aff1dc628bf/format/swf/lite/symbols/MorphShapeSymbol.hx#L100)):*
> ```Haxe
> 
>                     if( startStyleChange.stateMoveTo ){
>                         startStyleChange.moveDeltaX += (lastEndStyleChange.moveDeltaX - startStyleChange.moveDeltaX) * ratio;
> ```

can't lastEndStyleChange be null here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/393)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/symbols/MorphShapeSymbol.hx, line 100 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/393#-L2_1u-5dCeGr-49zMAq:-L2_B8RKDEYAn-jOIN1i:b-tzplaf) ([raw file](https://github.com/fishingcactus/openfl/blob/912d6846bff89f649e6562469abe8aff1dc628bf/format/swf/lite/symbols/MorphShapeSymbol.hx#L100)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

can't lastEndStyleChange be null here?
</blockquote></details>

It should never happen. If it's null, then it's undefined from the specifications

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/393)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/symbols/MorphShapeSymbol.hx, line 100 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/393#-L2_1u-5dCeGr-49zMAq:-L2_JaD_N2psEx0f9qo_:b2nid0f) ([raw file](https://github.com/fishingcactus/openfl/blob/912d6846bff89f649e6562469abe8aff1dc628bf/format/swf/lite/symbols/MorphShapeSymbol.hx#L100)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

It should never happen. If it's null, then it's undefined from the specifications
</blockquote></details>

thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/393)*

**Pull request merged**
