### PR TITLE
Refactor Gradient filters

### PR DESCRIPTION
**Pull request by gogoprog**
Created a common class

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/231)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/231#-:-Kik6vVTm-DiQiDwqcVQ:bnfp4nl)*

**Comment by NuclearCookie** [comment]
@rams3s I remember you saying there was an issue with generating the shaders if we used subclasses? Was it about this?

**Comment by crazyjul** [comment]
Only if you put shader code, here it's just haxe code.

**Comment by NuclearCookie** [comment]
To verify, have you run a graphics test with this branch? @gogoprog

**Comment by gogoprog** [comment]
Well there is no change in the code logic but okay I'll run that tomorrow

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/231#-:-KjDGyWDU99M9sTV4j-_:b-kn6flt)*

**Comment by gogoprog** [comment]
I checked, all gradients look the same

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/231#-:-KjHVDKlbuydn86l-Zqk:b-5mxiit)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/231#-:-KjHlRP2Jp6BNyP96zeI:bnfp4nl)*

**Pull request merged**
