### PR TITLE
Improved performance in computeFlattenedChildren

### PR DESCRIPTION
**Pull request by NuclearCookie**
Several parts here:
* __allChildrenStack was a HaxeVector. It was never cleared. If at some point there were 100 elements less to update, we'd still
process those 100 old entries.
* It's not necessary to update non renderable items. When renderability is changed, update will be called ( at worst in the
next frame ). All accumulated displacement etc will then be called at that time. This does not affect movieclips playing,
because that logic is handled in __enterFrame.

* Some better inlining

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/286)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/286)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/286#-:-KoRWAMWA8xgIYt2ehGQ:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Stage.hx, line 702 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/286#-KoRa6nov5UAUoJ9vVlP:-KoRa6nov5UAUoJ9vVlQ:b-o82bsc) ([raw file](https://github.com/fishingcactus/openfl/blob/4d51002cf30da56b5716d5fd8e5ab99475d82764/openfl/display/Stage.hx#L702)):*
> ```Haxe
> 			if (stack_id.__children != null && stack_id.__children.length > 0) {
> 				for(child in stack_id.__children) {
> 					if (!child.isRenderable()) continue;
> ```

arghh, I nearly made the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/286)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Stage.hx, line 702 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/286#-KoRa6nov5UAUoJ9vVlP:-KofIPhd39XxF1F-9HB1:b32vin) ([raw file](https://github.com/fishingcactus/openfl/blob/4d51002cf30da56b5716d5fd8e5ab99475d82764/openfl/display/Stage.hx#L702)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

arghh, I nearly made the comment
</blockquote></details>

:D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/286)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/286)*

**Pull request merged**
