### PR TITLE
Feature/forbid cache update stops children

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/356)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/356)*

**Comment by gogoprog** [comment]
Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/356)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/356#-:-Kw48iy5-p4zVWgb5Is0:bnfp4nl)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/356#-:-Kw4F0VcBbq1JwdOWLn7:bnfp4nl)*

**Pull request merged**
