### PR TITLE
Don't overwrite cached parent. Fixes multiple levels of cacheAsBitmap…

### PR DESCRIPTION
**Pull request by NuclearCookie**
… rendering

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/257)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlSwH-VvTWyJ3Q4Nw_e:b6ht3lz) (no related file):*
This code doesn't seem to be independent of call order. CachedParent should store the closest cached parent in the hierarchy and it seems it won't always be the case.

Suppose the following chain: MC1 > MC2 > MC3.
Cache MC1 => MC2 and MC3 have MC1 as cached parent.
Now cache MC2, MC3 cached parent won't be updated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by crazyjul** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlT1hbquBDd0pRWu15j:b-vyuxoh) (no related file):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

This code doesn't seem to be independent of call order. CachedParent should store the closest cached parent in the hierarchy and it seems it won't always be the case.

Suppose the following chain: MC1 > MC2 > MC3.
Cache MC1 => MC2 and MC3 have MC1 as cached parent.
Now cache MC2, MC3 cached parent won't be updated.
</blockquote></details>

I do agree with Ramses, what situation this code is supposed to fix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlTI_goeXEGtIYjGHM4:b-iy7pmd) (no related file):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I do agree with Ramses, what situation this code is supposed to fix?
</blockquote></details>

Supposed to fix the following issue:
MC1(filters) > MC2(filters) > MC3(filters) > MC

MC will have its cachedParent setup as MC1.
MC1 will then be marked as dirty if necessary, but MC2 is not dirty. Expected behavior:
MC has MC1 as cached parent, MC1 has MC2 as cached parent, MC2 has MC3 as cached parent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlTNMjMEYTzQH-ffMPf:b8ohcvu) (no related file):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Supposed to fix the following issue:
MC1(filters) > MC2(filters) > MC3(filters) > MC

MC will have its cachedParent setup as MC1.
MC1 will then be marked as dirty if necessary, but MC2 is not dirty. Expected behavior:
MC has MC1 as cached parent, MC1 has MC2 as cached parent, MC2 has MC3 as cached parent
</blockquote></details>

if MC is marked dirty, the parenting chain will be reevaluated on the next render.  If not, the fix should be that the parenting chain is marked as dirty until the cachedparent is reached

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlTR-OQc-yIgJCAlrBz:bx6vpc) (no related file):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

if MC is marked dirty, the parenting chain will be reevaluated on the next render.  If not, the fix should be that the parenting chain is marked as dirty until the cachedparent is reached
</blockquote></details>

That works too, though technically, cachedParent is not its cached parent in that case. it's the parent of the parent of the cachedParent. Check out my updated code and let me know what you think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by crazyjul** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlTREY841vMDrKr2Ya-:b4fysj) (no related file):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

That works too, though technically, cachedParent is not its cached parent in that case. it's the parent of the parent of the cachedParent. Check out my updated code and let me know what you think
</blockquote></details>

Yes, that was the point. The idea is that you need to update the parent that is first cached. The issue might be different. If there's a in-between cached parent ( for filter e.g. ), it needs to be updated as well. But this fix won't do it. Maybe the best way is to create a list of cached parent. An item would linked its closest cached parent, which in turn would reference its closest cached parent as a link. Marking one as dirty would crawl to the highest cached parent, marking everything in between as dirty

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlSwH-VvTWyJ3Q4Nw_d:-KlTVj55knQIkMcaRwc5:b10ocrr) (no related file):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Yes, that was the point. The idea is that you need to update the parent that is first cached. The issue might be different. If there's a in-between cached parent ( for filter e.g. ), it needs to be updated as well. But this fix won't do it. Maybe the best way is to create a list of cached parent. An item would linked its closest cached parent, which in turn would reference its closest cached parent as a link. Marking one as dirty would crawl to the highest cached parent, marking everything in between as dirty
</blockquote></details>

That's how it's implemented now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 294 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlTZEaZI80X9k825yKx:-KlTZEaZI80X9k825yKy:b-aw717p) ([raw file](https://github.com/fishingcactus/openfl/blob/699d93536563c5777913958cb42885a6d0305d18/openfl/display/DisplayObject.hx#L294)):*
> } else {
> 			__cachedParent = null;
> 		}

if `__cachedParent` changes its cacheAsBitmap flag, this will reset `this.__cachedParent` to null without checking if another ancestor should be the new cached parent. I think you can simply drop the `add` parameter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObjectContainer.hx, line 332 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlTgXLzRr-b5bWMyjLK:-KlTgXLzRr-b5bWMyjLL:b-8h3thr) ([raw file](https://github.com/fishingcactus/openfl/blob/b64350df405b79ed2e17e53cde74e41b0b114293/openfl/display/DisplayObjectContainer.hx#L332)):*
> ```Haxe
> 		super.unSetCachedParent();
> 
> 		if ( __children != null ) {
> ```

You should only do this if this item is not cached

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 294 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlTZEaZI80X9k825yKx:-KlTlZIEh9JNl_em8XIl:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/699d93536563c5777913958cb42885a6d0305d18/openfl/display/DisplayObject.hx#L294)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

> } else {
> 			__cachedParent = null;
> 		}

if `__cachedParent` changes its cacheAsBitmap flag, this will reset `this.__cachedParent` to null without checking if another ancestor should be the new cached parent. I think you can simply drop the `add` parameter
</blockquote></details>

Done.

---

*[openfl/display/DisplayObjectContainer.hx, line 332 at r3](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-KlTgXLzRr-b5bWMyjLK:-KlTlj5HCG6512rqvCqT:b-a4kic4) ([raw file](https://github.com/fishingcactus/openfl/blob/b64350df405b79ed2e17e53cde74e41b0b114293/openfl/display/DisplayObjectContainer.hx#L332)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

You should only do this if this item is not cached
</blockquote></details>

I don't agree, The children need to update their cachedParent, whether this DisplayObjectContainer is cached or not ( check for higher cached objects ) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/257#-:-KlU08B7W_ktpx7UXk3c:bnfp4nl)*

**Pull request merged**
