### PR TITLE
Feature/smarter dirty

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/318)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Comment by gogoprog** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/DisplayObject.hx, line 121 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/318#-KsreOIKXDd2rnW4Lzco:-KsreOIKXDd2rnW4Lzcp:b5214qa) ([raw file](https://github.com/fishingcactus/openfl/blob/cf01a502e7f3c776d8b4876e1e06ea7bdae9216d/openfl/display/DisplayObject.hx#L121)):*
> ```Haxe
> 	private var __forceCacheAsBitmap:Bool;
> 	private var __updateCachedBitmap:Bool;
> 	private var __updateCachedBitmapLastFrame:Bool;
> ```

shouldnt it be only for #dev ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 121 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/318#-KsreOIKXDd2rnW4Lzco:-KsrekVbz9XaTeOakn9u:b-5eohqv) ([raw file](https://github.com/fishingcactus/openfl/blob/cf01a502e7f3c776d8b4876e1e06ea7bdae9216d/openfl/display/DisplayObject.hx#L121)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

shouldnt it be only for #dev ?
</blockquote></details>

No, needed for spritesheet exporter atm

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 121 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/318#-KsreOIKXDd2rnW4Lzco:-KssE6er1oQkxW6MG6kz:bj3e5j2) ([raw file](https://github.com/fishingcactus/openfl/blob/cf01a502e7f3c776d8b4876e1e06ea7bdae9216d/openfl/display/DisplayObject.hx#L121)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

No, needed for spritesheet exporter atm
</blockquote></details>

if possible, I'd rather try to keep that flag in the tool itself

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/DisplayObject.hx, line 121 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/318#-KsreOIKXDd2rnW4Lzco:-KswaIOMBNMwdwETMjQD:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/cf01a502e7f3c776d8b4876e1e06ea7bdae9216d/openfl/display/DisplayObject.hx#L121)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

if possible, I'd rather try to keep that flag in the tool itself
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/318)*

**Pull request merged**
