### PR TITLE
Fix Bounds computation and added new dev tools //patch

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/424)

### CODE REVIEW

**Review by rams3s — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/424)* status: all files reviewed, 1 unresolved discussion (waiting on @gogoprog, @crazyjul, and @NuclearCookie)

___
*[openfl/display/DisplayObjectContainer.hx, line 350 at r1](https://reviewable.io/reviews/fishingcactus/openfl/424#-LLBTUErEA9DcnNEceRA:-LLBTUEs8HeGOJZlpMUU:b-qa13s6) ([raw file](https://github.com/fishingcactus/openfl/blob/ffa0109ccdcc034e5d387ada4116ef21e8e01b94/openfl/display/DisplayObjectContainer.hx#L350)):*
> ```Haxe
> 	private override function __getBounds (rect:Rectangle):Void {
> 
> 		super.__getBounds (rect);
> ```

probably not called if `this` is not renderable but I think we shouldn't call `super.__getBound()` if it was the case (not renderable), should we?

**Comment by gogoprog** [comment]
___
*[openfl/display/DisplayObjectContainer.hx, line 350 at r1](https://reviewable.io/reviews/fishingcactus/openfl/424#-LLBTUErEA9DcnNEceRA:-LLBVvE1-9Se_dmW1DeG:b494j5y) ([raw file](https://github.com/fishingcactus/openfl/blob/ffa0109ccdcc034e5d387ada4116ef21e8e01b94/openfl/display/DisplayObjectContainer.hx#L350)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

probably not called if `this` is not renderable but I think we shouldn't call `super.__getBound()` if it was the case (not renderable), should we?
</blockquote></details>

As you said in the current code that check is always done outside of this func so shouldn't avoid double check?

**Review by rams3s — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/424)* status: all files reviewed, 1 unresolved discussion (waiting on @rams3s, @crazyjul, and @NuclearCookie)

___
*[openfl/display/DisplayObjectContainer.hx, line 350 at r1](https://reviewable.io/reviews/fishingcactus/openfl/424#-LLBTUErEA9DcnNEceRA:-LLC5zmV4825lp9JipUP:be20zk3) ([raw file](https://github.com/fishingcactus/openfl/blob/ffa0109ccdcc034e5d387ada4116ef21e8e01b94/openfl/display/DisplayObjectContainer.hx#L350)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

As you said in the current code that check is always done outside of this func so shouldn't avoid double check?
</blockquote></details>

indeed, might be preferable to keep it like this ;) Thanks

**Review by rams3s — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/424)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @crazyjul and @NuclearCookie)

**Pull request merged**
