### PR TITLE
Fix MovieClipPreprocessor : generate relevant shapes only

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/355)

### CODE REVIEW

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-:-Kw0QmdPqjm3_dvSEUcF:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 261 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-Kw0pQTFk-256BEzRCys:-Kw0pQTFk-256BEzRCyt:b-1p5qk8) ([raw file](https://github.com/fishingcactus/openfl/blob/563c3071c812433e722a33d690837bdc7166b6cb/openfl/utils/MovieClipPreprocessor.hx#L261)):*
> ```Haxe
>         while (frameIndex < symbol.frames.length && !timedOut ()) {
>             mainSprite.update(shapeTable, simpleSpritesToProcessTable, swflite, transform);
>             ++frameIndex;
> ```

I think we should get rid of this frame index now that we store one in Sprite

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355)*

**Comment by gogoprog** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 261 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-Kw0pQTFk-256BEzRCys:-Kw42keKvBSbgvxuWpxC:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/563c3071c812433e722a33d690837bdc7166b6cb/openfl/utils/MovieClipPreprocessor.hx#L261)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

I think we should get rid of this frame index now that we store one in Sprite
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 46 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-Kw4DnvkN-qw4kelT3Ug:-Kw4DnvkN-qw4kelT3Uh:b-ep10z9) ([raw file](https://github.com/fishingcactus/openfl/blob/099c01eb94f0c8bfa9603f12a6eb0b50aecc76b4/openfl/utils/MovieClipPreprocessor.hx#L46)):*
> if(parent == null) {
>             parent = Lib.current.stage;
>         }
>  
>         parent.addChild(tempClip);
>  
>         process(tempClip, cachePrecision, timeSliceMillisecondCount);
>  
>         parent.removeChild(tempClip);
Duplicate code. 
Just call renderComplete() after resolving the clip.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-:-Kw4ESUxMCeRw5ErrlBM:bnfp4nl)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/utils/MovieClipPreprocessor.hx, line 46 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/355#-Kw4DnvkN-qw4kelT3Ug:-Kw4sM54ZYhBnRgzQQEs:b3e08jq) ([raw file](https://github.com/fishingcactus/openfl/blob/099c01eb94f0c8bfa9603f12a6eb0b50aecc76b4/openfl/utils/MovieClipPreprocessor.hx#L46)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> if(parent == null) {
>             parent = Lib.current.stage;
>         }
>  
>         parent.addChild(tempClip);
>  
>         process(tempClip, cachePrecision, timeSliceMillisecondCount);
>  
>         parent.removeChild(tempClip);
Duplicate code. 
Just call renderComplete() after resolving the clip.
</blockquote></details>

Will be changed in future PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/355)*

**Pull request merged**
