### PR TITLE
Make sure mouse events are correctly put back in the pool.

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/371)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/371)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/events/MouseEvent.hx, line 102 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/371#-KxmF4VLiz8oSAZJjEe9:-KxmF4VLiz8oSAZJjEeA:bayst07) ([raw file](https://github.com/fishingcactus/openfl/blob/04ab5af1b262b13ebde13e67ad2b762aaea32798/openfl/events/MouseEvent.hx#L102)):*
> ```Haxe
> 		event.target = target;
> 
> 		// data from base class
> ```

would be safer to put that in a reset() function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/371)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/events/MouseEvent.hx, line 102 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/371#-KxmF4VLiz8oSAZJjEe9:-KxxNFf-GKmJi_a9PcKU:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/04ab5af1b262b13ebde13e67ad2b762aaea32798/openfl/events/MouseEvent.hx#L102)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

would be safer to put that in a reset() function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/371)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/371#-:-KyFtMtz2dhHskQeCWy8:bnfp4nl)*

**Pull request merged**
