### PR TITLE
Optimize/filters

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/173)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwdUGnoN3X3y8aphQQ:-KcwdUGoRpA7l4reUH9z:b-28t7tl) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L23)):*
> ```Haxe
> 		inline function getPassSampleCount (passIndex:Int):Int return perPassFetchCount + passIndex * (perPassFetchCount - 1);
> 
> 		function computeWeightTable():Float32Array {
> ```

A non inline inner function. Interesting. Intended? It's only used once

---

*[openfl/filters/commands/Blur1DCommand.hx, line 41 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwniQNkgzv9x63hIy2:-KcwniQNkgzv9x63hIy3:b-enruiu) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L41)):*
> ```Haxe
> 
> 				sampleCount = getPassSampleCount (passIndex);
> 				weightTable = new Float32Array(sampleCount);
> ```

I don't like this. Instead of allocating a `new Float32Array` here, can't you swap the previousWeightTable and the current weightTable? 

---

*[openfl/filters/commands/Blur1DCommand.hx, line 74 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwoN2N46-A0nYaCYNv:-KcwoN2N46-A0nYaCYNw:bd4faun) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L74)):*
> ```Haxe
> 		for (i in 0...weightTable.length) {
> 
> 			weightTable[i] *= strength;
> ```

Would be nice to embed this in the previous loop

---

*[openfl/filters/commands/Blur1DCommand.hx, line 78 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwoRoXWwIX7heJ7xob:-KcwoRoXWwIX7heJ7xoc:bhj8qq7) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L78)):*
> ```Haxe
> 		}
> 
> 		var totalFetchCount = weightTable.length;
> ```

If you're going to cache it.. cache it sooner and use it in the for loop above

---

*[openfl/filters/commands/Blur1DCommand.hx, line 85 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-Kcwp5wkKrXxYW2s9mrB:-Kcwp5wkKrXxYW2s9mrC:b-j1m35y) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L85)):*
> ```Haxe
> 
> 			weightTable = weightTable.subarray (halfTrimCount, totalFetchCount - halfTrimCount);
> 			totalFetchCount = weightTable.length;
> ```

totalFetchCount = MAXIMUM_FETCH_COUNT no?

---

*[openfl/filters/commands/Blur1DCommand.hx, line 95 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwpMysiMNd1ny1i1Jl:-KcwpMytCyktlIrhGzl7:bp2x6ua) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L95)):*
>              var pass_width = horizontal ? blur * quality - 1 : 0;
> 		var pass_height = horizontal ? 0 : blur * quality - 1;
> 		__shader.uFetchCount = totalFetchCount;
> 		__shader.uTexCoordDelta[0] = totalFetchCount > 1 ? pass_width / (totalFetchCount - 1) : 0;
> 		__shader.uTexCoordDelta[1] = totalFetchCount > 1 ? pass_height / (totalFetchCount - 1) : 0;
> 		__shader.uTexCoordOffset[0] = 0.5 * pass_width + offset.x;
> 		__shader.uTexCoordOffset[1] = 0.5 * pass_height + offset.y;
Could be rewritten as: 
```
var pass_width, pass_height;
if ( horizontal ) {
    pass_width = blur * quality - 1;
    pass_height = 0;
} else {
    pass_width = 0;
    pass_height = blur * quality - 1;
}
__shader.uFetchCount = totalFetchCount;
if ( totalFetchCount > 1 ) {
    __shader.uTexCoordDelta[0] =  pass_width / ( totalFetchCount - 1);
    __shader.uTexCoordDelta[1] =  pass_height / ( totalFetchCount - 1);
} else {
    __shader.uTexCoordDelta[0] = 0;
    __shader.uTexCoordDelta[1] = 0;
}
__shader.uTexCoordOffset[0] = 0.5 * pass_width + offset.x;
__shader.uTexCoordOffset[1] = 0.5 * pass_height + offset.y;
```
May not change a lot but it halves the number of conditions

---

*[openfl/filters/commands/Blur1DCommand.hx, line 97 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwszbYZTbw7VM6FpFI:-KcwszbZqvkfMguk5dkb:b-wqloh9) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L97)):*
> ```Haxe
> 		__shader.uTexCoordOffset[1] = 0.5 * pass_height + offset.y;
> 
> 		CommandHelper.apply (renderSession, target, source, __shader, source == target, function (renderSession:RenderSession) { preDrawCallback(renderSession, weightTable); } );
> ```

Too bad we need this closure here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Comment by NuclearCookie** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Comment by rams3s** [comment]
Review status: 3 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwdUGnoN3X3y8aphQQ:-KcwxYIDGAPd_sD1d5jF:bun01pu) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L23)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

A non inline inner function. Interesting. Intended? It's only used once
</blockquote></details>

was using it twice at first but kept it as it was showing a bit more clearly what that part of code was doing

---

*[openfl/filters/commands/Blur1DCommand.hx, line 41 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwniQNkgzv9x63hIy2:-KcwxJEUK7dZJ7fjcx9a:b-9bj0rb) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L41)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

I don't like this. Instead of allocating a `new Float32Array` here, can't you swap the previousWeightTable and the current weightTable? 
</blockquote></details>

did as you proposed at first but indices / offsets logic was a bit more complex and saved only one allocation when filter quality is high so I removed it ;p

---

*[openfl/filters/commands/Blur1DCommand.hx, line 74 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwoN2N46-A0nYaCYNv:-KcwxpherylqlBLPUgf6:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L74)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Would be nice to embed this in the previous loop
</blockquote></details>

Done.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 78 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwoRoXWwIX7heJ7xob:-Kcwy2YcH8wP-5OhmJIe:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L78)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

If you're going to cache it.. cache it sooner and use it in the for loop above
</blockquote></details>

Done.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 85 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-Kcwp5wkKrXxYW2s9mrB:-Kcww7ALH-WKxJavNDsS:bp9cc6b) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L85)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

totalFetchCount = MAXIMUM_FETCH_COUNT no?
</blockquote></details>

nope... could be different if trimCount is odd (e.g. if trimCount is 1, halfTrimCount will also be 1 because we want the filter to stay symmetric and we end up with MAXIMUM_FETCH_COUNT  - 1 elements)

---

*[openfl/filters/commands/Blur1DCommand.hx, line 95 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwpMysiMNd1ny1i1Jl:-KcwzMgXLe0pWjlLDzsW:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L95)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

>              var pass_width = horizontal ? blur * quality - 1 : 0;
> 		var pass_height = horizontal ? 0 : blur * quality - 1;
> 		__shader.uFetchCount = totalFetchCount;
> 		__shader.uTexCoordDelta[0] = totalFetchCount > 1 ? pass_width / (totalFetchCount - 1) : 0;
> 		__shader.uTexCoordDelta[1] = totalFetchCount > 1 ? pass_height / (totalFetchCount - 1) : 0;
> 		__shader.uTexCoordOffset[0] = 0.5 * pass_width + offset.x;
> 		__shader.uTexCoordOffset[1] = 0.5 * pass_height + offset.y;
Could be rewritten as: 
```
var pass_width, pass_height;
if ( horizontal ) {
    pass_width = blur * quality - 1;
    pass_height = 0;
} else {
    pass_width = 0;
    pass_height = blur * quality - 1;
}
__shader.uFetchCount = totalFetchCount;
if ( totalFetchCount > 1 ) {
    __shader.uTexCoordDelta[0] =  pass_width / ( totalFetchCount - 1);
    __shader.uTexCoordDelta[1] =  pass_height / ( totalFetchCount - 1);
} else {
    __shader.uTexCoordDelta[0] = 0;
    __shader.uTexCoordDelta[1] = 0;
}
__shader.uTexCoordOffset[0] = 0.5 * pass_width + offset.x;
__shader.uTexCoordOffset[1] = 0.5 * pass_height + offset.y;
```
May not change a lot but it halves the number of conditions
</blockquote></details>

Done.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 97 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwszbYZTbw7VM6FpFI:-Kcwy5GW85AIDGA9vdo_:b9fbkuj) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L97)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Too bad we need this closure here
</blockquote></details>

indeed but IMHO cleaner than relying on global state (ie static weight table)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Comment by rams3s** [comment]
Review status: 3 of 11 files reviewed at latest revision, 7 unresolved discussions.

---

*[openfl/filters/commands/Blur1DCommand.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-KcwdUGnoN3X3y8aphQQ:-Kcx1AVj1PezFr0cbrxG:b-e3iml4) ([raw file](https://github.com/fishingcactus/openfl/blob/6490a2049f61012ebfe47d13700a749928c4b3a2/openfl/filters/commands/Blur1DCommand.hx#L23)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

was using it twice at first but kept it as it was showing a bit more clearly what that part of code was doing
</blockquote></details>

made it inline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Comment by NuclearCookie** [comment]
Reviewed 8 of 8 files at r2.
Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: 10 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173#-:-Kcx5ucrx74P7EfhQmUt:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/173)*

**Pull request merged**
