### PR TITLE
Feature/list items

### PR DESCRIPTION
**Pull request by gogoprog**
<li> support in texts

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420#-:-LCSvAC18H42EMdkZahQ:bnfp4nl)*

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420#-:-LCSvVAK1IRQEQMNsXWc:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)*

**Comment by rams3s** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[openfl/_internal/text/TextEngine.hx, line 645 at r3](https://reviewable.io/reviews/fishingcactus/openfl/420#-LCTGGBR8nupmNRwY3hJ:-LCTGGBR8nupmNRwY3hK:b-wg6daf) ([raw file](https://github.com/fishingcactus/openfl/blob/96820b1c2cb45091452d8af6c577496e607cb4c9/openfl/_internal/text/TextEngine.hx#L645)):*
> ```Haxe
> 				width = __context.measureText (text).width;
> 			} else {
> 				width = __context.measureText (text.substring(startIndex, endIndex)).width;
> ```

is this gonna work with startIndex == null ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/text/TextEngine.hx, line 645 at r3](https://reviewable.io/reviews/fishingcactus/openfl/420#-LCTGGBR8nupmNRwY3hJ:-LCXfAXPCJlQEig9C-Q1:b-56bx2m) ([raw file](https://github.com/fishingcactus/openfl/blob/96820b1c2cb45091452d8af6c577496e607cb4c9/openfl/_internal/text/TextEngine.hx#L645)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

is this gonna work with startIndex == null ?
</blockquote></details>

Yes, if startIndex isnt defined, neither is endIndex.
I summon @nuclearcookie to confirm that

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/text/TextEngine.hx, line 645 at r3](https://reviewable.io/reviews/fishingcactus/openfl/420#-LCTGGBR8nupmNRwY3hJ:-LCY4bi58HpVZe8ElpKp:b-cfabe4) ([raw file](https://github.com/fishingcactus/openfl/blob/96820b1c2cb45091452d8af6c577496e607cb4c9/openfl/_internal/text/TextEngine.hx#L645)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Yes, if startIndex isnt defined, neither is endIndex.
I summon @nuclearcookie to confirm that
</blockquote></details>

doesn't matter much. it's an internal function and indeed, for the current usecases, it's either no start + end index, or both

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/420)*

**Pull request merged**
