### PR TITLE
Subpixel rendering

### PR DESCRIPTION
**Pull request by rams3s**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/306)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by crazyjul** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/BitmapData.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ks2q2_5cjc9ObEoyZR0:-Ks2q2_5cjc9ObEoyZR1:bay2dbm) ([raw file](https://github.com/fishingcactus/openfl/blob/f600180d3766917cf85caa86553b2c2688d35f24/openfl/display/BitmapData.hx#L50)):*
> ```Haxe
> 	private static var __isGLES:Null<Bool> = null;
> 
> 	public var height (default, null):Float;
> ```

Try  not to use null, it does not behaves correctly in some cases.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by NuclearCookie** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 192 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr0RD9kti3Z5UJjHqe:-Ksr0RD9kti3Z5UJjHqf:b-qamt3x) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L192)):*
> ```Haxe
> 		if (bitmapData == null) return;
> 
> 		renderBitmapDataEx(bitmapData, bitmapData.physicalWidth / bitmapData.__scaleX, bitmapData.physicalHeight / bitmapData.__scaleY, bitmapData.__uvData, smoothing, matrix, ct, alpha, blendMode, flashShader, pixelSnapping);
> ```

Since `physicalWidth = Math.ceil (width * scaleX) + 2 * padding;`
You'll account here for scaled down paddings. Not what you want I think.

---

*[openfl/display/BitmapData.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ks2q2_5cjc9ObEoyZR0:-Ksr2QsFh9_Xx3KdJfyX:b-p14bbt) ([raw file](https://github.com/fishingcactus/openfl/blob/f600180d3766917cf85caa86553b2c2688d35f24/openfl/display/BitmapData.hx#L50)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

Try  not to use null, it does not behaves correctly in some cases.
</blockquote></details>

Not sure if this applies here... It's used in a lot of places and I personally don't see issues with it

---

*[openfl/display/BitmapData.hx, line 612 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr0rwu4gtz28E5eVl2:-Ksr0rwu4gtz28E5eVl3:b-jp7r5s) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L612)):*
> ```Haxe
> 
> 		if (rect == null) {
> 			rect = @:privateAccess Rectangle.__temp;
> ```

Why __temp instead of pool.get() ?
We should remove those __temp variables. You have no guarantee that nobody else is using it when calling getPixels

---

*[openfl/display/BitmapData.hx, line 784 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr136J9p3nVEaKDDje:-Ksr136J9p3nVEaKDDjf:b5kgrmo) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L784)):*
> ```Haxe
> 			// 	}
> 
> 			// }
> ```

No need to comment out this code. If you place a throw, the code after it will be stripped out of the generated code.

---

*[openfl/display/BitmapData.hx, line 1213 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr1RVloBft-LKCKrT-:-Ksr1RVloBft-LKCKrT0:b-u3z6qp) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L1213)):*
> ```Haxe
> 
> 
> 	function __resize (width:Float, height:Float, padding:Int, scaleX:Float = 1.0, scaleY:Float = 1.0) {
> ```

no default value for padding? Seems strange to have to pass that. Maybe only update the value if it was set? (`padding:Null<Int>`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by gogoprog** [comment]
Reviewed 1 of 6 files at r1, 1 of 8 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 298 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr9CbscVsU9Q67NQwh:-Ksr9CbscVsU9Q67NQwi:b-sfajxl) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/format/swf/exporters/SWFLiteExporter.hx#L298)):*
> ```Haxe
> 
> 				var bitmapData = new BitmapData (data.bitmapWidth, data.bitmapHeight, transparent);
> 				var rect = new Rectangle (0, 0, data.bitmapWidth, data.bitmapHeight);
> ```

Can use a pooled Rectangle I guess

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 813 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KsrA2rPUZf0TKdF1-gc:-KsrA2rPUZf0TKdF1-gd:bgg1vdd) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L813)):*
> ```Haxe
> 
> 				var bounds = graphics.__bounds;
> 				var bitmap = BitmapData.fromCanvas (graphics.__canvas, bounds.width, bounds.height, padding, scaleX, scaleY);
> ```

Might be useful to create a BitmapData.fromGraphics

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by crazyjul** [comment]
Reviewed 7 of 8 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[openfl/display/BitmapData.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ks2q2_5cjc9ObEoyZR0:-KsrFlZh-pjcy6KKn5_k:brfn5m) ([raw file](https://github.com/fishingcactus/openfl/blob/f600180d3766917cf85caa86553b2c2688d35f24/openfl/display/BitmapData.hx#L50)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Not sure if this applies here... It's used in a lot of places and I personally don't see issues with it
</blockquote></details>

it doesn't behaves correctly when accessing the type with reflection. It allows to set it from outside, despite having no accessors. And in C++, it duplicates the variable

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by rams3s** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[format/swf/exporters/SWFLiteExporter.hx, line 298 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr9CbscVsU9Q67NQwh:-KsrI0mUsZfcJ1Sc7cEq:bn5poz8) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/format/swf/exporters/SWFLiteExporter.hx#L298)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Can use a pooled Rectangle I guess
</blockquote></details>

exporter  ;)

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 813 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KsrA2rPUZf0TKdF1-gc:-KsrKUcRLt48thSWRmE7:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L813)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

Might be useful to create a BitmapData.fromGraphics
</blockquote></details>

Done.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 192 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr0RD9kti3Z5UJjHqe:-KsrK_PYm00Sg-FojV2b:b8aaw3p) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L192)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Since `physicalWidth = Math.ceil (width * scaleX) + 2 * padding;`
You'll account here for scaled down paddings. Not what you want I think.

</blockquote></details>

As discussed, added inline functions to show that's on purpose (padding is expressed in physical space and needs to be rotated in fill vertices)

---

*[openfl/display/BitmapData.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ks2q2_5cjc9ObEoyZR0:-KsrOH-OcVmt1E7sJOsF:bf9djrv) ([raw file](https://github.com/fishingcactus/openfl/blob/f600180d3766917cf85caa86553b2c2688d35f24/openfl/display/BitmapData.hx#L50)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

it doesn't behaves correctly when accessing the type with reflection. It allows to set it from outside, despite having no accessors. And in C++, it duplicates the variable
</blockquote></details>

What do you suggest? I could use a (get, never) property and declare a private backing store but I'm not sure it changes anything in terms of safety against reflection... I guess it would still be possible to set the backing store from outside.

---

*[openfl/display/BitmapData.hx, line 612 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr0rwu4gtz28E5eVl2:-KsrIH2TYtoJ2jbJLd_w:b-s8gkt8) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L612)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Why __temp instead of pool.get() ?
We should remove those __temp variables. You have no guarantee that nobody else is using it when calling getPixels
</blockquote></details>

less expensive than pool and checked it wasn't used in getPixels ;)
otherwise, need to store if rect was provided as argument to not release it to pool after using it

---

*[openfl/display/BitmapData.hx, line 784 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr136J9p3nVEaKDDje:-KsrLTkLHVJC-UQkiStw:b-k0bjpl) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L784)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

No need to comment out this code. If you place a throw, the code after it will be stripped out of the generated code.
</blockquote></details>

Commenting out the code fails compilation ;p

---

*[openfl/display/BitmapData.hx, line 1213 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ksr1RVloBft-LKCKrT-:-KsrMxloafT60C79Nlym:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3a084930c66836e258dce1ba2e3ed8e4ebb90eb6/openfl/display/BitmapData.hx#L1213)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

no default value for padding? Seems strange to have to pass that. Maybe only update the value if it was set? (`padding:Null<Int>`)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by crazyjul** [comment]
Review status: 5 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[openfl/display/BitmapData.hx, line 50 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-Ks2q2_5cjc9ObEoyZR0:-Ksrl866Bzw06U4KmqCm:b-ubs0jd) ([raw file](https://github.com/fishingcactus/openfl/blob/f600180d3766917cf85caa86553b2c2688d35f24/openfl/display/BitmapData.hx#L50)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

What do you suggest? I could use a (get, never) property and declare a private backing store but I'm not sure it changes anything in terms of safety against reflection... I guess it would still be possible to set the backing store from outside.
</blockquote></details>

you don't need a backing store, you can still assign from inside

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by crazyjul** [comment]
Reviewed 12 of 14 files at r3.
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by crazyjul** [comment]
Reviewed 1 of 14 files at r3, 16 of 17 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by NuclearCookie** [comment]
Reviewed 3 of 14 files at r3, 6 of 17 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 518 at r4](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KtjiqlNPogpcUXidoJK:-KtjiqlNPogpcUXidoJL:bdccs6j) ([raw file](https://github.com/fishingcactus/openfl/blob/1513eda93624d01525f031d7d3f812a8d286248a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L518)):*
> ```Haxe
> 						graphics.__bitmap = cachedBitmapData;
> 						graphics.dirty = false;
> ```

early out. Release `renderBounds` back to the pool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 2 of 14 files at r3, 9 of 17 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[openfl/display/DisplayObject.hx, line 1183 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuO26QqhoS-lasM3BK0:-KuO26QqhoS-lasM3BK1:b-2xzdvl) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/display/DisplayObject.hx#L1183)):*
> ```Haxe
> 		__updateFilters = __filters != null && __filters.length > 0;
> 
> 		__mustRefreshGraphicsCounter = 2;
> ```

We should make this value a static const.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-:-KuO3rqJMFe9mdCy8ra0:bnfp4nl)*

**Comment by gogoprog** [comment]
Reviewed 2 of 8 files at r2, 3 of 14 files at r3, 12 of 17 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[openfl/geom/Rectangle.hx, line 271 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuODRhqHuHdJxhvAx7j:-KuODRhrohX8nWCDyApb:b6af93o) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/geom/Rectangle.hx#L271)):*
> ```Haxe
> 
> 
> 	public function __transform (rect:Rectangle, m:Matrix):Void {
> ```

it would be nice to remove the underscores when it becomes public ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by gogoprog** [comment]
*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 318 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuOxCuitZLcqAWkiAIV:-KuOxCuitZLcqAWkiAIW:b-8elem1) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/_internal/renderer/opengl/GLRenderer.hx#L318)):*
>  ?smooth:Bool)
can you use Null<Bool> here to be clearer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by gogoprog** [comment]
*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 318 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuOxCuitZLcqAWkiAIV:-KuOxOL9vycjM9D_dvLO:b-wjgq0q) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/_internal/renderer/opengl/GLRenderer.hx#L318)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

>  ?smooth:Bool)
can you use Null<Bool> here to be clearer?
</blockquote></details>

`Null<Bool>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by rams3s** [comment]
Review status: 18 of 25 files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 518 at r4](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KtjiqlNPogpcUXidoJK:-KuOxT0BY2W1h6_kOfOB:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/1513eda93624d01525f031d7d3f812a8d286248a/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L518)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

early out. Release `renderBounds` back to the pool
</blockquote></details>

Done.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 318 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuOxCuitZLcqAWkiAIV:-KuOxqH9UviK3WgfNtJ_:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/_internal/renderer/opengl/GLRenderer.hx#L318)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

`Null<Bool>`
</blockquote></details>

Done.

---

*[openfl/display/DisplayObject.hx, line 1183 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuO26QqhoS-lasM3BK0:-KuOyhFJ9bSblwlkpNpI:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/display/DisplayObject.hx#L1183)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

We should make this value a static const.
</blockquote></details>

Done.

---

*[openfl/geom/Rectangle.hx, line 271 at r5](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-KuODRhqHuHdJxhvAx7j:-KuOzxXwl9PbGepH3uW3:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/15641861ddca0539f8a6980ad848585b09f45c2a/openfl/geom/Rectangle.hx#L271)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

it would be nice to remove the underscores when it becomes public ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by gogoprog** [comment]
Reviewed 6 of 7 files at r6.
Review status: 24 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-:-KuP-gAKUIcibex4N44e:bnfp4nl)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/306#-:-KuP-hw596d8jZ6XossX:bnfp4nl)*

**Pull request merged**
