### PR TITLE
Reset caret and selection index if invalid

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/246)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Stage.hx, line 554 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/246#-KkA8j744ih6uWmgUCm4:-KkA8j744ih6uWmgUCm5:b-7w7adj) ([raw file](https://github.com/fishingcactus/openfl/blob/a348f13275cce12e4581b0d75dcc15e6c40e85c3/openfl/display/Stage.hx#L554)):*
> ```Haxe
> 		if (this.window == null || this.window != window) return;
> 
> 		// :NOTE: This is highly inperformant. Verify if we need this. Mouse event should generate new focus element?
> ```

The  question is more Does any item listen for this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/246#-:-KkA8rSA8CAPZn8EqMhJ:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/Stage.hx, line 554 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/246#-KkA8j744ih6uWmgUCm4:-KkA9Y6qfihxutTyufer:bmpjuk2) ([raw file](https://github.com/fishingcactus/openfl/blob/a348f13275cce12e4581b0d75dcc15e6c40e85c3/openfl/display/Stage.hx#L554)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

The  question is more Does any item listen for this
</blockquote></details>

Yes, all textboxes for example. But it does not make sense to do it this way. We should just let the __onMouseDown set the correct focus based on the hittest. On top of that, it's a broadcastFromStage, which means it will propagate to all the children if no listener is found. That can be up to 3000 children... 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/246)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openfl/text/TextField.hx, line 954 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/246#-KkA9ixQpxlbdZeL_IhE:-KkA9ixRYsrnQPVFMXao:b-ss01lb) ([raw file](https://github.com/fishingcactus/openfl/blob/a348f13275cce12e4581b0d75dcc15e6c40e85c3/openfl/text/TextField.hx#L954)):*
> if ( __selectionIndex > __textEngine.text.length ) {
> 				__caretIndex = __textEngine.text.length - 1;
> 			}
don't you mean assigning __selectionIndex ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/246)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/246)*

**Comment by gogoprog** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/246)*

**Pull request merged**
