### PR TITLE
Fix/vertex buffer3d

### PR DESCRIPTION
**Pull request by gogoprog**
Put back useful signature, ensure startVertex is zero

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/273)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display3D/VertexBuffer3D.hx, line 70 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/273#-Kn8irYrH6Fb_rtFJ0is:-Kn8irYrH6Fb_rtFJ0it:b-nami4p) ([raw file](https://github.com/fishingcactus/openfl/blob/967a40b268d72e9e2e1596ca9b65dbfafd35494f/openfl/display3D/VertexBuffer3D.hx#L70)):*
> ```Haxe
> 
> 
> 	public function uploadFromFloat32Array (data:Float32Array, startVertex:Int, numVertices:Int):Void {
> ```

Shouldn't those be default initialized?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/273)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/273)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display3D/VertexBuffer3D.hx, line 70 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/273#-Kn8irYrH6Fb_rtFJ0is:-KnEw2z0dyLcc56-Ngqo:b-8p91v1) ([raw file](https://github.com/fishingcactus/openfl/blob/967a40b268d72e9e2e1596ca9b65dbfafd35494f/openfl/display3D/VertexBuffer3D.hx#L70)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Shouldn't those be default initialized?
</blockquote></details>

No to be consistent with existing uploadFromVector function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/273)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/273#-:-KnEwMDXAY52YUrMaKHu:bnfp4nl)*

**Pull request merged**
