### PR TITLE
Improved call to bufferSubData. Creatly reduces GPU cost

### PR DESCRIPTION
**Pull request by NuclearCookie**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/312)

### CODE REVIEW

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 314 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-KsNFaxsrPb-d1IgPYA3:-KsNFaxtvY020Lte6DaK:b-g8hqvi) ([raw file](https://github.com/fishingcactus/openfl/blob/7bfe3d11191791e34f3a08a55867c7a955f72794/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L314)):*
> ```Haxe
> 
> 
> 		if (writtenVertexBytes > (vertexArraySize * 0.5)) {
> ```

I'm a bit puzzled at the 'arbitrary' value. It might depend on hardware and (not in our case, I know) graphics API.

Maybe it's possible to use something like http://api.haxe.org/js/html/DataView.html (JS only) to avoid the copy an still always provide a subrange?

Also `if (writtenVertexBytes > (vertexArraySize >> 1))` allows keeping Int all along.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 314 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-KsNFaxsrPb-d1IgPYA3:-KsNJhKnUp9vigwmVtvI:b-mdbfcq) ([raw file](https://github.com/fishingcactus/openfl/blob/7bfe3d11191791e34f3a08a55867c7a955f72794/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L314)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

I'm a bit puzzled at the 'arbitrary' value. It might depend on hardware and (not in our case, I know) graphics API.

Maybe it's possible to use something like http://api.haxe.org/js/html/DataView.html (JS only) to avoid the copy an still always provide a subrange?

Also `if (writtenVertexBytes > (vertexArraySize >> 1))` allows keeping Int all along.

</blockquote></details>

This code was here initially (written exactly like this). We removed it to avoid the allocation but the cost of the graphics is huge (uploading 40000 positions per drawcall).
I'll check that DataView!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 314 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-KsNFaxsrPb-d1IgPYA3:-KsNTUGPlH249WuAhfy5:bsv4e8r) ([raw file](https://github.com/fishingcactus/openfl/blob/7bfe3d11191791e34f3a08a55867c7a955f72794/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L314)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

This code was here initially (written exactly like this). We removed it to avoid the allocation but the cost of the graphics is huge (uploading 40000 positions per drawcall).
I'll check that DataView!
</blockquote></details>

We already use a BufferView, so no need to change that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by crazyjul** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 314 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-KsNFaxsrPb-d1IgPYA3:-KsNXCMoNers0M2BrvRr:b-ucqvv4) ([raw file](https://github.com/fishingcactus/openfl/blob/7bfe3d11191791e34f3a08a55867c7a955f72794/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L314)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

We already use a BufferView, so no need to change that
</blockquote></details>

I wonder, as the buffer view is nearly free. why not using it all the time?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 314 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-KsNFaxsrPb-d1IgPYA3:-KsN_RV9DjudebBWI7gK:b374pwz) ([raw file](https://github.com/fishingcactus/openfl/blob/7bfe3d11191791e34f3a08a55867c7a955f72794/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L314)):*
<details><summary><i>Previously, crazyjul (Julien Hamaide) wrote…</i></summary><blockquote>

I wonder, as the buffer view is nearly free. why not using it all the time?
</blockquote></details>

Yep, that has just been pushed! :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312)*

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/312#-:-KsNaHmiD4miBrl4h91R:bnfp4nl)*

**Pull request merged**
