### PR TITLE
Unless explicitly stated, bitmaps are drawn with PixelSnapping.AUTO /…

### PR DESCRIPTION
**Pull request by NuclearCookie**
…/major

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/139)

### CODE REVIEW

**Comment by rams3s** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 341 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/139#-KbKwSTPC3Hjd9j0dT0i:-KbKwSTPC3Hjd9j0dT0j:b-3tjfvs) ([raw file](https://github.com/fishingcactus/openfl/blob/3e29903ea625fcf1464ac38187fb437f3de630b4/openfl/_internal/renderer/opengl/GLRenderer.hx#L341)):*
> ```Haxe
> 			round_pixels = PixelSnapping.NEVER;
> 		}
> 		if ( round_pixels == PixelSnapping.AUTO ) {
> ```

No need to test for AUTO here. 'else' should be enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/139)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/139)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/opengl/GLRenderer.hx, line 341 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/139#-KbKwSTPC3Hjd9j0dT0i:-Kdjm5UNg4vWjpjr8-Rr:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/3e29903ea625fcf1464ac38187fb437f3de630b4/openfl/_internal/renderer/opengl/GLRenderer.hx#L341)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

No need to test for AUTO here. 'else' should be enough.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/139)*

**Comment by NuclearCookie** [comment]
@rams3s What's blocking this MR? Anything I should know?

**Pull request merged**
