### PR TITLE
Added forbidClearCache

### PR DESCRIPTION
**Pull request by gogoprog**
Useful to avoid clear on resize

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/342)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/symbols/ShapeSymbol.hx, line 19 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/342#-KvWBFfPBHcNVT66-vDh:-KvWBFfPBHcNVT66-vDi:b9l4c3n) ([raw file](https://github.com/fishingcactus/openfl/blob/c4c965aa083e92551af0fa3465e83feffcc4960c/format/swf/lite/symbols/ShapeSymbol.hx#L19)):*
> ```Haxe
> 	private var cachedTable:Array<CacheEntry>;
>     public var cachePrecision:Int = 100;
>     public var forbidClearCache:Bool = false;
> ```

forbidClearCacheOnResize would be better

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/342)*

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/342)*

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/342#-:-KvWLLRbWQ5yEAnrqH7o:bnfp4nl)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/342#-:-KvWLQ0PeoROnQRm3Mhq:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/342)*

**Pull request merged**
