### PR TITLE
Added RenderInfo in Profile to get info on draw count

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/302)

### CODE REVIEW

**Comment by rams3s** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/RenderSession.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/302#-KrAKLGDw2ToPfmEIypY:-KrAKLGDw2ToPfmEIypZ:b-nsqpci) ([raw file](https://github.com/fishingcactus/openfl/blob/b28bc0aafc880c2428e528f969f5ac2bd9ecba14/openfl/_internal/renderer/RenderSession.hx#L109)):*
> ```Haxe
> 
> 
> 	#if(profile && js)
> ```

`#if profile` should be enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/302)*

**Comment by gogoprog** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/RenderSession.hx, line 109 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/302#-KrAKLGDw2ToPfmEIypY:-KrAMrvy9xiAaM7q003M:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/b28bc0aafc880c2428e528f969f5ac2bd9ecba14/openfl/_internal/renderer/RenderSession.hx#L109)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

`#if profile` should be enough
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/302)*

**Comment by crazyjul** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/302)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/302#-:-KrFDmBNObThk-EWi_lc:bnfp4nl)*

**Pull request merged**
