### PR TITLE
Feature/filter without sprite batch

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/148)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 518 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA5_DDKsdXZwqvdEA3:-KbA5_DE7VndTV1PMwmt:bl8likx) ([raw file](https://github.com/fishingcactus/openfl/blob/7c55cf12d96d7acbbafd95df71ba4d4e67918f7f/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L518)):*
> ```Haxe
> 		}
> 		
> 		if (dirty) {
> ```

Instead of removing the dirty flag, why not mark dirty when calling setNextVertexBufferContext ?

---

*[openfl/filters/commands/CombineInnerCommand.hx, line 23 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA4WWmRDGWc5G0sFn3:-KbA4WWmRDGWc5G0sFn4:bttiah1) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CombineInnerCommand.hx#L23)):*
> @vertex var vertex = [
> 		'uniform vec2 openfl_uScaleVector;',
> 
> 		'void main(void)',
> 		'{',
> 			'${Shader.vTexCoord} = openfl_uScaleVector * ${Shader.aTexCoord};',
> 			'gl_Position = vec4(${Shader.aPosition} * 2.0 - 1.0, 0.0, 1.0);',
> 		'}',
> 	];
We could make a FilterShader class that does this by default. It avoid duplicating code

---

*[openfl/filters/commands/CommandHelper.hx, line 30 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA4sA4QYmuLwrrbHl4:-KbA4sA4QYmuLwrrbHl5:b-cqtzc7) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CommandHelper.hx#L30)):*
> ```Haxe
> 		attributes.push(new VertexAttribute(2, ElementType.FLOAT, false, DefAttrib.TexCoord));
> 
> 		vertexArray = new VertexArray(attributes, 4 * 4 * ( 2 + 2 ), true);
> ```

a small comment about those sizes would be cool ( or use variables )

---

*[openfl/filters/commands/CommandHelper.hx, line 69 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA52XQLNfLtFgBQmpX:-KbA52XQLNfLtFgBQmpY:bf1bxl) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CommandHelper.hx#L69)):*
> ```Haxe
> 		var gl = renderSession.gl;
> 
> 		//target.__drawGL(renderSession, source, source.rect, true, false, true);
> ```

Intended to be commented?

---

*[openfl/filters/commands/CommandHelper.hx, line 75 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA5Gtik-s1WpREl2qR:-KbA5Gtik-s1WpREl2qS:bj1zq9z) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CommandHelper.hx#L75)):*
> renderSession.shaderManager.setShader(internalShader);
> 
> 		vertexArray.bind();
> 		// TODO cache this somehow?, don't do each state change?
> 		internalShader.bindVertexArray(vertexArray);
You can cache this by checking if the shader has changed from the shader in the shadermanager. It's done the same way in the spritebatch now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148)*

**Comment by gogoprog** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 518 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA5_DDKsdXZwqvdEA3:-KbA8-RQkvTG_oEbYtbV:bmqvne5) ([raw file](https://github.com/fishingcactus/openfl/blob/7c55cf12d96d7acbbafd95df71ba4d4e67918f7f/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L518)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Instead of removing the dirty flag, why not mark dirty when calling setNextVertexBufferContext ?
</blockquote></details>

it will be dirty every drawcall because of setNextVertexBufferContext + the vertexArray must be rebound (another one can be bound outside of this code)

In fact the dirty flag should be completely removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148)*

**Comment by crazyjul** [comment]
Reviewed 14 of 15 files at r2, 1 of 2 files at r3.
Review status: 13 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/_internal/renderer/opengl/utils/SpriteBatch.hx, line 518 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA5_DDKsdXZwqvdEA3:-KbEjY2czdgl5ZMawkfT:bb7f2mf) ([raw file](https://github.com/fishingcactus/openfl/blob/7c55cf12d96d7acbbafd95df71ba4d4e67918f7f/openfl/_internal/renderer/opengl/utils/SpriteBatch.hx#L518)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

it will be dirty every drawcall because of setNextVertexBufferContext + the vertexArray must be rebound (another one can be bound outside of this code)

In fact the dirty flag should be completely removed
</blockquote></details>

done

---

*[openfl/filters/commands/CombineInnerCommand.hx, line 23 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA4WWmRDGWc5G0sFn3:-KbEjb_-AmdB66pEuzZ0:be58900) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CombineInnerCommand.hx#L23)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

> @vertex var vertex = [
> 		'uniform vec2 openfl_uScaleVector;',
> 
> 		'void main(void)',
> 		'{',
> 			'${Shader.vTexCoord} = openfl_uScaleVector * ${Shader.aTexCoord};',
> 			'gl_Position = vec4(${Shader.aPosition} * 2.0 - 1.0, 0.0, 1.0);',
> 		'}',
> 	];
We could make a FilterShader class that does this by default. It avoid duplicating code
</blockquote></details>

Doesn't work with the meta code that process shader. On top of it, there is difference in certain commands

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148)*

**Comment by crazyjul** [comment]
Reviewed 1 of 15 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148)*

**Comment by crazyjul** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[openfl/filters/commands/CommandHelper.hx, line 69 at r2](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-KbA52XQLNfLtFgBQmpX:-KbEjqeWdgeFaprfQRKC:ba3dfob) ([raw file](https://github.com/fishingcactus/openfl/blob/b3984010e8448c85a45e3438d132c179952a48f7/openfl/filters/commands/CommandHelper.hx#L69)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

Intended to be commented?
</blockquote></details>

Removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 13 of 15 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/148#-:-KbF05mJd_MXib_E_dnT:bnfp4nl)*

**Pull request merged**
