### PR TITLE
allow passing Void->Void to event listeners

### PR DESCRIPTION
**Pull request by NuclearCookie**
The goal of this is to avoid having to creating useless arguments all the time if you don't need the event to be passed.

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/324)

### CODE REVIEW

**Comment by crazyjul** [comment]
This is dangerous, function is just a typedef to dynamic. That would remove type safety.

Have you tried with Dynamic?->Void ?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/324#-:-KtpTnAlwDhPtwOdvwu0:buiy4v2)*

**Comment by gogoprog** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/events/EventDispatcher.hx, line 263 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/324#-KtpUzivp6CNATi3g_8a:-KtpUziwOk2oOyoCnlFs:bqm9xgg) ([raw file](https://github.com/fishingcactus/openfl/blob/83594d75eea52b868a2e1bdfe91e221f94bd339f/openfl/events/EventDispatcher.hx#L263)):*
> ```Haxe
> 
> 					//listener.callback (event.clone ());
> 					listener.callCallback (event);
> ```

I would try to call the JavaScript function.call(this, arg1, arg2, ..) here to avoid a call to a function and an array creation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/324)*

**Comment by NuclearCookie** [comment]
That's not a valid syntax. I couldn't find any way of providing a function signature with optional arguments... If you know a way, please tell me :)

I've added checks in dev mode to ensure that the passed callback is a function.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[openfl/events/EventDispatcher.hx, line 263 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/324#-KtpUzivp6CNATi3g_8a:-KtpXQy0PVRSxZH3U5Bw:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/83594d75eea52b868a2e1bdfe91e221f94bd339f/openfl/events/EventDispatcher.hx#L263)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

I would try to call the JavaScript function.call(this, arg1, arg2, ..) here to avoid a call to a function and an array creation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/324#-:-KtpWPGddKymPTh_ubeT:by5e7ep)*

**Comment by gogoprog** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/324#-:-Ktpf79WwiDonI7V4Wwe:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/324)*

**Pull request merged**
