### PR TITLE
Updated findDependentSymbols : find texts

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/329)

### CODE REVIEW

**Comment by NuclearCookie** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/329)*

**Comment by NuclearCookie** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/329#-KuP-342VwktsUTer2_A:-KuP-342VwktsUTer2_B:b-ns4y7t) ([raw file](https://github.com/fishingcactus/openfl/blob/96a1392a911816290830538cb3895d48662dba8c/format/swf/lite/symbols/SpriteSymbol.hx#L23)):*
> ```Haxe
> 	}
> 
> 	public function findDependentSymbols(swflite:SWFLite, shapes:Map<Int, ShapeSymbol>, simpleSprites:Map<Int, SimpleSpriteSymbol> = null, dynamicTexts:Map<Int, DynamicTextSymbol> = null):Void {
> ```

I would make the shapes also null by default.
That way I hope that Haxe is smart enough to guess the correct argument based on the type of the map that is being passed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/329)*

**Comment by gogoprog** [comment]
*[format/swf/lite/symbols/SpriteSymbol.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/329#-KuP-342VwktsUTer2_A:-KuP0-iRbhKyw06StD59:b-7f5gij) ([raw file](https://github.com/fishingcactus/openfl/blob/96a1392a911816290830538cb3895d48662dba8c/format/swf/lite/symbols/SpriteSymbol.hx#L23)):*
<details><summary><i>Previously, NuclearCookie (Pieter Vantorre) wrote…</i></summary><blockquote>

I would make the shapes also null by default.
That way I hope that Haxe is smart enough to guess the correct argument based on the type of the map that is being passed :)
</blockquote></details>

good point I always forgot this feature

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/329)*

**Comment by gogoprog** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[format/swf/lite/symbols/SpriteSymbol.hx, line 23 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/329#-KuP-342VwktsUTer2_A:-KuP38N2lfHpUl_aPHm9:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/96a1392a911816290830538cb3895d48662dba8c/format/swf/lite/symbols/SpriteSymbol.hx#L23)):*
<details><summary><i>Previously, gogoprog (Gauthier Billot) wrote…</i></summary><blockquote>

good point I always forgot this feature
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/329)*

**Comment by NuclearCookie** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/329#-:-KuP4WmzDopEcLVyBXsB:bnfp4nl)*

**Pull request merged**
