### PR TITLE
Now that we don't use copyPixels by default, copyPixels whenever the …

### PR DESCRIPTION
**Pull request by NuclearCookie**
…user requests the image. Includes dirty flag

---
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/319)

### CODE REVIEW

**Comment by gogoprog** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/319#-:-KswawAOYr2ok2oZy4AO:bnfp4nl)*

**Comment by crazyjul** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/319)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[openfl/display/BitmapData.hx, line 1270 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/319#-KswsFbcJQi39ERwvfRy:-KswsFbcJQi39ERwvfRz:b8g8j9n) ([raw file](https://github.com/fishingcactus/openfl/blob/75a8e3f38a6a1556ed1069857b66c0237ea659a1/openfl/display/BitmapData.hx#L1270)):*
> ```Haxe
> 			this.__pushFrameBuffer(renderSession);
> 			this.__popFrameBuffer(renderSession, true);
> 			__usingPingPongTexture = false;
> ```

I don' t think we should set the flag to false here (maybe set image.dirty in pop and use this flag instead?). Previously, if we set the readPixel flag of __popFrameBuffer() to true, __usingPingPongTexture would still be true (enforced by __popFrameBuffer() itself). Now, it' s not the case anymore...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/319)*

**Comment by NuclearCookie** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/display/BitmapData.hx, line 1270 at r1](https://reviewable.io:443/reviews/fishingcactus/openfl/319#-KswsFbcJQi39ERwvfRy:-KsxLC6GTKKBJGDbG7qc:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/75a8e3f38a6a1556ed1069857b66c0237ea659a1/openfl/display/BitmapData.hx#L1270)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

I don' t think we should set the flag to false here (maybe set image.dirty in pop and use this flag instead?). Previously, if we set the readPixel flag of __popFrameBuffer() to true, __usingPingPongTexture would still be true (enforced by __popFrameBuffer() itself). Now, it' s not the case anymore...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/319)*

**Comment by rams3s** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/fishingcactus/openfl/319)*

**Pull request merged**
