### PR TITLE
Feature/render scale

### PR DESCRIPTION
**Pull request by gogoprog**
This change is [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417)

### CODE REVIEW

**Comment by crazyjul** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417#-:-LBwPD3_66EnFzwDUpGj:bnfp4nl)*

**Comment by rams3s** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 539 at r2](https://reviewable.io/reviews/fishingcactus/openfl/417#-LBzEtyQ7NOMxp_Qv7r-:-LBzEtyR1gpmWVcF_QSh:bf2ullz) ([raw file](https://github.com/fishingcactus/openfl/blob/cb4aea461eed6e0874a967a5d322448d3404c05f/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L539)):*
> ```Haxe
> 						var shapeSymbol = cast(graphics.__symbol, ShapeSymbol);
> 						shapeSymbol.registerGraphics(graphics);
> 						cachedBitmapData = shapeSymbol.getCachedBitmapData (renderTransform);
> ```

can avoid searching for cached bitmap data if `disableCache` is true

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417)*

**Comment by gogoprog** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[openfl/_internal/renderer/canvas/CanvasGraphics.hx, line 539 at r2](https://reviewable.io/reviews/fishingcactus/openfl/417#-LBzEtyQ7NOMxp_Qv7r-:-LBzI08I9e-So7VkC7ql:b-896fix) ([raw file](https://github.com/fishingcactus/openfl/blob/cb4aea461eed6e0874a967a5d322448d3404c05f/openfl/_internal/renderer/canvas/CanvasGraphics.hx#L539)):*
<details><summary><i>Previously, rams3s wrote…</i></summary><blockquote>

can avoid searching for cached bitmap data if `disableCache` is true
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417)*

**Comment by rams3s** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417#-:-LBzdxT43jyT6j7B9z4L:bnfp4nl)*

**Comment by NuclearCookie** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fishingcactus/openfl/417)*

**Pull request merged**
